### ISSUE TITLE
Test hyphy_gard 2.5.31+galaxy1

### ISSUE THREAD

**Issue by jennaj** [mvdbeek/usegalaxy-tests#17]
Reported in bugs at .org

[toolshed.g2.bx.psu.edu/repos/iuc/hyphy_gard/hyphy_gard/2.5.31+galaxy1](http://toolshed.g2.bx.psu.edu/repos/iuc/hyphy_gard/hyphy_gard/2.5.31+galaxy1)

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/iuc/hyphy_gard/hyphy_gard/2.5.31+galaxy1

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 100.0%" aria-valuenow="1" aria-valuemin="0" aria-valuemax="1" data-toggle="tooltip" title="1 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="1" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="1" title="0 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 1 |
| Passed     | 1 |
| Error      | 0 |
| Failure    | 0 |
| Skipped    | 0 |


<details><summary>Passed s</summary>

* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/hyphy_gard/hyphy_gard (Test #1)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      --------------------------------------------------------------------------
      WARNING: Open MPI will create a shared memory backing file in a
      directory that appears to be mounted on a network filesystem.
      Creating the shared memory backup file on a network file system, such
      as NFS or Lustre is not recommended -- it may cause excessive network
      traffic to your file servers and/or cause shared memory traffic in
      Open MPI to be much slower than expected.

      You may want to check what the typical temporary directory is on your
      node.  Possible sources of the location of this temporary directory
      include the $TEMPDIR, $TEMP, and $TMP environment variables.

      Note, too, that system administrators can set a list of filesystems
      where Open MPI is disallowed from creating temporary files by setting
      the MCA parameter "orte_no_session_dir".

        Local host: galaxy-21.novalocal
        Filename:   /corral4/main/jobs/040/721/40721128/_job_tmp/ompi.galaxy-21.819800/pid.2011/1/shared_mem_cuda_pool.galaxy-21

      You can set the MCA paramter shmem_mmap_enable_nfs_warning to 0 to
      disable this message.
      --------------------------------------------------------------------------
      [2K
      [GARD] Breakpoint          1 of 21. Best cAIC =    1450.9683 with no breakpoints.[2K
      [GARD] Breakpoint          2 of 21. Best cAIC =    1450.9683 with no breakpoints.[2K
      [GARD] Breakpoint          3 of 21. Best cAIC =    1450.9683 with no breakpoints.[2K
      [GARD] Breakpoint          4 of 21. Best cAIC =    1450.9683 with no breakpoints.[2K
      [GARD] Breakpoint          5 of 21. Best cAIC =    1450.9683 with no breakpoints.[2K
      [GARD] Breakpoint          6 of 21. Best cAIC =    1450.9683 with no breakpoints.[2K
      [GARD] Breakpoint          7 of 21. Best cAIC =    1450.9683 with no breakpoints.[2K
      [GARD] Breakpoint          8 of 21. Best cAIC =    1450.9683 with no breakpoints.[2K
      [GARD] Breakpoint          9 of 21. Best cAIC =    1450.9683 with no breakpoints.[2K
      [GARD] Breakpoint         10 of 21. Best cAIC =    1450.9683 with no breakpoints.[2K
      [GARD] Breakpoint         11 of 21. Best cAIC =    1450.9683 with no breakpoints.[2K
      [GARD] Breakpoint         12 of 21. Best cAIC =    1450.9683 with no breakpoints.[2K
      [GARD] Breakpoint         13 of 21. Best cAIC =    1450.9683 with no breakpoints.[2K
      [GARD] Breakpoint         14 of 21. Best cAIC =    1450.9683 with no breakpoints.[2K
      [GARD] Breakpoint         15 of 21. Best cAIC =    1450.9683 with no breakpoints.[2K
      [GARD] Breakpoint         16 of 21. Best cAIC =    1450.9683 with no breakpoints.[2K
      [GARD] Breakpoint         17 of 21. Best cAIC =    1450.9683 with no breakpoints.[2K
      [GARD] Breakpoint         18 of 21. Best cAIC =    1450.9683 with no breakpoints.[2K
      [GARD] Breakpoint         19 of 21. Best cAIC =    1450.9683 with no breakpoints.[2K
      [GARD] Breakpoint         20 of 21. Best cAIC =    1450.9683 with no breakpoints.[2K
      [GARD] Breakpoint         21 of 21. Best cAIC =    1450.9683 with no breakpoints.[2K
                                                                                       [2K
      [2K
      [GARD]   2 breakpoints [ generation      1, total models       59,    0% converged,   inf/sec]. Min (c-AIC) =    1496.2474 [no improvement], breakpoints at 130, 198[2K
      [GARD]   2 breakpoints [ generation      2, total models       80,    1% converged, 80.00/sec]. Min (c-AIC) =    1496.2474 [no improvement], breakpoints at 130, 198[2K
      [GARD]   2 breakpoints [ generation      3, total models       93,    2% converged, 93.00/sec]. Min (c-AIC) =    1496.2474 [no improvement], breakpoints at 130, 198[2K
      [GARD]   2 breakpoints [ generation      4, total models      100,    3% converged, 100.00/sec]. Min (c-AIC) =    1496.2474 [no improvement], breakpoints at 130, 198[2K
      [GARD]   2 breakpoints [ generation      5, total models      133,    4% converged, 133.00/sec]. Min (c-AIC) =    1496.2474 [no improvement], breakpoints at 130, 198[2K
      [GARD]   2 breakpoints [ generation      6, total models      145,    0% converged, 145.00/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation      7, total models      151,    1% converged, 151.00/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation      8, total models      155,    2% converged, 155.00/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation      9, total models      157,    3% converged, 78.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     10, total models      159,    4% converged, 79.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     11, total models      161,    5% converged, 80.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     12, total models      161,    6% converged, 80.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     13, total models      162,    7% converged, 81.00/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     14, total models      163,    8% converged, 81.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     15, total models      163,    9% converged, 81.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     16, total models      163,   10% converged, 81.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     17, total models      163,   11% converged, 81.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     18, total models      163,   12% converged, 81.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     19, total models      163,   13% converged, 81.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     20, total models      163,   14% converged, 81.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[galaxy-21.novalocal:02011] 1 more process has sent help message help-opal-shmem-mmap.txt / mmap on nfs
      [galaxy-21.novalocal:02011] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
      [2K
      [GARD]   2 breakpoints [ generation     21, total models      163,   15% converged, 81.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     22, total models      163,   16% converged, 81.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     23, total models      163,   17% converged, 81.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     24, total models      163,   18% converged, 81.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     25, total models      163,   19% converged, 81.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     26, total models      163,   20% converged, 81.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     27, total models      163,   21% converged, 81.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     28, total models      163,   22% converged, 81.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     29, total models      163,   23% converged, 81.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     30, total models      163,   24% converged, 81.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     31, total models      163,   25% converged, 81.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     32, total models      163,   26% converged, 81.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     33, total models      163,   27% converged, 81.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     34, total models      163,   28% converged, 81.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     35, total models      163,   29% converged, 81.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     36, total models      163,   30% converged, 81.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     37, total models      163,   31% converged, 81.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     38, total models      163,   32% converged, 81.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     39, total models      163,   33% converged, 81.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     40, total models      163,   34% converged, 81.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     41, total models      176,   35% converged, 88.00/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     42, total models      179,   36% converged, 89.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     43, total models      179,   37% converged, 89.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     44, total models      180,   38% converged, 90.00/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     45, total models      181,   39% converged, 90.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     46, total models      181,   40% converged, 90.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     47, total models      181,   41% converged, 90.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     48, total models      181,   42% converged, 90.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     49, total models      181,   43% converged, 90.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     50, total models      181,   44% converged, 90.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     51, total models      181,   45% converged, 90.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     52, total models      181,   46% converged, 90.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     53, total models      181,   47% converged, 90.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     54, total models      181,   48% converged, 90.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     55, total models      181,   49% converged, 90.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     56, total models      181,   50% converged, 90.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     57, total models      181,   51% converged, 90.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     58, total models      181,   52% converged, 90.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     59, total models      181,   53% converged, 90.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     60, total models      181,   54% converged, 90.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     61, total models      181,   55% converged, 90.50/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     62, total models      181,   56% converged, 60.33/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     63, total models      181,   57% converged, 60.33/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     64, total models      181,   58% converged, 60.33/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     65, total models      181,   59% converged, 60.33/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     66, total models      181,   60% converged, 60.33/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     67, total models      181,   61% converged, 60.33/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     68, total models      181,   62% converged, 60.33/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     69, total models      181,   63% converged, 60.33/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     70, total models      181,   64% converged, 60.33/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     71, total models      181,   65% converged, 60.33/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     72, total models      187,   66% converged, 62.33/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     73, total models      187,   67% converged, 62.33/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     74, total models      187,   68% converged, 62.33/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     75, total models      187,   69% converged, 62.33/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     76, total models      187,   70% converged, 62.33/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     77, total models      187,   71% converged, 62.33/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     78, total models      187,   72% converged, 62.33/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     79, total models      187,   73% converged, 62.33/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     80, total models      187,   74% converged, 62.33/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     81, total models      187,   75% converged, 62.33/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     82, total models      187,   76% converged, 62.33/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     83, total models      187,   77% converged, 62.33/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     84, total models      187,   78% converged, 62.33/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     85, total models      187,   79% converged, 62.33/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     86, total models      187,   80% converged, 62.33/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     87, total models      187,   81% converged, 62.33/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     88, total models      187,   82% converged, 62.33/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     89, total models      187,   83% converged, 62.33/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     90, total models      187,   84% converged, 62.33/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     91, total models      187,   85% converged, 62.33/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     92, total models      187,   86% converged, 62.33/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     93, total models      187,   87% converged, 62.33/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     94, total models      187,   88% converged, 62.33/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     95, total models      187,   89% converged, 62.33/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     96, total models      187,   90% converged, 62.33/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     97, total models      187,   91% converged, 62.33/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     98, total models      187,   92% converged, 62.33/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation     99, total models      193,   93% converged, 64.33/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation    100, total models      195,   94% converged, 65.00/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation    101, total models      195,   95% converged, 65.00/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation    102, total models      195,   96% converged, 65.00/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation    103, total models      195,   97% converged, 65.00/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation    104, total models      195,   98% converged, 65.00/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation    105, total models      195,   99% converged, 65.00/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
      [GARD]   2 breakpoints [ generation    106, total models      195,  100% converged, 65.00/sec]. Min (c-AIC) =    1492.8803 [no improvement], breakpoints at 130, 253[2K
                                                                                                                                                                          [2K
      [galaxy-21.novalocal:02011] PMIX ERROR: NO-PERMISSIONS in file dstore_base.c at line 237

      ```
    **Standard Output:**

    * ```console
      
      Analysis Description
      --------------------
      GARD : Genetic Algorithms for Recombination Detection. Implements a
      heuristic approach to screening alignments of sequences for
      recombination, by using the CHC genetic algorithm to search for
      phylogenetic incongruence among different partitions of the data. The
      number of partitions is determined using a step-up procedure, while the
      placement of breakpoints is searched for with the GA. The best fitting
      model (based on c-AIC) is returned; and additional post-hoc tests run to
      distinguish topological incongruence from rate-variation. v0.2 adds and
      spooling results to JSON after each breakpoint search conclusion

      - __Requirements__: A sequence alignment.

      - __Citation__: **Automated Phylogenetic Detection of Recombination Using a Genetic
      Algorithm**, _Mol Biol Evol 23(10), 1891–1901

      - __Written by__: Sergei L Kosakovsky Pond

      - __Contact Information__: spond@temple.edu

      - __Analysis Version__: 0.2

      type: nucleotide
      rv: None
      mode: Normal
      >Loaded a nucleotide multiple sequence alignment with **12** sequences, **428** sites (22 of which are variable) from `/corral4/main/jobs/040/721/40721128/working/./input.fasta`
      >Minimum size of a partition is set to be 21 sites


      ### Fitting the baseline (single-partition; no breakpoints) model
      * Log(L) =  -694.30, AIC-c =  1450.97 (29 estimated parameters)

      ### Performing an exhaustive single breakpoint analysis
      Done with single breakpoint analysis.
         Best sinlge break point location: 198
         c-AIC  = 1471.012534343766

      ### Performing multi breakpoint analysis using a genetic algorithm
      Done with 2 breakpoint analysis.
          Best break point locations: 130, 253
          c-AIC = 1492.880273874196




      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | datatype | ` {"__current_case__": 0, "value": "nucleotide"} ` |
       | rate\_cond | ` {"__current_case__": 0, "rate": ""} ` |
       | \_\_job\_resource | ` {"__current_case__": 0, "__job_resource__select": "no"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


</details>
