### ISSUE TITLE
Test prokka 1.14.6+galaxy1

### ISSUE THREAD

**Issue by jennaj** [mvdbeek/usegalaxy-tests#18]
Failure reported at bugs & looks technical

toolshed.g2.bx.psu.edu/repos/crs4/prokka/prokka/1.14.6+galaxy1

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/crs4/prokka/prokka/1.14.6+galaxy1

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="1" data-toggle="tooltip" title="0 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="1" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 100.0%" aria-valuenow="1" aria-valuemin="0" aria-valuemax="1" title="1 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 1 |
| Passed     | 0 |
| Error      | 0 |
| Failure    | 1 |
| Skipped    | 0 |


<details><summary>Failed s</summary>

* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/crs4/prokka/prokka (Test #1)</summary><div class="padded">

    **Problems**:
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/crs4/prokka/prokka/1.14.6+galaxy1, exit_code: 2, stderr: Argument "1.7.8" isn't numeric in numeric lt (<) at /usr/local/bin/prokka line 259.
      Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/corral4/main/jobs/040/721/40721862/_job_tmp -Xmx28g -Xms256m
      Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/corral4/main/jobs/040/721/40721862/_job_tmp -Xmx28g -Xms256m
      Bio::SearchIO: hmmer3 cannot be found
      Exception 
      ------------- EXCEPTION -------------
      MSG: Failed to load module Bio::SearchIO::hmmer3. Can't locate Bio/SearchIO/hmmer3.pm in @INC (you may need to install the Bio::SearchIO::hmmer3 module) (@INC contains: /usr/local/lib/perl5/5.32/site_perl /usr/local/lib/perl5/site_perl /usr/local/lib/perl5/5.32/vendor_perl /usr/local/lib/perl5/vendor_perl /usr/local/lib/perl5/5.32/core_perl /usr/local/lib/perl5/core_perl .) at /usr/local/lib/perl5/site_perl/Bio/Root/Root.pm line 520.

      STACK Bio::Root::Root::_load_module /usr/local/lib/perl5/site_perl/Bio/Root/Root.pm:522
      STACK (eval) /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:620
      STACK Bio::SearchIO::_load_format_module /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:619
      STACK Bio::SearchIO::new /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:217
      STACK toplevel /usr/local/bin/prokka:1113
      -------------------------------------


      For more information about the SearchIO system please see the SearchIO docs.
      This includes ways of checking for formats at compile time, not run time
      Can't call method "next_result" on an undefined value at /usr/local/bin/prokka line 1114.
      .
      ```
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/crs4/prokka/prokka/1.14.6+galaxy1, exit_code: 2, stderr: Argument "1.7.8" isn't numeric in numeric lt (<) at /usr/local/bin/prokka line 259.
      Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/corral4/main/jobs/040/721/40721862/_job_tmp -Xmx28g -Xms256m
      Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/corral4/main/jobs/040/721/40721862/_job_tmp -Xmx28g -Xms256m
      Bio::SearchIO: hmmer3 cannot be found
      Exception 
      ------------- EXCEPTION -------------
      MSG: Failed to load module Bio::SearchIO::hmmer3. Can't locate Bio/SearchIO/hmmer3.pm in @INC (you may need to install the Bio::SearchIO::hmmer3 module) (@INC contains: /usr/local/lib/perl5/5.32/site_perl /usr/local/lib/perl5/site_perl /usr/local/lib/perl5/5.32/vendor_perl /usr/local/lib/perl5/vendor_perl /usr/local/lib/perl5/5.32/core_perl /usr/local/lib/perl5/core_perl .) at /usr/local/lib/perl5/site_perl/Bio/Root/Root.pm line 520.

      STACK Bio::Root::Root::_load_module /usr/local/lib/perl5/site_perl/Bio/Root/Root.pm:522
      STACK (eval) /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:620
      STACK Bio::SearchIO::_load_format_module /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:619
      STACK Bio::SearchIO::new /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:217
      STACK toplevel /usr/local/bin/prokka:1113
      -------------------------------------


      For more information about the SearchIO system please see the SearchIO docs.
      This includes ways of checking for formats at compile time, not run time
      Can't call method "next_result" on an undefined value at /usr/local/bin/prokka line 1114.
      .
      ```
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/crs4/prokka/prokka/1.14.6+galaxy1, exit_code: 2, stderr: Argument "1.7.8" isn't numeric in numeric lt (<) at /usr/local/bin/prokka line 259.
      Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/corral4/main/jobs/040/721/40721862/_job_tmp -Xmx28g -Xms256m
      Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/corral4/main/jobs/040/721/40721862/_job_tmp -Xmx28g -Xms256m
      Bio::SearchIO: hmmer3 cannot be found
      Exception 
      ------------- EXCEPTION -------------
      MSG: Failed to load module Bio::SearchIO::hmmer3. Can't locate Bio/SearchIO/hmmer3.pm in @INC (you may need to install the Bio::SearchIO::hmmer3 module) (@INC contains: /usr/local/lib/perl5/5.32/site_perl /usr/local/lib/perl5/site_perl /usr/local/lib/perl5/5.32/vendor_perl /usr/local/lib/perl5/vendor_perl /usr/local/lib/perl5/5.32/core_perl /usr/local/lib/perl5/core_perl .) at /usr/local/lib/perl5/site_perl/Bio/Root/Root.pm line 520.

      STACK Bio::Root::Root::_load_module /usr/local/lib/perl5/site_perl/Bio/Root/Root.pm:522
      STACK (eval) /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:620
      STACK Bio::SearchIO::_load_format_module /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:619
      STACK Bio::SearchIO::new /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:217
      STACK toplevel /usr/local/bin/prokka:1113
      -------------------------------------


      For more information about the SearchIO system please see the SearchIO docs.
      This includes ways of checking for formats at compile time, not run time
      Can't call method "next_result" on an undefined value at /usr/local/bin/prokka line 1114.
      .
      ```
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/crs4/prokka/prokka/1.14.6+galaxy1, exit_code: 2, stderr: Argument "1.7.8" isn't numeric in numeric lt (<) at /usr/local/bin/prokka line 259.
      Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/corral4/main/jobs/040/721/40721862/_job_tmp -Xmx28g -Xms256m
      Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/corral4/main/jobs/040/721/40721862/_job_tmp -Xmx28g -Xms256m
      Bio::SearchIO: hmmer3 cannot be found
      Exception 
      ------------- EXCEPTION -------------
      MSG: Failed to load module Bio::SearchIO::hmmer3. Can't locate Bio/SearchIO/hmmer3.pm in @INC (you may need to install the Bio::SearchIO::hmmer3 module) (@INC contains: /usr/local/lib/perl5/5.32/site_perl /usr/local/lib/perl5/site_perl /usr/local/lib/perl5/5.32/vendor_perl /usr/local/lib/perl5/vendor_perl /usr/local/lib/perl5/5.32/core_perl /usr/local/lib/perl5/core_perl .) at /usr/local/lib/perl5/site_perl/Bio/Root/Root.pm line 520.

      STACK Bio::Root::Root::_load_module /usr/local/lib/perl5/site_perl/Bio/Root/Root.pm:522
      STACK (eval) /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:620
      STACK Bio::SearchIO::_load_format_module /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:619
      STACK Bio::SearchIO::new /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:217
      STACK toplevel /usr/local/bin/prokka:1113
      -------------------------------------


      For more information about the SearchIO system please see the SearchIO docs.
      This includes ways of checking for formats at compile time, not run time
      Can't call method "next_result" on an undefined value at /usr/local/bin/prokka line 1114.
      .
      ```
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/crs4/prokka/prokka/1.14.6+galaxy1, exit_code: 2, stderr: Argument "1.7.8" isn't numeric in numeric lt (<) at /usr/local/bin/prokka line 259.
      Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/corral4/main/jobs/040/721/40721862/_job_tmp -Xmx28g -Xms256m
      Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/corral4/main/jobs/040/721/40721862/_job_tmp -Xmx28g -Xms256m
      Bio::SearchIO: hmmer3 cannot be found
      Exception 
      ------------- EXCEPTION -------------
      MSG: Failed to load module Bio::SearchIO::hmmer3. Can't locate Bio/SearchIO/hmmer3.pm in @INC (you may need to install the Bio::SearchIO::hmmer3 module) (@INC contains: /usr/local/lib/perl5/5.32/site_perl /usr/local/lib/perl5/site_perl /usr/local/lib/perl5/5.32/vendor_perl /usr/local/lib/perl5/vendor_perl /usr/local/lib/perl5/5.32/core_perl /usr/local/lib/perl5/core_perl .) at /usr/local/lib/perl5/site_perl/Bio/Root/Root.pm line 520.

      STACK Bio::Root::Root::_load_module /usr/local/lib/perl5/site_perl/Bio/Root/Root.pm:522
      STACK (eval) /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:620
      STACK Bio::SearchIO::_load_format_module /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:619
      STACK Bio::SearchIO::new /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:217
      STACK toplevel /usr/local/bin/prokka:1113
      -------------------------------------


      For more information about the SearchIO system please see the SearchIO docs.
      This includes ways of checking for formats at compile time, not run time
      Can't call method "next_result" on an undefined value at /usr/local/bin/prokka line 1114.
      .
      ```
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/crs4/prokka/prokka/1.14.6+galaxy1, exit_code: 2, stderr: Argument "1.7.8" isn't numeric in numeric lt (<) at /usr/local/bin/prokka line 259.
      Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/corral4/main/jobs/040/721/40721862/_job_tmp -Xmx28g -Xms256m
      Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/corral4/main/jobs/040/721/40721862/_job_tmp -Xmx28g -Xms256m
      Bio::SearchIO: hmmer3 cannot be found
      Exception 
      ------------- EXCEPTION -------------
      MSG: Failed to load module Bio::SearchIO::hmmer3. Can't locate Bio/SearchIO/hmmer3.pm in @INC (you may need to install the Bio::SearchIO::hmmer3 module) (@INC contains: /usr/local/lib/perl5/5.32/site_perl /usr/local/lib/perl5/site_perl /usr/local/lib/perl5/5.32/vendor_perl /usr/local/lib/perl5/vendor_perl /usr/local/lib/perl5/5.32/core_perl /usr/local/lib/perl5/core_perl .) at /usr/local/lib/perl5/site_perl/Bio/Root/Root.pm line 520.

      STACK Bio::Root::Root::_load_module /usr/local/lib/perl5/site_perl/Bio/Root/Root.pm:522
      STACK (eval) /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:620
      STACK Bio::SearchIO::_load_format_module /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:619
      STACK Bio::SearchIO::new /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:217
      STACK toplevel /usr/local/bin/prokka:1113
      -------------------------------------


      For more information about the SearchIO system please see the SearchIO docs.
      This includes ways of checking for formats at compile time, not run time
      Can't call method "next_result" on an undefined value at /usr/local/bin/prokka line 1114.
      .
      ```
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/crs4/prokka/prokka/1.14.6+galaxy1, exit_code: 2, stderr: Argument "1.7.8" isn't numeric in numeric lt (<) at /usr/local/bin/prokka line 259.
      Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/corral4/main/jobs/040/721/40721862/_job_tmp -Xmx28g -Xms256m
      Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/corral4/main/jobs/040/721/40721862/_job_tmp -Xmx28g -Xms256m
      Bio::SearchIO: hmmer3 cannot be found
      Exception 
      ------------- EXCEPTION -------------
      MSG: Failed to load module Bio::SearchIO::hmmer3. Can't locate Bio/SearchIO/hmmer3.pm in @INC (you may need to install the Bio::SearchIO::hmmer3 module) (@INC contains: /usr/local/lib/perl5/5.32/site_perl /usr/local/lib/perl5/site_perl /usr/local/lib/perl5/5.32/vendor_perl /usr/local/lib/perl5/vendor_perl /usr/local/lib/perl5/5.32/core_perl /usr/local/lib/perl5/core_perl .) at /usr/local/lib/perl5/site_perl/Bio/Root/Root.pm line 520.

      STACK Bio::Root::Root::_load_module /usr/local/lib/perl5/site_perl/Bio/Root/Root.pm:522
      STACK (eval) /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:620
      STACK Bio::SearchIO::_load_format_module /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:619
      STACK Bio::SearchIO::new /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:217
      STACK toplevel /usr/local/bin/prokka:1113
      -------------------------------------


      For more information about the SearchIO system please see the SearchIO docs.
      This includes ways of checking for formats at compile time, not run time
      Can't call method "next_result" on an undefined value at /usr/local/bin/prokka line 1114.
      .
      ```
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/crs4/prokka/prokka/1.14.6+galaxy1, exit_code: 2, stderr: Argument "1.7.8" isn't numeric in numeric lt (<) at /usr/local/bin/prokka line 259.
      Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/corral4/main/jobs/040/721/40721862/_job_tmp -Xmx28g -Xms256m
      Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/corral4/main/jobs/040/721/40721862/_job_tmp -Xmx28g -Xms256m
      Bio::SearchIO: hmmer3 cannot be found
      Exception 
      ------------- EXCEPTION -------------
      MSG: Failed to load module Bio::SearchIO::hmmer3. Can't locate Bio/SearchIO/hmmer3.pm in @INC (you may need to install the Bio::SearchIO::hmmer3 module) (@INC contains: /usr/local/lib/perl5/5.32/site_perl /usr/local/lib/perl5/site_perl /usr/local/lib/perl5/5.32/vendor_perl /usr/local/lib/perl5/vendor_perl /usr/local/lib/perl5/5.32/core_perl /usr/local/lib/perl5/core_perl .) at /usr/local/lib/perl5/site_perl/Bio/Root/Root.pm line 520.

      STACK Bio::Root::Root::_load_module /usr/local/lib/perl5/site_perl/Bio/Root/Root.pm:522
      STACK (eval) /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:620
      STACK Bio::SearchIO::_load_format_module /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:619
      STACK Bio::SearchIO::new /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:217
      STACK toplevel /usr/local/bin/prokka:1113
      -------------------------------------


      For more information about the SearchIO system please see the SearchIO docs.
      This includes ways of checking for formats at compile time, not run time
      Can't call method "next_result" on an undefined value at /usr/local/bin/prokka line 1114.
      .
      ```
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/crs4/prokka/prokka/1.14.6+galaxy1, exit_code: 2, stderr: Argument "1.7.8" isn't numeric in numeric lt (<) at /usr/local/bin/prokka line 259.
      Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/corral4/main/jobs/040/721/40721862/_job_tmp -Xmx28g -Xms256m
      Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/corral4/main/jobs/040/721/40721862/_job_tmp -Xmx28g -Xms256m
      Bio::SearchIO: hmmer3 cannot be found
      Exception 
      ------------- EXCEPTION -------------
      MSG: Failed to load module Bio::SearchIO::hmmer3. Can't locate Bio/SearchIO/hmmer3.pm in @INC (you may need to install the Bio::SearchIO::hmmer3 module) (@INC contains: /usr/local/lib/perl5/5.32/site_perl /usr/local/lib/perl5/site_perl /usr/local/lib/perl5/5.32/vendor_perl /usr/local/lib/perl5/vendor_perl /usr/local/lib/perl5/5.32/core_perl /usr/local/lib/perl5/core_perl .) at /usr/local/lib/perl5/site_perl/Bio/Root/Root.pm line 520.

      STACK Bio::Root::Root::_load_module /usr/local/lib/perl5/site_perl/Bio/Root/Root.pm:522
      STACK (eval) /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:620
      STACK Bio::SearchIO::_load_format_module /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:619
      STACK Bio::SearchIO::new /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:217
      STACK toplevel /usr/local/bin/prokka:1113
      -------------------------------------


      For more information about the SearchIO system please see the SearchIO docs.
      This includes ways of checking for formats at compile time, not run time
      Can't call method "next_result" on an undefined value at /usr/local/bin/prokka line 1114.
      .
      ```
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/crs4/prokka/prokka/1.14.6+galaxy1, exit_code: 2, stderr: Argument "1.7.8" isn't numeric in numeric lt (<) at /usr/local/bin/prokka line 259.
      Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/corral4/main/jobs/040/721/40721862/_job_tmp -Xmx28g -Xms256m
      Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/corral4/main/jobs/040/721/40721862/_job_tmp -Xmx28g -Xms256m
      Bio::SearchIO: hmmer3 cannot be found
      Exception 
      ------------- EXCEPTION -------------
      MSG: Failed to load module Bio::SearchIO::hmmer3. Can't locate Bio/SearchIO/hmmer3.pm in @INC (you may need to install the Bio::SearchIO::hmmer3 module) (@INC contains: /usr/local/lib/perl5/5.32/site_perl /usr/local/lib/perl5/site_perl /usr/local/lib/perl5/5.32/vendor_perl /usr/local/lib/perl5/vendor_perl /usr/local/lib/perl5/5.32/core_perl /usr/local/lib/perl5/core_perl .) at /usr/local/lib/perl5/site_perl/Bio/Root/Root.pm line 520.

      STACK Bio::Root::Root::_load_module /usr/local/lib/perl5/site_perl/Bio/Root/Root.pm:522
      STACK (eval) /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:620
      STACK Bio::SearchIO::_load_format_module /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:619
      STACK Bio::SearchIO::new /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:217
      STACK toplevel /usr/local/bin/prokka:1113
      -------------------------------------


      For more information about the SearchIO system please see the SearchIO docs.
      This includes ways of checking for formats at compile time, not run time
      Can't call method "next_result" on an undefined value at /usr/local/bin/prokka line 1114.
      .
      ```
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/crs4/prokka/prokka/1.14.6+galaxy1, exit_code: 2, stderr: Argument "1.7.8" isn't numeric in numeric lt (<) at /usr/local/bin/prokka line 259.
      Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/corral4/main/jobs/040/721/40721862/_job_tmp -Xmx28g -Xms256m
      Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/corral4/main/jobs/040/721/40721862/_job_tmp -Xmx28g -Xms256m
      Bio::SearchIO: hmmer3 cannot be found
      Exception 
      ------------- EXCEPTION -------------
      MSG: Failed to load module Bio::SearchIO::hmmer3. Can't locate Bio/SearchIO/hmmer3.pm in @INC (you may need to install the Bio::SearchIO::hmmer3 module) (@INC contains: /usr/local/lib/perl5/5.32/site_perl /usr/local/lib/perl5/site_perl /usr/local/lib/perl5/5.32/vendor_perl /usr/local/lib/perl5/vendor_perl /usr/local/lib/perl5/5.32/core_perl /usr/local/lib/perl5/core_perl .) at /usr/local/lib/perl5/site_perl/Bio/Root/Root.pm line 520.

      STACK Bio::Root::Root::_load_module /usr/local/lib/perl5/site_perl/Bio/Root/Root.pm:522
      STACK (eval) /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:620
      STACK Bio::SearchIO::_load_format_module /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:619
      STACK Bio::SearchIO::new /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:217
      STACK toplevel /usr/local/bin/prokka:1113
      -------------------------------------


      For more information about the SearchIO system please see the SearchIO docs.
      This includes ways of checking for formats at compile time, not run time
      Can't call method "next_result" on an undefined value at /usr/local/bin/prokka line 1114.
      .
      ```
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/crs4/prokka/prokka/1.14.6+galaxy1, exit_code: 2, stderr: Argument "1.7.8" isn't numeric in numeric lt (<) at /usr/local/bin/prokka line 259.
      Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/corral4/main/jobs/040/721/40721862/_job_tmp -Xmx28g -Xms256m
      Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/corral4/main/jobs/040/721/40721862/_job_tmp -Xmx28g -Xms256m
      Bio::SearchIO: hmmer3 cannot be found
      Exception 
      ------------- EXCEPTION -------------
      MSG: Failed to load module Bio::SearchIO::hmmer3. Can't locate Bio/SearchIO/hmmer3.pm in @INC (you may need to install the Bio::SearchIO::hmmer3 module) (@INC contains: /usr/local/lib/perl5/5.32/site_perl /usr/local/lib/perl5/site_perl /usr/local/lib/perl5/5.32/vendor_perl /usr/local/lib/perl5/vendor_perl /usr/local/lib/perl5/5.32/core_perl /usr/local/lib/perl5/core_perl .) at /usr/local/lib/perl5/site_perl/Bio/Root/Root.pm line 520.

      STACK Bio::Root::Root::_load_module /usr/local/lib/perl5/site_perl/Bio/Root/Root.pm:522
      STACK (eval) /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:620
      STACK Bio::SearchIO::_load_format_module /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:619
      STACK Bio::SearchIO::new /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:217
      STACK toplevel /usr/local/bin/prokka:1113
      -------------------------------------


      For more information about the SearchIO system please see the SearchIO docs.
      This includes ways of checking for formats at compile time, not run time
      Can't call method "next_result" on an undefined value at /usr/local/bin/prokka line 1114.
      .
      ```
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/crs4/prokka/prokka/1.14.6+galaxy1, exit_code: 2, stderr: Argument "1.7.8" isn't numeric in numeric lt (<) at /usr/local/bin/prokka line 259.
      Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/corral4/main/jobs/040/721/40721862/_job_tmp -Xmx28g -Xms256m
      Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/corral4/main/jobs/040/721/40721862/_job_tmp -Xmx28g -Xms256m
      Bio::SearchIO: hmmer3 cannot be found
      Exception 
      ------------- EXCEPTION -------------
      MSG: Failed to load module Bio::SearchIO::hmmer3. Can't locate Bio/SearchIO/hmmer3.pm in @INC (you may need to install the Bio::SearchIO::hmmer3 module) (@INC contains: /usr/local/lib/perl5/5.32/site_perl /usr/local/lib/perl5/site_perl /usr/local/lib/perl5/5.32/vendor_perl /usr/local/lib/perl5/vendor_perl /usr/local/lib/perl5/5.32/core_perl /usr/local/lib/perl5/core_perl .) at /usr/local/lib/perl5/site_perl/Bio/Root/Root.pm line 520.

      STACK Bio::Root::Root::_load_module /usr/local/lib/perl5/site_perl/Bio/Root/Root.pm:522
      STACK (eval) /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:620
      STACK Bio::SearchIO::_load_format_module /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:619
      STACK Bio::SearchIO::new /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:217
      STACK toplevel /usr/local/bin/prokka:1113
      -------------------------------------


      For more information about the SearchIO system please see the SearchIO docs.
      This includes ways of checking for formats at compile time, not run time
      Can't call method "next_result" on an undefined value at /usr/local/bin/prokka line 1114.
      .
      ```
    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      2
      ```
    **Standard Error:**

    * ```console
      Argument "1.7.8" isn't numeric in numeric lt (<) at /usr/local/bin/prokka line 259.
      Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/corral4/main/jobs/040/721/40721862/_job_tmp -Xmx28g -Xms256m
      Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/corral4/main/jobs/040/721/40721862/_job_tmp -Xmx28g -Xms256m
      Bio::SearchIO: hmmer3 cannot be found
      Exception 
      ------------- EXCEPTION -------------
      MSG: Failed to load module Bio::SearchIO::hmmer3. Can't locate Bio/SearchIO/hmmer3.pm in @INC (you may need to install the Bio::SearchIO::hmmer3 module) (@INC contains: /usr/local/lib/perl5/5.32/site_perl /usr/local/lib/perl5/site_perl /usr/local/lib/perl5/5.32/vendor_perl /usr/local/lib/perl5/vendor_perl /usr/local/lib/perl5/5.32/core_perl /usr/local/lib/perl5/core_perl .) at /usr/local/lib/perl5/site_perl/Bio/Root/Root.pm line 520.

      STACK Bio::Root::Root::_load_module /usr/local/lib/perl5/site_perl/Bio/Root/Root.pm:522
      STACK (eval) /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:620
      STACK Bio::SearchIO::_load_format_module /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:619
      STACK Bio::SearchIO::new /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:217
      STACK toplevel /usr/local/bin/prokka:1113
      -------------------------------------


      For more information about the SearchIO system please see the SearchIO docs.
      This includes ways of checking for formats at compile time, not run time
      Can't call method "next_result" on an undefined value at /usr/local/bin/prokka line 1114.

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | locustag | ` "" ` |
       | increment | ` "1" ` |
       | gffver | ` "3" ` |
       | compliant | ` {"__current_case__": 0, "addgenes": "false", "compliant_select": "no", "mincontig": "200"} ` |
       | centre | ` "" ` |
       | genus | ` "" ` |
       | species | ` "" ` |
       | strain | ` "" ` |
       | plasmid | ` "" ` |
       | kingdom | ` {"__current_case__": 1, "gcode": "11", "kingdom_select": "Bacteria"} ` |
       | usegenus | ` "false" ` |
       | proteins | ` None ` |
       | metagenome | ` "false" ` |
       | fast | ` "false" ` |
       | evalue | ` "1e-06" ` |
       | rfam | ` "false" ` |
       | norrna | ` "false" ` |
       | notrna | ` "false" ` |
       | outputs | ` ["gff", "gbk", "fna", "faa", "ffn", "sqn", "fsa", "tbl", "tsv", "err", "txt"] ` |
       | \_\_job\_resource | ` {"__current_case__": 0, "__job_resource__select": "no"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "fasta" ` |



  </div></details>


</details>

**Comment by jennaj** [comment]
Looks like a dependency is missing:

> Bio::SearchIO: hmmer3 cannot be found
> Exception 
> ------------- EXCEPTION -------------
> MSG: Failed to load module Bio::SearchIO::hmmer3. Can't locate Bio/SearchIO/hmmer3.pm in @INC (you may need to install the Bio::SearchIO::hmmer3 module) (@INC contains: /usr/local/lib/perl5/5.32/site_perl /usr/local/lib/perl5/site_perl /usr/local/lib/perl5/5.32/vendor_perl /usr/local/lib/perl5/vendor_perl /usr/local/lib/perl5/5.32/core_perl /usr/local/lib/perl5/core_perl .) at /usr/local/lib/perl5/site_perl/Bio/Root/Root.pm line 520.
> 
> STACK Bio::Root::Root::_load_module /usr/local/lib/perl5/site_perl/Bio/Root/Root.pm:522
> STACK (eval) /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:620
> STACK Bio::SearchIO::_load_format_module /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:619
> STACK Bio::SearchIO::new /usr/local/lib/perl5/site_perl/Bio/SearchIO.pm:217
> STACK toplevel /usr/local/bin/prokka:1113
