### ISSUE TITLE
Test build_ucsc_custom_track_1 1.0.0 (+ 1.0.1 once updated on org)

### ISSUE THREAD

**Issue by jennaj** [mvdbeek/usegalaxy-tests#19]
Older tool. Was failing at ORG in January, this is a retest

toolshed.g2.bx.psu.edu/repos/devteam/ucsc_custom_track/build_ucsc_custom_track_1/1.0.0

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/devteam/ucsc_custom_track/build_ucsc_custom_track_1/1.0.0

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="1" data-toggle="tooltip" title="0 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="1" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 100.0%" aria-valuenow="1" aria-valuemin="0" aria-valuemax="1" title="1 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 1 |
| Passed     | 0 |
| Error      | 0 |
| Failure    | 1 |
| Skipped    | 0 |


<details><summary>Failed s</summary>

* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/devteam/ucsc_custom_track/build_ucsc_custom_track_1 (Test #1)</summary><div class="padded">

    **Problems**:
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/devteam/ucsc_custom_track/build_ucsc_custom_track_1/1.0.0, exit_code: 1, stderr:   File "/cvmfs/main.galaxyproject.org/migrated_tools/toolshed.g2.bx.psu.edu/repos/devteam/ucsc_custom_track/618e56c3109b/ucsc_custom_track/build_ucsc_custom_track.py", line 94
          print "Generated a custom track containing %d subtracks." % num_tracks
                ^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Generated a custom track containing %d subtracks." % num_tracks)?
      .
      ```
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/devteam/ucsc_custom_track/build_ucsc_custom_track_1/1.0.0, exit_code: 1, stderr:   File "/cvmfs/main.galaxyproject.org/migrated_tools/toolshed.g2.bx.psu.edu/repos/devteam/ucsc_custom_track/618e56c3109b/ucsc_custom_track/build_ucsc_custom_track.py", line 94
          print "Generated a custom track containing %d subtracks." % num_tracks
                ^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Generated a custom track containing %d subtracks." % num_tracks)?
      .
      ```
    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      1
      ```
    **Standard Error:**

    * ```console
        File "/cvmfs/main.galaxyproject.org/migrated_tools/toolshed.g2.bx.psu.edu/repos/devteam/ucsc_custom_track/618e56c3109b/ucsc_custom_track/build_ucsc_custom_track.py", line 94
          print "Generated a custom track containing %d subtracks." % num_tracks
                ^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Generated a custom track containing %d subtracks." % num_tracks)?

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | tracks | ` [{"__index__": 0, "color": "0-0-0", "description": "User Supplied Track (from Galaxy)", "input": {"values": [{"id": 93291197, "src": "hda"}]}, "name": "User Track", "visibility": "1"}] ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "bed" ` |



  </div></details>


</details>

**Comment by jennaj** [comment]
Bad print statement 🥇 
Thought these older tools are supposed to be running with Py2 (?)
Or, could update it to use Py3 syntax. Or, in the case of this particular tool -- maybe get rid of it

fails at EU too: https://usegalaxy.eu/u/jenj/h/test-builducsccustomtrack1

**Comment by jennaj** [comment]
Status: 

- [x] Pending install at `org` https://github.com/galaxyproject/usegalaxy-tools/pull/480
* Installed at `eu`
* No version installed at `org.eu` (or tool search doesn't find it)

**Comment by mvdbeek** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/devteam/ucsc_custom_track/build_ucsc_custom_track_1/1.0.1

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 100.0%" aria-valuenow="1" aria-valuemin="0" aria-valuemax="1" data-toggle="tooltip" title="1 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="1" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="1" title="0 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 1 |
| Passed     | 1 |
| Error      | 0 |
| Failure    | 0 |
| Skipped    | 0 |


<details><summary>Passed s</summary>

* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/devteam/ucsc_custom_track/build_ucsc_custom_track_1 (Test #1)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Output:**

    * ```console
      Generated a custom track containing 1 subtracks.

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | tracks | ` [{"__index__": 0, "color": "0-0-0", "description": "User Supplied Track (from Galaxy)", "input": {"values": [{"id": 94249859, "src": "hda"}]}, "name": "User Track", "visibility": "1"}] ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


</details>
