### ISSUE TITLE
Test mothur_align_seqs 1.39.5.0

### ISSUE THREAD

**Issue by jennaj** [mvdbeek/usegalaxy-tests#21]
Report bug test to eliminate technical factors with using the silva reference

Tool ID: toolshed.g2.bx.psu.edu/repos/iuc/mothur_align_seqs/mothur_align_seqs/1.39.5.0

MTS: https://toolshed.g2.bx.psu.edu/repository?repository_id=b8bfc4c6aa897f97

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/iuc/mothur_align_seqs/mothur_align_seqs/1.39.5.0

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 100.0%" aria-valuenow="5" aria-valuemin="0" aria-valuemax="5" data-toggle="tooltip" title="5 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5" title="0 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 5 |
| Passed     | 5 |
| Error      | 0 |
| Failure    | 0 |
| Skipped    | 0 |


<details><summary>Passed s</summary>

* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/mothur_align_seqs/mothur_align_seqs (Test #1)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      TERM environment variable not set.

      ```
    **Standard Output:**

    * ```console
      [H[J





      mothur v.1.39.5
      Last updated: 3/20/2017

      by
      Patrick D. Schloss

      Department of Microbiology & Immunology
      University of Michigan
      http://www.mothur.org

      When using, please cite:
      Schloss, P.D., et al., Introducing mothur: Open-source, platform-independent, community-supported software for describing and comparing microbial communities. Appl Environ Microbiol, 2009. 75(23):7537-41.

      Distributed under the GNU General Public License

      Type 'help()' for information on the commands that are available

      For questions and analysis support, please visit our forum at https://www.mothur.org/forum

      Type 'quit()' to exit program



      mothur > align.seqs(fasta=fasta.dat,reference=alignment.reference.dat,align=need 
      leman,ksize=8,processors=6)

      Using 6 processors.

      Reading in the alignment.reference.dat template sequences...	DONE.
      It took 0 to read  32 sequences.
      Aligning sequences from fasta.dat ...
      3
      4
      3
      4
      4
      4
      It took 0 secs to align 22 sequences.


      Output File Names: 
      fasta.align
      fasta.align.report


      mothur > quit

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | alignment | ` {"__current_case__": 1, "reference": {"values": [{"id": 93418225, "src": "hda"}]}, "source": "history"} ` |
       | search | ` {"__current_case__": 0, "ksize": "8", "method": "kmer"} ` |
       | align | ` "needleman" ` |
       | scoring | ` {"__current_case__": 1, "adjust": "no"} ` |
       | reverse | ` {"__current_case__": 1, "flip": "no"} ` |
       | savelog | ` "true" ` |
       | \_\_job\_resource | ` {"__current_case__": 0, "__job_resource__select": "no"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/mothur_align_seqs/mothur_align_seqs (Test #2)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      TERM environment variable not set.

      ```
    **Standard Output:**

    * ```console
      [H[J





      mothur v.1.39.5
      Last updated: 3/20/2017

      by
      Patrick D. Schloss

      Department of Microbiology & Immunology
      University of Michigan
      http://www.mothur.org

      When using, please cite:
      Schloss, P.D., et al., Introducing mothur: Open-source, platform-independent, community-supported software for describing and comparing microbial communities. Appl Environ Microbiol, 2009. 75(23):7537-41.

      Distributed under the GNU General Public License

      Type 'help()' for information on the commands that are available

      For questions and analysis support, please visit our forum at https://www.mothur.org/forum

      Type 'quit()' to exit program



      mothur > align.seqs(fasta=fasta.dat,reference=alignment.reference.dat,align=need 
      leman,ksize=8,match=2,mismatch=-15,gapopen=-6,gapextend=-3,processors=6)

      Using 6 processors.

      Reading in the alignment.reference.dat template sequences...	DONE.
      It took 0 to read  32 sequences.
      Aligning sequences from fasta.dat ...
      4
      4
      3
      4
      3
      4
      It took 0 secs to align 22 sequences.


      Output File Names: 
      fasta.align
      fasta.align.report


      mothur > quit

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | alignment | ` {"__current_case__": 1, "reference": {"values": [{"id": 93418225, "src": "hda"}]}, "source": "history"} ` |
       | search | ` {"__current_case__": 0, "ksize": "8", "method": "kmer"} ` |
       | align | ` "needleman" ` |
       | scoring | ` {"__current_case__": 0, "adjust": "yes", "gapextend": "-3", "gapopen": "-6", "match": "2", "mismatch": "-15"} ` |
       | reverse | ` {"__current_case__": 1, "flip": "no"} ` |
       | savelog | ` "true" ` |
       | \_\_job\_resource | ` {"__current_case__": 0, "__job_resource__select": "no"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/mothur_align_seqs/mothur_align_seqs (Test #3)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      TERM environment variable not set.

      ```
    **Standard Output:**

    * ```console
      [H[J





      mothur v.1.39.5
      Last updated: 3/20/2017

      by
      Patrick D. Schloss

      Department of Microbiology & Immunology
      University of Michigan
      http://www.mothur.org

      When using, please cite:
      Schloss, P.D., et al., Introducing mothur: Open-source, platform-independent, community-supported software for describing and comparing microbial communities. Appl Environ Microbiol, 2009. 75(23):7537-41.

      Distributed under the GNU General Public License

      Type 'help()' for information on the commands that are available

      For questions and analysis support, please visit our forum at https://www.mothur.org/forum

      Type 'quit()' to exit program



      mothur > align.seqs(fasta=fasta.dat,reference=alignment.reference.dat,align=goto 
      h,search=suffix,match=2,mismatch=-15,gapopen=-6,gapextend=-3,processors=6)

      Using 6 processors.

      Reading in the alignment.reference.dat template sequences...	DONE.
      It took 0 to read  32 sequences.
      Aligning sequences from fasta.dat ...
      4
      3
      4
      3
      4
      4
      It took 0 secs to align 22 sequences.


      Output File Names: 
      fasta.align
      fasta.align.report


      mothur > quit

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | alignment | ` {"__current_case__": 1, "reference": {"values": [{"id": 93418225, "src": "hda"}]}, "source": "history"} ` |
       | search | ` {"__current_case__": 1, "method": "suffix"} ` |
       | align | ` "gotoh" ` |
       | scoring | ` {"__current_case__": 0, "adjust": "yes", "gapextend": "-3", "gapopen": "-6", "match": "2", "mismatch": "-15"} ` |
       | reverse | ` {"__current_case__": 1, "flip": "no"} ` |
       | savelog | ` "true" ` |
       | \_\_job\_resource | ` {"__current_case__": 0, "__job_resource__select": "no"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/mothur_align_seqs/mothur_align_seqs (Test #4)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      TERM environment variable not set.

      ```
    **Standard Output:**

    * ```console
      [H[J





      mothur v.1.39.5
      Last updated: 3/20/2017

      by
      Patrick D. Schloss

      Department of Microbiology & Immunology
      University of Michigan
      http://www.mothur.org

      When using, please cite:
      Schloss, P.D., et al., Introducing mothur: Open-source, platform-independent, community-supported software for describing and comparing microbial communities. Appl Environ Microbiol, 2009. 75(23):7537-41.

      Distributed under the GNU General Public License

      Type 'help()' for information on the commands that are available

      For questions and analysis support, please visit our forum at https://www.mothur.org/forum

      Type 'quit()' to exit program



      mothur > align.seqs(fasta=fasta.dat,reference=alignment.reference.dat,align=blas 
      t,search=blast,flip=true,threshold=0.5,processors=6)

      Using 6 processors.

      Reading in the alignment.reference.dat template sequences...	DONE.
      It took 0 to read  32 sequences.
      Aligning sequences from fasta.dat ...
      3
      3
      4
      4
      4
      4
      It took 1 secs to align 22 sequences.


      Output File Names: 
      fasta.align
      fasta.align.report


      mothur > quit

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | alignment | ` {"__current_case__": 1, "reference": {"values": [{"id": 93418225, "src": "hda"}]}, "source": "history"} ` |
       | search | ` {"__current_case__": 2, "method": "blast"} ` |
       | align | ` "blast" ` |
       | scoring | ` {"__current_case__": 1, "adjust": "no"} ` |
       | reverse | ` {"__current_case__": 0, "flip": "yes", "threshold": "0.5"} ` |
       | savelog | ` "true" ` |
       | \_\_job\_resource | ` {"__current_case__": 0, "__job_resource__select": "no"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/mothur_align_seqs/mothur_align_seqs (Test #5)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      TERM environment variable not set.

      ```
    **Standard Output:**

    * ```console
      [H[J





      mothur v.1.39.5
      Last updated: 3/20/2017

      by
      Patrick D. Schloss

      Department of Microbiology & Immunology
      University of Michigan
      http://www.mothur.org

      When using, please cite:
      Schloss, P.D., et al., Introducing mothur: Open-source, platform-independent, community-supported software for describing and comparing microbial communities. Appl Environ Microbiol, 2009. 75(23):7537-41.

      Distributed under the GNU General Public License

      Type 'help()' for information on the commands that are available

      For questions and analysis support, please visit our forum at https://www.mothur.org/forum

      Type 'quit()' to exit program



      mothur > align.seqs(fasta=fasta.dat,reference=alignment.reference.dat,align=need 
      leman,ksize=8,flip=true,threshold=0.5,processors=6)

      Using 6 processors.

      Reading in the alignment.reference.dat template sequences...	DONE.
      It took 0 to read  32 sequences.
      Aligning sequences from fasta.dat ...
      16
      16
      16
      18
      16
      16
      [WARNING]: Some of your sequences generated alignments that eliminated too many bases, a list is provided in fasta.flip.accnos. If the reverse compliment proved to be better it was reported.
      It took 1 secs to align 98 sequences.


      Output File Names: 
      fasta.align
      fasta.align.report
      fasta.flip.accnos


      mothur > quit


      <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<^>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
      <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<^>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
      <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<^>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
      Detected 1 [WARNING] messages, please review.
      <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<^>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
      <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<^>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
      <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<^>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | alignment | ` {"__current_case__": 1, "reference": {"values": [{"id": 93418225, "src": "hda"}]}, "source": "history"} ` |
       | search | ` {"__current_case__": 0, "ksize": "8", "method": "kmer"} ` |
       | align | ` "needleman" ` |
       | scoring | ` {"__current_case__": 1, "adjust": "no"} ` |
       | reverse | ` {"__current_case__": 0, "flip": "yes", "threshold": "0.5"} ` |
       | savelog | ` "true" ` |
       | \_\_job\_resource | ` {"__current_case__": 0, "__job_resource__select": "no"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


</details>
