### ISSUE TITLE
Test rseqc_bam2wig 2.6.4

### ISSUE THREAD

**Issue by jennaj** [mvdbeek/usegalaxy-tests#23]
Updating an older issue https://github.com/galaxyproject/tools-iuc/issues/3751 -- quick check to make sure no errors so can close it out

tool_id=toolshed.g2.bx.psu.edu/repos/nilesh/rseqc/rseqc_bam2wig/2.6.4

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/nilesh/rseqc/rseqc_bam2wig/2.6.4

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 100.0%" aria-valuenow="4" aria-valuemin="0" aria-valuemax="4" data-toggle="tooltip" title="4 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="4" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="4" title="0 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 4 |
| Passed     | 4 |
| Error      | 0 |
| Failure    | 0 |
| Skipped    | 0 |


<details><summary>Passed s</summary>

* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/nilesh/rseqc/rseqc_bam2wig (Test #1)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      No alignments for chr19_gl000208_random. skipped
      No alignments for chr21_gl000210_random. skipped
      No alignments for chr6_apd_hap1. skipped
      Processing chr13 ...
      Processing chr12 ...
      Processing chr11 ...
      Processing chr10 ...
      Processing chr17 ...
      Processing chr16 ...
      Processing chr15 ...
      Processing chr14 ...
      Processing chr19 ...
      Processing chr18 ...
      No alignments for chr9_gl000198_random. skipped
      No alignments for chrUn_gl000239. skipped
      No alignments for chrUn_gl000238. skipped
      No alignments for chrUn_gl000233. skipped
      No alignments for chrUn_gl000232. skipped
      No alignments for chrUn_gl000231. skipped
      No alignments for chrUn_gl000230. skipped
      No alignments for chrUn_gl000237. skipped
      No alignments for chrUn_gl000236. skipped
      No alignments for chrUn_gl000235. skipped
      No alignments for chrUn_gl000234. skipped
      No alignments for chr6_qbl_hap6. skipped
      No alignments for chr11_gl000202_random. skipped
      No alignments for chr17_gl000206_random. skipped
      No alignments for chr6_cox_hap2. skipped
      No alignments for chr4_gl000193_random. skipped
      No alignments for chrUn_gl000248. skipped
      No alignments for chrUn_gl000249. skipped
      No alignments for chrUn_gl000246. skipped
      No alignments for chrUn_gl000247. skipped
      No alignments for chrUn_gl000244. skipped
      No alignments for chrUn_gl000245. skipped
      No alignments for chrUn_gl000242. skipped
      No alignments for chrUn_gl000243. skipped
      No alignments for chrUn_gl000240. skipped
      No alignments for chrUn_gl000241. skipped
      No alignments for chr17_gl000204_random. skipped
      No alignments for chr17_ctg5_hap1. skipped
      No alignments for chr17_gl000205_random. skipped
      No alignments for chr9_gl000199_random. skipped
      No alignments for chr9_gl000201_random. skipped
      Processing chr8 ...
      No alignments for chr6_ssto_hap7. skipped
      No alignments for chr8_gl000197_random. skipped
      No alignments for chr6_dbb_hap3. skipped
      No alignments for chr7_gl000195_random. skipped
      No alignments for chr1_gl000191_random. skipped
      No alignments for chr4_ctg9_hap1. skipped
      Processing chr3 ...
      No alignments for chrUn_gl000229. skipped
      Processing chr1 ...
      No alignments for chr17_gl000203_random. skipped
      No alignments for chr4_gl000194_random. skipped
      Processing chrY ...
      Processing chrX ...
      No alignments for chr9_gl000200_random. skipped
      Processing chr9 ...
      Processing chrM ...
      No alignments for chr8_gl000196_random. skipped
      No alignments for chr6_mann_hap4. skipped
      No alignments for chrUn_gl000211. skipped
      No alignments for chrUn_gl000213. skipped
      No alignments for chrUn_gl000212. skipped
      No alignments for chrUn_gl000215. skipped
      No alignments for chrUn_gl000214. skipped
      No alignments for chrUn_gl000217. skipped
      No alignments for chrUn_gl000216. skipped
      No alignments for chrUn_gl000219. skipped
      No alignments for chrUn_gl000218. skipped
      No alignments for chr19_gl000209_random. skipped
      Processing chr22 ...
      Processing chr20 ...
      Processing chr21 ...
      No alignments for chr6_mcf_hap5. skipped
      Processing chr7 ...
      Processing chr6 ...
      Processing chr5 ...
      Processing chr4 ...
      No alignments for chrUn_gl000228. skipped
      Processing chr2 ...
      No alignments for chr1_gl000192_random. skipped
      No alignments for chrUn_gl000224. skipped
      No alignments for chrUn_gl000225. skipped
      No alignments for chrUn_gl000226. skipped
      No alignments for chrUn_gl000227. skipped
      No alignments for chrUn_gl000220. skipped
      No alignments for chrUn_gl000221. skipped
      No alignments for chrUn_gl000222. skipped
      No alignments for chrUn_gl000223. skipped
      No alignments for chr18_gl000207_random. skipped
      /bin/sh: wigToBigWig: command not found

      ```
    **Standard Output:**

    * ```console
      Skip multi-hits:False
      Run wigToBigWig outfile.wig /corral4/main/objects/b/0/8/dataset_b08a11f6-7db5-4f5d-a6f0-d127fd4443e6.dat outfile.bw 

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | multihits\_type | ` {"__current_case__": 1, "multihits_type_selector": "use_multihits"} ` |
       | wigsum\_type | ` {"__current_case__": 1, "wigsum_type_selector": "raw"} ` |
       | strand\_type | ` {"__current_case__": 2, "strand_specific": "none"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "auto" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/nilesh/rseqc/rseqc_bam2wig (Test #2)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      No alignments for chr19_gl000208_random. skipped
      No alignments for chr21_gl000210_random. skipped
      No alignments for chr6_apd_hap1. skipped
      Processing chr13 ...
      Processing chr12 ...
      Processing chr11 ...
      Processing chr10 ...
      Processing chr17 ...
      Processing chr16 ...
      Processing chr15 ...
      Processing chr14 ...
      Processing chr19 ...
      Processing chr18 ...
      No alignments for chr9_gl000198_random. skipped
      No alignments for chrUn_gl000239. skipped
      No alignments for chrUn_gl000238. skipped
      No alignments for chrUn_gl000233. skipped
      No alignments for chrUn_gl000232. skipped
      No alignments for chrUn_gl000231. skipped
      No alignments for chrUn_gl000230. skipped
      No alignments for chrUn_gl000237. skipped
      No alignments for chrUn_gl000236. skipped
      No alignments for chrUn_gl000235. skipped
      No alignments for chrUn_gl000234. skipped
      No alignments for chr6_qbl_hap6. skipped
      No alignments for chr11_gl000202_random. skipped
      No alignments for chr17_gl000206_random. skipped
      No alignments for chr6_cox_hap2. skipped
      No alignments for chr4_gl000193_random. skipped
      No alignments for chrUn_gl000248. skipped
      No alignments for chrUn_gl000249. skipped
      No alignments for chrUn_gl000246. skipped
      No alignments for chrUn_gl000247. skipped
      No alignments for chrUn_gl000244. skipped
      No alignments for chrUn_gl000245. skipped
      No alignments for chrUn_gl000242. skipped
      No alignments for chrUn_gl000243. skipped
      No alignments for chrUn_gl000240. skipped
      No alignments for chrUn_gl000241. skipped
      No alignments for chr17_gl000204_random. skipped
      No alignments for chr17_ctg5_hap1. skipped
      No alignments for chr17_gl000205_random. skipped
      No alignments for chr9_gl000199_random. skipped
      No alignments for chr9_gl000201_random. skipped
      Processing chr8 ...
      No alignments for chr6_ssto_hap7. skipped
      No alignments for chr8_gl000197_random. skipped
      No alignments for chr6_dbb_hap3. skipped
      No alignments for chr7_gl000195_random. skipped
      No alignments for chr1_gl000191_random. skipped
      No alignments for chr4_ctg9_hap1. skipped
      Processing chr3 ...
      No alignments for chrUn_gl000229. skipped
      Processing chr1 ...
      No alignments for chr17_gl000203_random. skipped
      No alignments for chr4_gl000194_random. skipped
      Processing chrY ...
      Processing chrX ...
      No alignments for chr9_gl000200_random. skipped
      Processing chr9 ...
      Processing chrM ...
      No alignments for chr8_gl000196_random. skipped
      No alignments for chr6_mann_hap4. skipped
      No alignments for chrUn_gl000211. skipped
      No alignments for chrUn_gl000213. skipped
      No alignments for chrUn_gl000212. skipped
      No alignments for chrUn_gl000215. skipped
      No alignments for chrUn_gl000214. skipped
      No alignments for chrUn_gl000217. skipped
      No alignments for chrUn_gl000216. skipped
      No alignments for chrUn_gl000219. skipped
      No alignments for chrUn_gl000218. skipped
      No alignments for chr19_gl000209_random. skipped
      Processing chr22 ...
      Processing chr20 ...
      Processing chr21 ...
      No alignments for chr6_mcf_hap5. skipped
      Processing chr7 ...
      Processing chr6 ...
      Processing chr5 ...
      Processing chr4 ...
      No alignments for chrUn_gl000228. skipped
      Processing chr2 ...
      No alignments for chr1_gl000192_random. skipped
      No alignments for chrUn_gl000224. skipped
      No alignments for chrUn_gl000225. skipped
      No alignments for chrUn_gl000226. skipped
      No alignments for chrUn_gl000227. skipped
      No alignments for chrUn_gl000220. skipped
      No alignments for chrUn_gl000221. skipped
      No alignments for chrUn_gl000222. skipped
      No alignments for chrUn_gl000223. skipped
      No alignments for chr18_gl000207_random. skipped
      /bin/sh: wigToBigWig: command not found

      ```
    **Standard Output:**

    * ```console
      Skip multi-hits:True
      Run wigToBigWig outfile.wig /corral4/main/objects/b/0/8/dataset_b08a11f6-7db5-4f5d-a6f0-d127fd4443e6.dat outfile.bw 

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | multihits\_type | ` {"__current_case__": 0, "mapq": "20", "multihits_type_selector": "skip_multihits"} ` |
       | wigsum\_type | ` {"__current_case__": 1, "wigsum_type_selector": "raw"} ` |
       | strand\_type | ` {"__current_case__": 2, "strand_specific": "none"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "bam" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/nilesh/rseqc/rseqc_bam2wig (Test #3)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      No alignments for chr19_gl000208_random. skipped
      No alignments for chr21_gl000210_random. skipped
      No alignments for chr6_apd_hap1. skipped
      Processing chr13 ...
      Processing chr12 ...
      Processing chr11 ...
      Processing chr10 ...
      Processing chr17 ...
      Processing chr16 ...
      Processing chr15 ...
      Processing chr14 ...
      Processing chr19 ...
      Processing chr18 ...
      No alignments for chr9_gl000198_random. skipped
      No alignments for chrUn_gl000239. skipped
      No alignments for chrUn_gl000238. skipped
      No alignments for chrUn_gl000233. skipped
      No alignments for chrUn_gl000232. skipped
      No alignments for chrUn_gl000231. skipped
      No alignments for chrUn_gl000230. skipped
      No alignments for chrUn_gl000237. skipped
      No alignments for chrUn_gl000236. skipped
      No alignments for chrUn_gl000235. skipped
      No alignments for chrUn_gl000234. skipped
      No alignments for chr6_qbl_hap6. skipped
      No alignments for chr11_gl000202_random. skipped
      No alignments for chr17_gl000206_random. skipped
      No alignments for chr6_cox_hap2. skipped
      No alignments for chr4_gl000193_random. skipped
      No alignments for chrUn_gl000248. skipped
      No alignments for chrUn_gl000249. skipped
      No alignments for chrUn_gl000246. skipped
      No alignments for chrUn_gl000247. skipped
      No alignments for chrUn_gl000244. skipped
      No alignments for chrUn_gl000245. skipped
      No alignments for chrUn_gl000242. skipped
      No alignments for chrUn_gl000243. skipped
      No alignments for chrUn_gl000240. skipped
      No alignments for chrUn_gl000241. skipped
      No alignments for chr17_gl000204_random. skipped
      No alignments for chr17_ctg5_hap1. skipped
      No alignments for chr17_gl000205_random. skipped
      No alignments for chr9_gl000199_random. skipped
      No alignments for chr9_gl000201_random. skipped
      Processing chr8 ...
      No alignments for chr6_ssto_hap7. skipped
      No alignments for chr8_gl000197_random. skipped
      No alignments for chr6_dbb_hap3. skipped
      No alignments for chr7_gl000195_random. skipped
      No alignments for chr1_gl000191_random. skipped
      No alignments for chr4_ctg9_hap1. skipped
      Processing chr3 ...
      No alignments for chrUn_gl000229. skipped
      Processing chr1 ...
      No alignments for chr17_gl000203_random. skipped
      No alignments for chr4_gl000194_random. skipped
      Processing chrY ...
      Processing chrX ...
      No alignments for chr9_gl000200_random. skipped
      Processing chr9 ...
      Processing chrM ...
      No alignments for chr8_gl000196_random. skipped
      No alignments for chr6_mann_hap4. skipped
      No alignments for chrUn_gl000211. skipped
      No alignments for chrUn_gl000213. skipped
      No alignments for chrUn_gl000212. skipped
      No alignments for chrUn_gl000215. skipped
      No alignments for chrUn_gl000214. skipped
      No alignments for chrUn_gl000217. skipped
      No alignments for chrUn_gl000216. skipped
      No alignments for chrUn_gl000219. skipped
      No alignments for chrUn_gl000218. skipped
      No alignments for chr19_gl000209_random. skipped
      Processing chr22 ...
      Processing chr20 ...
      Processing chr21 ...
      No alignments for chr6_mcf_hap5. skipped
      Processing chr7 ...
      Processing chr6 ...
      Processing chr5 ...
      Processing chr4 ...
      No alignments for chrUn_gl000228. skipped
      Processing chr2 ...
      No alignments for chr1_gl000192_random. skipped
      No alignments for chrUn_gl000224. skipped
      No alignments for chrUn_gl000225. skipped
      No alignments for chrUn_gl000226. skipped
      No alignments for chrUn_gl000227. skipped
      No alignments for chrUn_gl000220. skipped
      No alignments for chrUn_gl000221. skipped
      No alignments for chrUn_gl000222. skipped
      No alignments for chrUn_gl000223. skipped
      No alignments for chr18_gl000207_random. skipped
      /bin/sh: wigToBigWig: command not found
      /bin/sh: wigToBigWig: command not found

      ```
    **Standard Output:**

    * ```console
      Skip multi-hits:False

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | multihits\_type | ` {"__current_case__": 1, "multihits_type_selector": "use_multihits"} ` |
       | wigsum\_type | ` {"__current_case__": 1, "wigsum_type_selector": "raw"} ` |
       | strand\_type | ` {"__current_case__": 0, "pair_type": "sd", "strand_specific": "pair"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "bam" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/nilesh/rseqc/rseqc_bam2wig (Test #4)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      Calcualte wigsum ... 
      No alignments for chr19_gl000208_random. skipped
      No alignments for chr21_gl000210_random. skipped
      No alignments for chr6_apd_hap1. skipped
      Processing chr13 ...
      Processing chr12 ...
      Processing chr11 ...
      Processing chr10 ...
      Processing chr17 ...
      Processing chr16 ...
      Processing chr15 ...
      Processing chr14 ...
      Processing chr19 ...
      Processing chr18 ...
      No alignments for chr9_gl000198_random. skipped
      No alignments for chrUn_gl000239. skipped
      No alignments for chrUn_gl000238. skipped
      No alignments for chrUn_gl000233. skipped
      No alignments for chrUn_gl000232. skipped
      No alignments for chrUn_gl000231. skipped
      No alignments for chrUn_gl000230. skipped
      No alignments for chrUn_gl000237. skipped
      No alignments for chrUn_gl000236. skipped
      No alignments for chrUn_gl000235. skipped
      No alignments for chrUn_gl000234. skipped
      No alignments for chr6_qbl_hap6. skipped
      No alignments for chr11_gl000202_random. skipped
      No alignments for chr17_gl000206_random. skipped
      No alignments for chr6_cox_hap2. skipped
      No alignments for chr4_gl000193_random. skipped
      No alignments for chrUn_gl000248. skipped
      No alignments for chrUn_gl000249. skipped
      No alignments for chrUn_gl000246. skipped
      No alignments for chrUn_gl000247. skipped
      No alignments for chrUn_gl000244. skipped
      No alignments for chrUn_gl000245. skipped
      No alignments for chrUn_gl000242. skipped
      No alignments for chrUn_gl000243. skipped
      No alignments for chrUn_gl000240. skipped
      No alignments for chrUn_gl000241. skipped
      No alignments for chr17_gl000204_random. skipped
      No alignments for chr17_ctg5_hap1. skipped
      No alignments for chr17_gl000205_random. skipped
      No alignments for chr9_gl000199_random. skipped
      No alignments for chr9_gl000201_random. skipped
      Processing chr8 ...
      No alignments for chr6_ssto_hap7. skipped
      No alignments for chr8_gl000197_random. skipped
      No alignments for chr6_dbb_hap3. skipped
      No alignments for chr7_gl000195_random. skipped
      No alignments for chr1_gl000191_random. skipped
      No alignments for chr4_ctg9_hap1. skipped
      Processing chr3 ...
      No alignments for chrUn_gl000229. skipped
      Processing chr1 ...
      No alignments for chr17_gl000203_random. skipped
      No alignments for chr4_gl000194_random. skipped
      Processing chrY ...
      Processing chrX ...
      No alignments for chr9_gl000200_random. skipped
      Processing chr9 ...
      Processing chrM ...
      No alignments for chr8_gl000196_random. skipped
      No alignments for chr6_mann_hap4. skipped
      No alignments for chrUn_gl000211. skipped
      No alignments for chrUn_gl000213. skipped
      No alignments for chrUn_gl000212. skipped
      No alignments for chrUn_gl000215. skipped
      No alignments for chrUn_gl000214. skipped
      No alignments for chrUn_gl000217. skipped
      No alignments for chrUn_gl000216. skipped
      No alignments for chrUn_gl000219. skipped
      No alignments for chrUn_gl000218. skipped
      No alignments for chr19_gl000209_random. skipped
      Processing chr22 ...
      Processing chr20 ...
      Processing chr21 ...
      No alignments for chr6_mcf_hap5. skipped
      Processing chr7 ...
      Processing chr6 ...
      Processing chr5 ...
      Processing chr4 ...
      No alignments for chrUn_gl000228. skipped
      Processing chr2 ...
      No alignments for chr1_gl000192_random. skipped
      No alignments for chrUn_gl000224. skipped
      No alignments for chrUn_gl000225. skipped
      No alignments for chrUn_gl000226. skipped
      No alignments for chrUn_gl000227. skipped
      No alignments for chrUn_gl000220. skipped
      No alignments for chrUn_gl000221. skipped
      No alignments for chrUn_gl000222. skipped
      No alignments for chrUn_gl000223. skipped
      No alignments for chr18_gl000207_random. skipped


      total wigsum is:1960.0

      No alignments for chr19_gl000208_random. skipped
      No alignments for chr21_gl000210_random. skipped
      No alignments for chr6_apd_hap1. skipped
      Processing chr13 ...
      Processing chr12 ...
      Processing chr11 ...
      Processing chr10 ...
      Processing chr17 ...
      Processing chr16 ...
      Processing chr15 ...
      Processing chr14 ...
      Processing chr19 ...
      Processing chr18 ...
      No alignments for chr9_gl000198_random. skipped
      No alignments for chrUn_gl000239. skipped
      No alignments for chrUn_gl000238. skipped
      No alignments for chrUn_gl000233. skipped
      No alignments for chrUn_gl000232. skipped
      No alignments for chrUn_gl000231. skipped
      No alignments for chrUn_gl000230. skipped
      No alignments for chrUn_gl000237. skipped
      No alignments for chrUn_gl000236. skipped
      No alignments for chrUn_gl000235. skipped
      No alignments for chrUn_gl000234. skipped
      No alignments for chr6_qbl_hap6. skipped
      No alignments for chr11_gl000202_random. skipped
      No alignments for chr17_gl000206_random. skipped
      No alignments for chr6_cox_hap2. skipped
      No alignments for chr4_gl000193_random. skipped
      No alignments for chrUn_gl000248. skipped
      No alignments for chrUn_gl000249. skipped
      No alignments for chrUn_gl000246. skipped
      No alignments for chrUn_gl000247. skipped
      No alignments for chrUn_gl000244. skipped
      No alignments for chrUn_gl000245. skipped
      No alignments for chrUn_gl000242. skipped
      No alignments for chrUn_gl000243. skipped
      No alignments for chrUn_gl000240. skipped
      No alignments for chrUn_gl000241. skipped
      No alignments for chr17_gl000204_random. skipped
      No alignments for chr17_ctg5_hap1. skipped
      No alignments for chr17_gl000205_random. skipped
      No alignments for chr9_gl000199_random. skipped
      No alignments for chr9_gl000201_random. skipped
      Processing chr8 ...
      No alignments for chr6_ssto_hap7. skipped
      No alignments for chr8_gl000197_random. skipped
      No alignments for chr6_dbb_hap3. skipped
      No alignments for chr7_gl000195_random. skipped
      No alignments for chr1_gl000191_random. skipped
      No alignments for chr4_ctg9_hap1. skipped
      Processing chr3 ...
      No alignments for chrUn_gl000229. skipped
      Processing chr1 ...
      No alignments for chr17_gl000203_random. skipped
      No alignments for chr4_gl000194_random. skipped
      Processing chrY ...
      Processing chrX ...
      No alignments for chr9_gl000200_random. skipped
      Processing chr9 ...
      Processing chrM ...
      No alignments for chr8_gl000196_random. skipped
      No alignments for chr6_mann_hap4. skipped
      No alignments for chrUn_gl000211. skipped
      No alignments for chrUn_gl000213. skipped
      No alignments for chrUn_gl000212. skipped
      No alignments for chrUn_gl000215. skipped
      No alignments for chrUn_gl000214. skipped
      No alignments for chrUn_gl000217. skipped
      No alignments for chrUn_gl000216. skipped
      No alignments for chrUn_gl000219. skipped
      No alignments for chrUn_gl000218. skipped
      No alignments for chr19_gl000209_random. skipped
      Processing chr22 ...
      Processing chr20 ...
      Processing chr21 ...
      No alignments for chr6_mcf_hap5. skipped
      Processing chr7 ...
      Processing chr6 ...
      Processing chr5 ...
      Processing chr4 ...
      No alignments for chrUn_gl000228. skipped
      Processing chr2 ...
      No alignments for chr1_gl000192_random. skipped
      No alignments for chrUn_gl000224. skipped
      No alignments for chrUn_gl000225. skipped
      No alignments for chrUn_gl000226. skipped
      No alignments for chrUn_gl000227. skipped
      No alignments for chrUn_gl000220. skipped
      No alignments for chrUn_gl000221. skipped
      No alignments for chrUn_gl000222. skipped
      No alignments for chrUn_gl000223. skipped
      No alignments for chr18_gl000207_random. skipped
      /bin/sh: wigToBigWig: command not found

      ```
    **Standard Output:**

    * ```console
      Skip multi-hits:False
      Run wigToBigWig outfile.wig /corral4/main/objects/b/0/8/dataset_b08a11f6-7db5-4f5d-a6f0-d127fd4443e6.dat outfile.bw 

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | multihits\_type | ` {"__current_case__": 1, "multihits_type_selector": "use_multihits"} ` |
       | wigsum\_type | ` {"__current_case__": 0, "totalwig": "100", "wigsum_type_selector": "normalize"} ` |
       | strand\_type | ` {"__current_case__": 2, "strand_specific": "none"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "auto" ` |



  </div></details>


</details>
