### ISSUE TITLE
Test gops_coverage_1 1.0.0

### ISSUE THREAD

**Issue by jennaj** [mvdbeek/usegalaxy-tests#24]
All GOPS tools except for "Join" are failing with a metadata error at `org`. With both bed and interval input/outputs.

toolshed.g2.bx.psu.edu/repos/devteam/coverage/gops_coverage_1/1.0.0

Ref: https://help.galaxyproject.org/t/error-galaxy-set-metadata-command-not-found/7551

Test history: https://usegalaxy.org/u/jen/h/test-gops

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/devteam/coverage/gops_coverage_1/1.0.0

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 100.0%" aria-valuenow="3" aria-valuemin="0" aria-valuemax="3" data-toggle="tooltip" title="3 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="3" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="3" title="0 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 3 |
| Passed     | 3 |
| Error      | 0 |
| Failure    | 0 |
| Skipped    | 0 |


<details><summary>Passed s</summary>

* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/devteam/coverage/gops_coverage_1 (Test #1)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      
      /corral4/main/jobs/041/228/41228210/galaxy_41228210.sh: line 123: galaxy-set-metadata: command not found

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "bed" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/devteam/coverage/gops_coverage_1 (Test #2)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      
      /corral4/main/jobs/041/228/41228196/galaxy_41228196.sh: line 123: galaxy-set-metadata: command not found

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "bed" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/devteam/coverage/gops_coverage_1 (Test #3)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      
      /corral4/main/jobs/041/228/41228201/galaxy_41228201.sh: line 123: galaxy-set-metadata: command not found

      ```
    **Standard Output:**

    * ```console
      Skipped 1 invalid lines of 1st dataset, 1st line #9: "chrM	4294967295	4294967322	EAS38_1_45_638_677	2	+
      ", problem: 4294967295 is larger than the size of this BitSet (536870912).

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "bed" ` |



  </div></details>


</details>

**Comment by jennaj** [comment]
Technically "successful" with that same metadata error. Same as in the test history and reports from user's examined.

We should fix this before the Smorg if possible 

confirmed by @mvdbeek -- needs "set-metadata script reinstalled"

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/devteam/coverage/gops_coverage_1/1.0.0

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 66.66666666666666%" aria-valuenow="2" aria-valuemin="0" aria-valuemax="3" data-toggle="tooltip" title="2 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="3" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 33.33333333333333%" aria-valuenow="1" aria-valuemin="0" aria-valuemax="3" title="1 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 3 |
| Passed     | 2 |
| Error      | 1 |
| Failure    | 0 |
| Skipped    | 0 |


<details><summary>Errored s</summary>

* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/devteam/coverage/gops_coverage_1 (Test #2)</summary><div class="padded">

    **Execution Problem:**
    * ```
      The attributes of this dataset are not properly set. Click the pencil icon in the history item to set the chrom, start, end and strand columns.
      ```

  </div></details>


</details>
<details><summary>Passed s</summary>

* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/devteam/coverage/gops_coverage_1 (Test #1)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "bed" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/devteam/coverage/gops_coverage_1 (Test #3)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Output:**

    * ```console
      Skipped 1 invalid lines of 1st dataset, 1st line #9: "chrM	4294967295	4294967322	EAS38_1_45_638_677	2	+
      ", problem: 4294967295 is larger than the size of this BitSet (536870912).

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "bed" ` |



  </div></details>


</details>

**Comment by jennaj** [comment]
Hum, this doesn't show up at org. Just a green dataset, no warnings. 

> The attributes of this dataset are not properly set. Click the pencil icon in the history item to set the chrom, start, end and strand columns.

Under attributes, score is set for c4 instead of c5. I don't think that is new for this output -- it is making an interval dataset that we label as bed. c4 is a number instead of a dot or word (doesn't fit strict bed). Think that is Ok.
