### ISSUE TITLE
Test spades 3.12.0+galaxy1 and 3.15.3+galaxy2

### ISSUE THREAD

**Issue by jennaj** [mvdbeek/usegalaxy-tests#25]
Reported issue with the tool. Not obvious what is going wrong.

toolshed.g2.bx.psu.edu/repos/nml/spades/spades/3.12.0+galaxy1

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/nml/spades/spades/3.12.0+galaxy1

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/nml/spades/spades/3.12.0+galaxy1

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="8" data-toggle="tooltip" title="0 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="8" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 100.0%" aria-valuenow="8" aria-valuemin="0" aria-valuemax="8" title="8 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 8 |
| Passed     | 0 |
| Error      | 8 |
| Failure    | 0 |
| Skipped    | 0 |


<details><summary>Errored s</summary>

* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/nml/spades/spades (Test #1)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Test input file (ecoli_1K_1.fq) cannot be found.
      ```

  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/nml/spades/spades (Test #2)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Test input file (ecoli_1K_1.fasta) cannot be found.
      ```

  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/nml/spades/spades (Test #3)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Test input file (ecoli_1K_1.fq.gz) cannot be found.
      ```

  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/nml/spades/spades (Test #4)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Test input file (ecoli_1K_1.fq) cannot be found.
      ```

  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/nml/spades/spades (Test #5)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Test input file (ecoli_1K_1.fq) cannot be found.
      ```

  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/nml/spades/spades (Test #6)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Test input file (ecoli_1K_1.fq) cannot be found.
      ```

  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/nml/spades/spades (Test #7)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Test input file (ecoli_1K_1.fq) cannot be found.
      ```

  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/nml/spades/spades (Test #8)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Test input file (ecoli_1K_1.fq.gz) cannot be found.
      ```

  </div></details>


</details>

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/nml/spades/spades/3.12.0+galaxy1

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="8" data-toggle="tooltip" title="0 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="8" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 100.0%" aria-valuenow="8" aria-valuemin="0" aria-valuemax="8" title="8 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 8 |
| Passed     | 0 |
| Error      | 8 |
| Failure    | 0 |
| Skipped    | 0 |


<details><summary>Errored s</summary>

* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/nml/spades/spades (Test #1)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Test input file (ecoli_1K_1.fq) cannot be found.
      ```

  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/nml/spades/spades (Test #2)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Test input file (ecoli_1K_1.fasta) cannot be found.
      ```

  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/nml/spades/spades (Test #3)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Test input file (ecoli_1K_1.fq.gz) cannot be found.
      ```

  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/nml/spades/spades (Test #4)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Test input file (ecoli_1K_1.fq) cannot be found.
      ```

  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/nml/spades/spades (Test #5)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Test input file (ecoli_1K_1.fq) cannot be found.
      ```

  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/nml/spades/spades (Test #6)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Test input file (ecoli_1K_1.fq) cannot be found.
      ```

  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/nml/spades/spades (Test #7)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Test input file (ecoli_1K_1.fq) cannot be found.
      ```

  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/nml/spades/spades (Test #8)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Test input file (ecoli_1K_1.fq.gz) cannot be found.
      ```

  </div></details>


</details>

**Comment by jennaj** [comment]
toolshed.g2.bx.psu.edu/repos/nml/spades/spades/3.15.3+galaxy2

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/nml/spades/spades/3.15.3+galaxy2

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/nml/spades/spades/3.15.3+galaxy2
