### ISSUE TITLE
Test circos 0.69.8+galaxy7

### ISSUE THREAD

**Issue by jennaj** [mvdbeek/usegalaxy-tests#26]
This tool is pending an update at `org` https://github.com/galaxyproject/usegalaxy-playbook/issues/346

`org` is at 0.69.8+galaxy7 (known issues, but don't impact GTN tutorials, curious how tests turn out)
`.eu` is still at 0.69.8+galaxy9
`mts` is at 0.69.8+galaxy10

tool_id=toolshed.g2.bx.psu.edu/repos/iuc/circos/circos/0.69.8+galaxy7

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/iuc/circos/circos/0.69.8+galaxy7

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="2" data-toggle="tooltip" title="0 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="2" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 100.0%" aria-valuenow="2" aria-valuemin="0" aria-valuemax="2" title="2 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 2 |
| Passed     | 0 |
| Error      | 0 |
| Failure    | 2 |
| Skipped    | 0 |


<details><summary>Failed s</summary>

* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/iuc/circos/circos (Test #1)</summary><div class="padded">

    **Problems**:
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/circos/circos/0.69.8+galaxy7, exit_code: 21, stderr: Use of uninitialized value in subroutine entry at /cvmfs/main.galaxyproject.org/deps/_conda/envs/mulled-v1-3cf5c7d734898be0f8d76d0fbf3face5f99ca4b3a9b294235f9271dd27115368/bin/../lib/Circos/Configuration.pm line 781.
      Can't call method "colorExact" on an undefined value at /cvmfs/main.galaxyproject.org/deps/_conda/envs/mulled-v1-3cf5c7d734898be0f8d76d0fbf3face5f99ca4b3a9b294235f9271dd27115368/bin/../lib/Circos/Colors.pm line 348, <F> line 2.
      .
      ```
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/circos/circos/0.69.8+galaxy7, exit_code: 21, stderr: Use of uninitialized value in subroutine entry at /cvmfs/main.galaxyproject.org/deps/_conda/envs/mulled-v1-3cf5c7d734898be0f8d76d0fbf3face5f99ca4b3a9b294235f9271dd27115368/bin/../lib/Circos/Configuration.pm line 781.
      Can't call method "colorExact" on an undefined value at /cvmfs/main.galaxyproject.org/deps/_conda/envs/mulled-v1-3cf5c7d734898be0f8d76d0fbf3face5f99ca4b3a9b294235f9271dd27115368/bin/../lib/Circos/Colors.pm line 348, <F> line 2.
      .
      ```
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/circos/circos/0.69.8+galaxy7, exit_code: 21, stderr: Use of uninitialized value in subroutine entry at /cvmfs/main.galaxyproject.org/deps/_conda/envs/mulled-v1-3cf5c7d734898be0f8d76d0fbf3face5f99ca4b3a9b294235f9271dd27115368/bin/../lib/Circos/Configuration.pm line 781.
      Can't call method "colorExact" on an undefined value at /cvmfs/main.galaxyproject.org/deps/_conda/envs/mulled-v1-3cf5c7d734898be0f8d76d0fbf3face5f99ca4b3a9b294235f9271dd27115368/bin/../lib/Circos/Colors.pm line 348, <F> line 2.
      .
      ```
    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      21
      ```
    **Standard Error:**

    * ```console
      Use of uninitialized value in subroutine entry at /cvmfs/main.galaxyproject.org/deps/_conda/envs/mulled-v1-3cf5c7d734898be0f8d76d0fbf3face5f99ca4b3a9b294235f9271dd27115368/bin/../lib/Circos/Configuration.pm line 781.
      Can't call method "colorExact" on an undefined value at /cvmfs/main.galaxyproject.org/deps/_conda/envs/mulled-v1-3cf5c7d734898be0f8d76d0fbf3face5f99ca4b3a9b294235f9271dd27115368/bin/../lib/Circos/Colors.pm line 348, <F> line 2.

      ```
    **Standard Output:**

    * ```console
      debuggroup summary 0.26s welcome to circos v0.69-8 15 Jun 2019 on Perl 5.026002
      debuggroup summary 0.26s current working directory /corral4/main/jobs/041/306/41306838/working
      debuggroup summary 0.26s command /cvmfs/main.galaxyproject.org/deps/_conda/envs/mulled-v1-3cf5c7d734898be0f8d76d0fbf3face5f99ca4b3a9b294235f9271dd27115368/bin/circos -conf circos/conf/circos.conf -noparanoid
      debuggroup summary 0.26s loading configuration from file circos/conf/circos.conf
      debuggroup summary 0.26s found conf file circos/conf/circos.conf
      debuggroup summary 2.39s debug will appear for these features: output,summary
      debuggroup summary 2.40s bitmap output image ./circos.png
      debuggroup summary 2.40s SVG output image ./circos.svg
      debuggroup summary 2.40s parsing karyotype and organizing ideograms
      debuggroup summary 2.41s karyotype has 2 chromosomes of total size 56,082
      debuggroup summary 2.41s applying global and local scaling
      debuggroup summary 2.41s allocating image, colors and brushes

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | reference\_genome | ` {"ref": {"__current_case__": 2, "genome_fasta": {"values": [{"id": 94315153, "src": "hda"}]}, "ref_source": "history"}} ` |
       | ideogram | ` {"angle_offset": "-90", "angle_orientation": "clockwise", "bands": {"band_stroke_color": "#000000", "band_stroke_thickness": "0", "band_transparency": "3", "fill_bands": "true", "show_bands": "true"}, "chromosomes_reverse": null, "ideogram_labels": {"parallel": "true", "radius_offset": "0.075", "show_label": "true", "size": "24"}, "limit_chromosomes": null, "pairwise_spacing": [], "radius": "0.9", "spacing": "0.5", "thickness": "30.0", "units": "mb"} ` |
       | plot\_options | ` {"background": {"__current_case__": 1, "background_color": "#ffffff", "background_select": "color"}, "colour_profile": null, "radius": "1500"} ` |
       | sec\_tdd | ` {"data": []} ` |
       | sec\_links | ` {"data": []} ` |
       | scaling | ` {"zooms": []} ` |
       | ticks | ` {"radius": "1.0", "skip_first_label": "false", "skip_last_label": "false", "tick_group": []} ` |
       | limits | ` {"max_ideograms": "200", "max_links": "25000", "max_points_per_track": "25000", "max_ticks": "5000"} ` |
       | outputs | ` {"png": "true", "svg": "true", "tar": "false"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "auto" ` |



  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/iuc/circos/circos (Test #2)</summary><div class="padded">

    **Problems**:
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/circos/circos/0.69.8+galaxy7, exit_code: 21, stderr: Use of uninitialized value in subroutine entry at /cvmfs/main.galaxyproject.org/deps/_conda/envs/mulled-v1-3cf5c7d734898be0f8d76d0fbf3face5f99ca4b3a9b294235f9271dd27115368/bin/../lib/Circos/Configuration.pm line 781.
      Can't call method "colorExact" on an undefined value at /cvmfs/main.galaxyproject.org/deps/_conda/envs/mulled-v1-3cf5c7d734898be0f8d76d0fbf3face5f99ca4b3a9b294235f9271dd27115368/bin/../lib/Circos/Colors.pm line 348, <F> line 2.
      .
      ```
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/circos/circos/0.69.8+galaxy7, exit_code: 21, stderr: Use of uninitialized value in subroutine entry at /cvmfs/main.galaxyproject.org/deps/_conda/envs/mulled-v1-3cf5c7d734898be0f8d76d0fbf3face5f99ca4b3a9b294235f9271dd27115368/bin/../lib/Circos/Configuration.pm line 781.
      Can't call method "colorExact" on an undefined value at /cvmfs/main.galaxyproject.org/deps/_conda/envs/mulled-v1-3cf5c7d734898be0f8d76d0fbf3face5f99ca4b3a9b294235f9271dd27115368/bin/../lib/Circos/Colors.pm line 348, <F> line 2.
      .
      ```
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/circos/circos/0.69.8+galaxy7, exit_code: 21, stderr: Use of uninitialized value in subroutine entry at /cvmfs/main.galaxyproject.org/deps/_conda/envs/mulled-v1-3cf5c7d734898be0f8d76d0fbf3face5f99ca4b3a9b294235f9271dd27115368/bin/../lib/Circos/Configuration.pm line 781.
      Can't call method "colorExact" on an undefined value at /cvmfs/main.galaxyproject.org/deps/_conda/envs/mulled-v1-3cf5c7d734898be0f8d76d0fbf3face5f99ca4b3a9b294235f9271dd27115368/bin/../lib/Circos/Colors.pm line 348, <F> line 2.
      .
      ```
    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      21
      ```
    **Standard Error:**

    * ```console
      Use of uninitialized value in subroutine entry at /cvmfs/main.galaxyproject.org/deps/_conda/envs/mulled-v1-3cf5c7d734898be0f8d76d0fbf3face5f99ca4b3a9b294235f9271dd27115368/bin/../lib/Circos/Configuration.pm line 781.
      Can't call method "colorExact" on an undefined value at /cvmfs/main.galaxyproject.org/deps/_conda/envs/mulled-v1-3cf5c7d734898be0f8d76d0fbf3face5f99ca4b3a9b294235f9271dd27115368/bin/../lib/Circos/Colors.pm line 348, <F> line 2.

      ```
    **Standard Output:**

    * ```console
      debuggroup summary 0.21s welcome to circos v0.69-8 15 Jun 2019 on Perl 5.026002
      debuggroup summary 0.22s current working directory /corral4/main/jobs/041/306/41306844/working
      debuggroup summary 0.22s command /cvmfs/main.galaxyproject.org/deps/_conda/envs/mulled-v1-3cf5c7d734898be0f8d76d0fbf3face5f99ca4b3a9b294235f9271dd27115368/bin/circos -conf circos/conf/circos.conf -noparanoid
      debuggroup summary 0.22s loading configuration from file circos/conf/circos.conf
      debuggroup summary 0.22s found conf file circos/conf/circos.conf
      debuggroup summary 0.63s debug will appear for these features: output,summary
      debuggroup summary 0.63s bitmap output image ./circos.png
      debuggroup summary 0.63s SVG output image ./circos.svg
      debuggroup summary 0.64s parsing karyotype and organizing ideograms
      debuggroup summary 0.65s karyotype has 2 chromosomes of total size 56,082
      debuggroup summary 0.65s applying global and local scaling
      debuggroup summary 0.65s allocating image, colors and brushes

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | reference\_genome | ` {"ref": {"__current_case__": 2, "genome_fasta": {"values": [{"id": 94315153, "src": "hda"}]}, "ref_source": "history"}} ` |
       | ideogram | ` {"angle_offset": "-90", "angle_orientation": "clockwise", "bands": {"band_stroke_color": "#000000", "band_stroke_thickness": "0", "band_transparency": "3", "fill_bands": "true", "show_bands": "true"}, "chromosomes_reverse": null, "ideogram_labels": {"parallel": "true", "radius_offset": "0.075", "show_label": "true", "size": "24"}, "limit_chromosomes": null, "pairwise_spacing": [], "radius": "0.9", "spacing": "0.5", "thickness": "30.0", "units": "kb"} ` |
       | plot\_options | ` {"background": {"__current_case__": 1, "background_color": "#ffffff", "background_select": "color"}, "colour_profile": null, "radius": "1500"} ` |
       | sec\_tdd | ` {"data": [{"__index__": 0, "minmax": {"__current_case__": 1, "minmax_select": "no"}, "minsize": "0.0", "orientation": "false", "plot_format": {"__current_case__": 0, "data_source": {"values": [{"id": 94315166, "src": "hda"}]}, "format_specific": {"extend_bins": "false", "fill_color": "#ffdcfc", "fill_color_alpha": "1.0", "fill_under": "true", "stroke_color": "#000000", "stroke_color_alpha": "1.0", "stroke_thickness": "1"}, "plot_format_select": "histogram"}, "r0": "0.8", "r1": "0.9", "sec_axes": {"axes": [], "only_if_data": "always"}, "sec_bkgs": {"backgrounds": [], "only_if_data": "always"}, "sec_rule": {"rules": []}, "zdepth": "0"}, {"__index__": 1, "minmax": {"__current_case__": 1, "minmax_select": "no"}, "minsize": "0.0", "orientation": "false", "plot_format": {"__current_case__": 5, "data_source": {"values": [{"id": 94315166, "src": "hda"}]}, "format_specific": {"fill_color": "#555555", "fill_color_alpha": "1.0", "glyph": "circle", "glyph_size": "8", "stroke_color": "#000000", "stroke_color_alpha": "1.0", "stroke_thickness": "1"}, "plot_format_select": "scatter"}, "r0": "0.7", "r1": "0.8", "sec_axes": {"axes": [], "only_if_data": "always"}, "sec_bkgs": {"backgrounds": [], "only_if_data": "always"}, "sec_rule": {"rules": []}, "zdepth": "0"}, {"__index__": 2, "minmax": {"__current_case__": 1, "minmax_select": "no"}, "minsize": "0.0", "orientation": "false", "plot_format": {"__current_case__": 6, "data_source": {"values": [{"id": 94315168, "src": "hda"}]}, "format_specific": {"fill_color": "#000000", "fill_color_alpha": "1.0", "layers": "15", "margin": "0.002", "overflow": {"__current_case__": 0, "overflow_behavior": "hide"}, "padding": "8.0", "stroke_color": "#000000", "stroke_color_alpha": "1.0", "stroke_thickness": "1", "thickness": "15.0"}, "plot_format_select": "tile"}, "r0": "0.6", "r1": "0.7", "sec_axes": {"axes": [], "only_if_data": "always"}, "sec_bkgs": {"backgrounds": [], "only_if_data": "always"}, "sec_rule": {"rules": []}, "zdepth": "0"}]} ` |
       | sec\_links | ` {"data": [{"__index__": 0, "advanced": {"bezier_radius_purity": "0.75", "crest": "0.5", "perturbation": {"__current_case__": 1, "perturb": "no"}}, "bezier_radius": "0.1", "color": "#000000", "color_alpha": "1.0", "data_source": {"values": [{"id": 94315169, "src": "hda"}]}, "linktype": {"__current_case__": 0, "pattern": "solid", "ribbon": "yes", "twist": ""}, "minsize": "0.0", "radius": "0.59", "sec_link_rule": {"rules": []}, "thickness": "15.0", "zdepth": "0"}]} ` |
       | scaling | ` {"zooms": []} ` |
       | ticks | ` {"radius": "1.0", "skip_first_label": "false", "skip_last_label": "false", "tick_group": [{"__index__": 0, "color": "#000000", "size": "10.0", "spacing": "1.0", "ticks": {"__current_case__": 1, "show_tick_labels": "no"}}, {"__index__": 1, "color": "#000000", "size": "10.0", "spacing": "5.0", "ticks": {"__current_case__": 0, "format": "%.1f", "format_ext": "true", "label_offset": "10.0", "label_size": "20.0", "show_tick_labels": "yes"}}]} ` |
       | limits | ` {"max_ideograms": "200", "max_links": "25000", "max_points_per_track": "25000", "max_ticks": "5000"} ` |
       | outputs | ` {"png": "true", "svg": "true", "tar": "false"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "fasta" ` |



  </div></details>


</details>

**Comment by jennaj** [comment]
That the known karyotype issue. We should update, I'll ping in lab

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/iuc/circos/circos/0.69.8+galaxy10

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 33.33333333333333%" aria-valuenow="1" aria-valuemin="0" aria-valuemax="3" data-toggle="tooltip" title="1 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="3" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 66.66666666666666%" aria-valuenow="2" aria-valuemin="0" aria-valuemax="3" title="2 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 3 |
| Passed     | 1 |
| Error      | 2 |
| Failure    | 0 |
| Skipped    | 0 |


<details><summary>Errored s</summary>

* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/iuc/circos/circos (Test #2)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Value ('1') must fulfill float('200') <= value <= float('inf'), Value ('1') must fulfill float('200') <= value <= float('inf'), Value ('1') must fulfill float('200') <= value <= float('inf'), Value ('1') must fulfill float('200') <= value <= float('inf')
      ```

  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/iuc/circos/circos (Test #3)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Job in error state.. tool_id: upload1, exit_code: None, stderr: .
      ```

  </div></details>


</details>
<details><summary>Passed s</summary>

* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/circos/circos (Test #1)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.

      ```
    **Standard Output:**

    * ```console
      debuggroup summary 0.24s welcome to circos v0.69-8 15 Jun 2019 on Perl 5.026002
      debuggroup summary 0.24s current working directory /corral4/main/jobs/041/396/41396294/working
      debuggroup summary 0.24s command /usr/local/bin/circos -conf circos/conf/circos.conf -noparanoid
      debuggroup summary 0.24s loading configuration from file circos/conf/circos.conf
      debuggroup summary 0.24s found conf file circos/conf/circos.conf
      debuggroup summary 0.47s debug will appear for these features: output,summary
      debuggroup summary 0.47s bitmap output image ./circos.png
      debuggroup summary 0.47s SVG output image ./circos.svg
      debuggroup summary 0.48s parsing karyotype and organizing ideograms
      debuggroup summary 0.51s karyotype has 2 chromosomes of total size 56,082
      debuggroup summary 0.51s applying global and local scaling
      debuggroup summary 0.51s allocating image, colors and brushes
      debuggroup summary 9.89s drawing 2 ideograms of total size 56,082
      debuggroup summary 9.89s drawing highlights and ideograms
      debuggroup output 9.90s generating output
      debuggroup output 10.38s created PNG image ./circos.png (40 kb)
      debuggroup output 10.38s created SVG image ./circos.svg (2 kb)

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | reference\_genome | ` {"ref": {"__current_case__": 2, "genome_fasta": {"values": [{"id": 94474101, "src": "hda"}]}, "ref_source": "history"}} ` |
       | ideogram | ` {"angle_offset": "-90", "angle_orientation": "clockwise", "bands": {"band_stroke_color": "#000000", "band_stroke_thickness": "0", "band_transparency": "3", "fill_bands": "true", "show_bands": "true"}, "chromosomes_reverse": null, "ideogram_labels": {"parallel": "true", "radius_offset": "0.075", "show_label": "true", "size": "24"}, "limit_chromosomes": null, "pairwise_spacing": [], "radius": "0.9", "spacing": "0.5", "thickness": "30.0", "units": "mb"} ` |
       | plot\_options | ` {"background": {"__current_case__": 1, "background_color": "#ffffff", "background_select": "color"}, "colour_profile": null, "radius": "1500"} ` |
       | sec\_tdd | ` {"data": []} ` |
       | sec\_links | ` {"data": []} ` |
       | scaling | ` {"zooms": []} ` |
       | ticks | ` {"radius": "1.0", "skip_first_label": "false", "skip_last_label": "false", "tick_group": []} ` |
       | limits | ` {"max_ideograms": "200", "max_links": "25000", "max_points_per_track": "25000", "max_ticks": "5000"} ` |
       | outputs | ` {"png": "true", "svg": "true", "tar": "false"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "auto" ` |



  </div></details>


</details>
