### ISSUE TITLE
Test macs2_callpeak 2.1.1.20160309.6

### ISSUE THREAD

**Issue by jennaj** [mvdbeek/usegalaxy-tests#27]
Double checking the tool function

toolshed.g2.bx.psu.edu/repos/iuc/macs2/macs2_callpeak/2.1.1.20160309.6

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/iuc/macs2/macs2_callpeak/2.1.1.20160309.6

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 100.0%" aria-valuenow="3" aria-valuemin="0" aria-valuemax="3" data-toggle="tooltip" title="3 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="3" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="3" title="0 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 3 |
| Passed     | 3 |
| Error      | 0 |
| Failure    | 0 |
| Skipped    | 0 |


<details><summary>Passed s</summary>

* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/macs2/macs2_callpeak (Test #1)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Output:**

    * ```console
      INFO  @ Fri, 11 Mar 2022 21:47:06: 
      # Command line: callpeak -t /corral4/main/objects/b/8/0/dataset_b804fa8b-042e-4072-8656-c78f41dcd477.dat --name ChIP_200K_bed -c /corral4/main/objects/3/1/2/dataset_3120fd52-6093-49fc-b21e-519f3c34f50c.dat --format BED --gsize 3300000000 --keep-dup 1 --bdg --qvalue 0.05 --mfold 5 50 --bw 300
      # ARGUMENTS LIST:
      # name = ChIP_200K_bed
      # format = BED
      # ChIP-seq file = ['/corral4/main/objects/b/8/0/dataset_b804fa8b-042e-4072-8656-c78f41dcd477.dat']
      # control file = ['/corral4/main/objects/3/1/2/dataset_3120fd52-6093-49fc-b21e-519f3c34f50c.dat']
      # effective genome size = 3.30e+09
      # band width = 300
      # model fold = [5, 50]
      # qvalue cutoff = 5.00e-02
      # Larger dataset will be scaled towards smaller dataset.
      # Range for calculating regional lambda is: 1000 bps and 10000 bps
      # Broad region calling is off
      # Paired-End mode is off
       
      INFO  @ Fri, 11 Mar 2022 21:47:06: #1 read tag files... 
      INFO  @ Fri, 11 Mar 2022 21:47:06: #1 read treatment tags... 
      INFO  @ Fri, 11 Mar 2022 21:47:07: #1.2 read input tags... 
      INFO  @ Fri, 11 Mar 2022 21:47:08: #1 tag size is determined as 100 bps 
      INFO  @ Fri, 11 Mar 2022 21:47:08: #1 tag size = 100 
      INFO  @ Fri, 11 Mar 2022 21:47:08: #1  total tags in treatment: 199977 
      INFO  @ Fri, 11 Mar 2022 21:47:08: #1 user defined the maximum tags... 
      INFO  @ Fri, 11 Mar 2022 21:47:08: #1 filter out redundant tags at the same location and the same strand by allowing at most 1 tag(s) 
      INFO  @ Fri, 11 Mar 2022 21:47:08: #1  tags after filtering in treatment: 199583 
      INFO  @ Fri, 11 Mar 2022 21:47:08: #1  Redundant rate of treatment: 0.00 
      INFO  @ Fri, 11 Mar 2022 21:47:08: #1  total tags in control: 199978 
      INFO  @ Fri, 11 Mar 2022 21:47:08: #1 user defined the maximum tags... 
      INFO  @ Fri, 11 Mar 2022 21:47:08: #1 filter out redundant tags at the same location and the same strand by allowing at most 1 tag(s) 
      INFO  @ Fri, 11 Mar 2022 21:47:08: #1  tags after filtering in control: 199867 
      INFO  @ Fri, 11 Mar 2022 21:47:08: #1  Redundant rate of control: 0.00 
      INFO  @ Fri, 11 Mar 2022 21:47:08: #1 finished! 
      INFO  @ Fri, 11 Mar 2022 21:47:08: #2 Build Peak Model... 
      INFO  @ Fri, 11 Mar 2022 21:47:08: #2 looking for paired plus/minus strand peaks... 
      INFO  @ Fri, 11 Mar 2022 21:47:09: #2 number of paired peaks: 4488 
      INFO  @ Fri, 11 Mar 2022 21:47:09: start model_add_line... 
      INFO  @ Fri, 11 Mar 2022 21:47:09: start X-correlation... 
      INFO  @ Fri, 11 Mar 2022 21:47:10: end of X-cor 
      INFO  @ Fri, 11 Mar 2022 21:47:10: #2 finished! 
      INFO  @ Fri, 11 Mar 2022 21:47:10: #2 predicted fragment length is 254 bps 
      INFO  @ Fri, 11 Mar 2022 21:47:10: #2 alternative fragment length(s) may be 254 bps 
      INFO  @ Fri, 11 Mar 2022 21:47:10: #2.2 Generate R script for model : ChIP_200K_bed_model.r 
      INFO  @ Fri, 11 Mar 2022 21:47:10: #3 Call peaks... 
      INFO  @ Fri, 11 Mar 2022 21:47:11: #3 Pre-compute pvalue-qvalue table... 
      INFO  @ Fri, 11 Mar 2022 21:47:13: #3 In the peak calling step, the following will be performed simultaneously: 
      INFO  @ Fri, 11 Mar 2022 21:47:13: #3   Write bedGraph files for treatment pileup (after scaling if necessary)... ChIP_200K_bed_treat_pileup.bdg 
      INFO  @ Fri, 11 Mar 2022 21:47:13: #3   Write bedGraph files for control lambda (after scaling if necessary)... ChIP_200K_bed_control_lambda.bdg 
      INFO  @ Fri, 11 Mar 2022 21:47:13: #3   Pileup will be based on sequencing depth in treatment. 
      INFO  @ Fri, 11 Mar 2022 21:47:13: #3 Call peaks for each chromosome... 
      INFO  @ Fri, 11 Mar 2022 21:47:25: #4 Write output xls file... ChIP_200K_bed_peaks.xls 
      INFO  @ Fri, 11 Mar 2022 21:47:26: #4 Write peak in narrowPeak format file... ChIP_200K_bed_peaks.narrowPeak 
      INFO  @ Fri, 11 Mar 2022 21:47:26: #4 Write summits bed file... ChIP_200K_bed_summits.bed 
      INFO  @ Fri, 11 Mar 2022 21:47:26: Done! 

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | treatment | ` {"__current_case__": 0, "input_treatment_file": {"values": [{"id": 94363059, "src": "hda"}]}, "t_multi_select": "No"} ` |
       | control | ` {"__current_case__": 0, "c_multiple": {"__current_case__": 0, "c_multi_select": "No", "input_control_file": {"values": [{"id": 94363062, "src": "hda"}]}}, "c_select": "Yes"} ` |
       | format | ` "BED" ` |
       | effective\_genome\_size\_options | ` {"__current_case__": 4, "effective_genome_size_options_selector": "user_defined", "gsize": "3300000000"} ` |
       | nomodel\_type | ` {"__current_case__": 0, "band_width": "300", "mfold_lower": "5", "mfold_upper": "50", "nomodel_type_selector": "create_model"} ` |
       | cutoff\_options | ` {"__current_case__": 1, "cutoff_options_selector": "qvalue", "qvalue": "0.05"} ` |
       | outputs | ` ["peaks_tabular", "bdg", "html"] ` |
       | advanced\_options | ` {"broad_options": {"__current_case__": 1, "broad_options_selector": "nobroad", "call_summits": "false"}, "keep_dup_options": {"__current_case__": 1, "keep_dup_options_selector": "1"}, "llocal": "", "nolambda": "false", "ratio": "", "slocal": "", "spmr": "false", "to_large": "false"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/macs2/macs2_callpeak (Test #2)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Output:**

    * ```console
      INFO  @ Fri, 11 Mar 2022 21:46:54: 
      # Command line: callpeak -t /corral4/main/objects/b/8/0/dataset_b804fa8b-042e-4072-8656-c78f41dcd477.dat --name ChIP_200K_bed -c /corral4/main/objects/3/1/2/dataset_3120fd52-6093-49fc-b21e-519f3c34f50c.dat --format BED --gsize 3300000000 --keep-dup 1 --qvalue 0.05 --mfold 5 50 --bw 300
      # ARGUMENTS LIST:
      # name = ChIP_200K_bed
      # format = BED
      # ChIP-seq file = ['/corral4/main/objects/b/8/0/dataset_b804fa8b-042e-4072-8656-c78f41dcd477.dat']
      # control file = ['/corral4/main/objects/3/1/2/dataset_3120fd52-6093-49fc-b21e-519f3c34f50c.dat']
      # effective genome size = 3.30e+09
      # band width = 300
      # model fold = [5, 50]
      # qvalue cutoff = 5.00e-02
      # Larger dataset will be scaled towards smaller dataset.
      # Range for calculating regional lambda is: 1000 bps and 10000 bps
      # Broad region calling is off
      # Paired-End mode is off
       
      INFO  @ Fri, 11 Mar 2022 21:46:54: #1 read tag files... 
      INFO  @ Fri, 11 Mar 2022 21:46:54: #1 read treatment tags... 
      INFO  @ Fri, 11 Mar 2022 21:46:54: #1.2 read input tags... 
      INFO  @ Fri, 11 Mar 2022 21:46:55: #1 tag size is determined as 100 bps 
      INFO  @ Fri, 11 Mar 2022 21:46:55: #1 tag size = 100 
      INFO  @ Fri, 11 Mar 2022 21:46:55: #1  total tags in treatment: 199977 
      INFO  @ Fri, 11 Mar 2022 21:46:55: #1 user defined the maximum tags... 
      INFO  @ Fri, 11 Mar 2022 21:46:55: #1 filter out redundant tags at the same location and the same strand by allowing at most 1 tag(s) 
      INFO  @ Fri, 11 Mar 2022 21:46:55: #1  tags after filtering in treatment: 199583 
      INFO  @ Fri, 11 Mar 2022 21:46:55: #1  Redundant rate of treatment: 0.00 
      INFO  @ Fri, 11 Mar 2022 21:46:55: #1  total tags in control: 199978 
      INFO  @ Fri, 11 Mar 2022 21:46:55: #1 user defined the maximum tags... 
      INFO  @ Fri, 11 Mar 2022 21:46:55: #1 filter out redundant tags at the same location and the same strand by allowing at most 1 tag(s) 
      INFO  @ Fri, 11 Mar 2022 21:46:55: #1  tags after filtering in control: 199867 
      INFO  @ Fri, 11 Mar 2022 21:46:55: #1  Redundant rate of control: 0.00 
      INFO  @ Fri, 11 Mar 2022 21:46:55: #1 finished! 
      INFO  @ Fri, 11 Mar 2022 21:46:55: #2 Build Peak Model... 
      INFO  @ Fri, 11 Mar 2022 21:46:55: #2 looking for paired plus/minus strand peaks... 
      INFO  @ Fri, 11 Mar 2022 21:46:55: #2 number of paired peaks: 4488 
      INFO  @ Fri, 11 Mar 2022 21:46:55: start model_add_line... 
      INFO  @ Fri, 11 Mar 2022 21:46:55: start X-correlation... 
      INFO  @ Fri, 11 Mar 2022 21:46:55: end of X-cor 
      INFO  @ Fri, 11 Mar 2022 21:46:55: #2 finished! 
      INFO  @ Fri, 11 Mar 2022 21:46:55: #2 predicted fragment length is 254 bps 
      INFO  @ Fri, 11 Mar 2022 21:46:55: #2 alternative fragment length(s) may be 254 bps 
      INFO  @ Fri, 11 Mar 2022 21:46:55: #2.2 Generate R script for model : ChIP_200K_bed_model.r 
      INFO  @ Fri, 11 Mar 2022 21:46:55: #3 Call peaks... 
      INFO  @ Fri, 11 Mar 2022 21:46:55: #3 Pre-compute pvalue-qvalue table... 
      INFO  @ Fri, 11 Mar 2022 21:46:57: #3 Call peaks for each chromosome... 
      INFO  @ Fri, 11 Mar 2022 21:46:57: #4 Write output xls file... ChIP_200K_bed_peaks.xls 
      INFO  @ Fri, 11 Mar 2022 21:46:58: #4 Write peak in narrowPeak format file... ChIP_200K_bed_peaks.narrowPeak 
      INFO  @ Fri, 11 Mar 2022 21:46:58: #4 Write summits bed file... ChIP_200K_bed_summits.bed 
      INFO  @ Fri, 11 Mar 2022 21:46:58: Done! 

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | treatment | ` {"__current_case__": 0, "input_treatment_file": {"values": [{"id": 94363059, "src": "hda"}]}, "t_multi_select": "No"} ` |
       | control | ` {"__current_case__": 0, "c_multiple": {"__current_case__": 0, "c_multi_select": "No", "input_control_file": {"values": [{"id": 94363062, "src": "hda"}]}}, "c_select": "Yes"} ` |
       | format | ` "BED" ` |
       | effective\_genome\_size\_options | ` {"__current_case__": 4, "effective_genome_size_options_selector": "user_defined", "gsize": "3300000000"} ` |
       | nomodel\_type | ` {"__current_case__": 0, "band_width": "300", "mfold_lower": "5", "mfold_upper": "50", "nomodel_type_selector": "create_model"} ` |
       | cutoff\_options | ` {"__current_case__": 1, "cutoff_options_selector": "qvalue", "qvalue": "0.05"} ` |
       | outputs | ` "pdf" ` |
       | advanced\_options | ` {"broad_options": {"__current_case__": 1, "broad_options_selector": "nobroad", "call_summits": "false"}, "keep_dup_options": {"__current_case__": 1, "keep_dup_options_selector": "1"}, "llocal": "", "nolambda": "false", "ratio": "", "slocal": "", "spmr": "false", "to_large": "false"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/macs2/macs2_callpeak (Test #3)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Output:**

    * ```console
      INFO  @ Fri, 11 Mar 2022 21:49:14: 
      # Command line: callpeak -t /corral4/main/objects/2/2/0/dataset_220ad041-9b75-4cf6-be26-2a903cfe271e.dat --name bwa-mem-test1_bam --format BAMPE --gsize 3300000000 --nolambda --keep-dup 1 --qvalue 0.05 --nomodel --extsize 200 --shift 0
      # ARGUMENTS LIST:
      # name = bwa-mem-test1_bam
      # format = BAMPE
      # ChIP-seq file = ['/corral4/main/objects/2/2/0/dataset_220ad041-9b75-4cf6-be26-2a903cfe271e.dat']
      # control file = None
      # effective genome size = 3.30e+09
      # band width = 300
      # model fold = [5, 50]
      # qvalue cutoff = 5.00e-02
      # Larger dataset will be scaled towards smaller dataset.
      # Range for calculating regional lambda is: 10000 bps
      # Broad region calling is off
      # Paired-End mode is on
       
      INFO  @ Fri, 11 Mar 2022 21:49:14: #1 read fragment files... 
      INFO  @ Fri, 11 Mar 2022 21:49:14: #1 read treatment fragments... 
      INFO  @ Fri, 11 Mar 2022 21:49:15: #1 mean fragment size is determined as 193 bp from treatment 
      INFO  @ Fri, 11 Mar 2022 21:49:15: #1 fragment size = 193 
      INFO  @ Fri, 11 Mar 2022 21:49:15: #1  total fragments in treatment: 99 
      INFO  @ Fri, 11 Mar 2022 21:49:15: #1 user defined the maximum fragments... 
      INFO  @ Fri, 11 Mar 2022 21:49:15: #1 filter out redundant fragments by allowing at most 1 identical fragment(s) 
      INFO  @ Fri, 11 Mar 2022 21:49:16: #1  fragments after filtering in treatment: 44 
      INFO  @ Fri, 11 Mar 2022 21:49:16: #1  Redundant rate of treatment: 0.56 
      INFO  @ Fri, 11 Mar 2022 21:49:16: #1 finished! 
      INFO  @ Fri, 11 Mar 2022 21:49:16: #2 Build Peak Model... 
      INFO  @ Fri, 11 Mar 2022 21:49:16: #2 Skipped... 
      INFO  @ Fri, 11 Mar 2022 21:49:16: #2 Use 193 as fragment length 
      INFO  @ Fri, 11 Mar 2022 21:49:16: #3 Call peaks... 
      INFO  @ Fri, 11 Mar 2022 21:49:16: # local lambda is disabled! 
      INFO  @ Fri, 11 Mar 2022 21:49:16: #3 !!!! DYNAMIC LAMBDA IS DISABLED !!!! 
      INFO  @ Fri, 11 Mar 2022 21:49:16: #3 Pre-compute pvalue-qvalue table... 
      INFO  @ Fri, 11 Mar 2022 21:49:17: #3 Call peaks for each chromosome... 
      INFO  @ Fri, 11 Mar 2022 21:49:17: #4 Write output xls file... bwa-mem-test1_bam_peaks.xls 
      INFO  @ Fri, 11 Mar 2022 21:49:17: #4 Write peak in narrowPeak format file... bwa-mem-test1_bam_peaks.narrowPeak 
      INFO  @ Fri, 11 Mar 2022 21:49:17: #4 Write summits bed file... bwa-mem-test1_bam_summits.bed 
      INFO  @ Fri, 11 Mar 2022 21:49:17: Done! 

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | treatment | ` {"__current_case__": 0, "input_treatment_file": {"values": [{"id": 94363056, "src": "hda"}]}, "t_multi_select": "No"} ` |
       | control | ` {"__current_case__": 1, "c_select": "No"} ` |
       | format | ` "BAMPE" ` |
       | effective\_genome\_size\_options | ` {"__current_case__": 4, "effective_genome_size_options_selector": "user_defined", "gsize": "3300000000"} ` |
       | nomodel\_type | ` {"__current_case__": 1, "extsize": "200", "nomodel_type_selector": "nomodel", "shift": "0"} ` |
       | cutoff\_options | ` {"__current_case__": 1, "cutoff_options_selector": "qvalue", "qvalue": "0.05"} ` |
       | outputs | ` "pdf" ` |
       | advanced\_options | ` {"broad_options": {"__current_case__": 1, "broad_options_selector": "nobroad", "call_summits": "false"}, "keep_dup_options": {"__current_case__": 1, "keep_dup_options_selector": "1"}, "llocal": "", "nolambda": "true", "ratio": "", "slocal": "", "spmr": "false", "to_large": "false"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


</details>
