### ISSUE TITLE
Test table_annovar 0.2

### ISSUE THREAD

**Issue by jennaj** [mvdbeek/usegalaxy-tests#28]
Testing functionality

tool_id=toolshed.g2.bx.psu.edu/repos/devteam/table_annovar/table_annovar/0.2

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/devteam/table_annovar/table_annovar/0.2

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary


|  State | Count |
| ---------- | ----- |
| Total      | 0 |
| Passed     | 0 |
| Error      | 0 |
| Failure    | 0 |
| Skipped    | 0 |

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/devteam/table_annovar/table_annovar/0.2

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary


|  State | Count |
| ---------- | ----- |
| Total      | 0 |
| Passed     | 0 |
| Error      | 0 |
| Failure    | 0 |
| Skipped    | 0 |

**Comment by jennaj** [comment]
This tool isn't functional anymore. 

Do we want to still keep it? Do we need to? 

No test cases but I've used this old tutorial vcf with it before (circa 2015) and it produced an output. Doesn't now.

There is at a minimum a variable problem. 

`stdout`
> Unknown option: vcfinput

https://usegalaxy.org/u/jen/h/test-annovar

Had three open issues about this tool  -- closing all out. https://github.com/galaxyproject/usegalaxy-playbook/issues?q=is%3Aissue+is%3Aopen+annovar
