### ISSUE TITLE
Test Prokka 1.14.6+galaxy1

### ISSUE THREAD

**Issue by natefoo** [mvdbeek/usegalaxy-tests#3]
EDIT: forgot the slash commands only work in comments

**Comment by natefoo** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/crs4/prokka/prokka/1.14.6+galaxy1

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 100.0%" aria-valuenow="1" aria-valuemin="0" aria-valuemax="1" data-toggle="tooltip" title="1 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="1" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="1" title="0 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 1 |
| Passed     | 1 |
| Error      | 0 |
| Failure    | 0 |
| Skipped    | 0 |


<details><summary>Passed s</summary>

* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/crs4/prokka/prokka (Test #1)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/corral4/main/jobs/039/109/39109957/_job_tmp -Xmx28g -Xms256m
      Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/corral4/main/jobs/039/109/39109957/_job_tmp -Xmx28g -Xms256m

      ```
    **Standard Output:**

    * ```console
      [tbl2asn-forever] Found Prokka input, correcting dates in .gbf|.sqn files.
      [tbl2asn-forever] Correcting dates in outdir/prokka.gbf
      [tbl2asn-forever] Correcting dates in outdir/prokka.sqn
      [tbl2asn-forever] Dates changed from 01-JAN-2019 to 17-NOV-2021

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | locustag | ` "" ` |
       | increment | ` "1" ` |
       | gffver | ` "3" ` |
       | compliant | ` {"__current_case__": 0, "addgenes": "false", "compliant_select": "no", "mincontig": "200"} ` |
       | centre | ` "" ` |
       | genus | ` "" ` |
       | species | ` "" ` |
       | strain | ` "" ` |
       | plasmid | ` "" ` |
       | kingdom | ` {"__current_case__": 1, "gcode": "11", "kingdom_select": "Bacteria"} ` |
       | usegenus | ` "false" ` |
       | proteins | ` None ` |
       | metagenome | ` "false" ` |
       | fast | ` "false" ` |
       | evalue | ` "1e-06" ` |
       | rfam | ` "false" ` |
       | norrna | ` "false" ` |
       | notrna | ` "false" ` |
       | outputs | ` ["gff", "gbk", "fna", "faa", "ffn", "sqn", "fsa", "tbl", "tsv", "err", "txt"] ` |
       | \_\_job\_resource | ` {"__current_case__": 0, "__job_resource__select": "no"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "fasta" ` |



  </div></details>


</details>
