### ISSUE TITLE
Test ggplot2_point 3.3.5+galaxy0

### ISSUE THREAD

**Issue by jennaj** [mvdbeek/usegalaxy-tests#30]
Ref Tapas https://gtnsmrgsbord.slack.com/archives/C01ES914GCU/p1647273416314139

tool_id=toolshed.g2.bx.psu.edu/repos/iuc/ggplot2_point/ggplot2_point/3.3.5+galaxy0

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/iuc/ggplot2_point/ggplot2_point/3.3.5+galaxy0

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 100.0%" aria-valuenow="2" aria-valuemin="0" aria-valuemax="2" data-toggle="tooltip" title="2 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="2" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="2" title="0 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 2 |
| Passed     | 2 |
| Error      | 0 |
| Failure    | 0 |
| Skipped    | 0 |


<details><summary>Passed s</summary>

* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/ggplot2_point/ggplot2_point (Test #1)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      Warning message:
      In Sys.setlocale("LC_MESSAGES", "en_US.UTF-8") :
        OS reports request to set locale to "en_US.UTF-8" cannot be honored

      ```
    **Standard Output:**

    * ```console
      

              options(show.error.messages=F, error=function(){cat(geterrmessage(), file=stderr()); q("no",1,F)})

              loc <- Sys.setlocale("LC_MESSAGES", "en_US.UTF-8")
          

      library(ggplot2)


              #Choose between automatically scaled x and y axis or user defined
                  gg_scalex = NULL
                  gg_scaley = NULL
          


                  gg_theme = theme_bw()
          


                  gg_legend = theme(legend.position="right")
          

      input <- read.csv('/corral4/main/objects/b/3/d/dataset_b3dd7953-594b-4b9d-b11c-d75e073cf805.dat', sep='\t', header=TRUE)

      names(input)[8] <- "xcol"
      names(input)[9] <- "ycol"

          gg_facet = NULL
          gg_factor = NULL
          color_scale = NULL

              gg_point = geom_point(size=1, alpha=1, gg_factor)
              gg_line = geom_line(size=1, alpha=1, gg_factor)


          

          gg_axistitle = theme(axis.title = element_text(color = NULL, size = NULL, face = NULL))

          gg_axistext = theme(axis.text = element_text(color = NULL, size = NULL, face = NULL))

          gg_plottitle = theme(plot.title = element_text(color = NULL, size = NULL, face = NULL))

          gg_gridline = NULL

          gg_line = NULL

      #this is the actual ggplot command to make the final plot(s)
      plot_out <- ggplot(input, aes(xcol, ycol)) + gg_point + gg_line + gg_facet +
          gg_theme + gg_scalex + gg_scaley + color_scale + gg_legend + ggtitle('') + xlab('Title of x-axis') + ylab('Title of y-axis')+
          gg_axistitle + gg_axistext + gg_plottitle + gg_gridline


              gg_width <- as.double('7.0')
              gg_height <- as.double('7.0')
              gg_unit <- 'in'
              gg_dpi <- as.double('300.0')
              gg_add_device <- 'pdf'
              output1 <- '/corral4/main/jobs/041/374/41374376/outputs/galaxy_dataset_9a7c77de-5de0-4e94-8000-3ce4d48442d7.dat'
              output2 <- '/corral4/main/jobs/041/374/41374376/outputs/galaxy_dataset_d9b069ec-a645-4a67-b5c7-07f5d0acda03.dat'

              ggsave(filename = output1, plot = plot_out, width = gg_width, height = gg_height, units = gg_unit, dpi = gg_dpi, device = "png")
              if(gg_add_device != "none"){
                ggsave(filename = output2, plot = plot_out, width = gg_width, height = gg_height, units = gg_unit, dpi = gg_dpi, device = gg_add_device)
              }
          
              
      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | xplot | ` "8" ` |
       | yplot | ` "9" ` |
       | title | ` "" ` |
       | xlab | ` "Title of x-axis" ` |
       | ylab | ` "Title of y-axis" ` |
       | adv | ` {"axis_text_customization": {"__current_case__": 0, "axis_customization": "default"}, "axis_title_customization": {"__current_case__": 0, "axis_customization": "default"}, "factor": {"__current_case__": 0, "factoring": "Default"}, "gridlinecust": "default", "legend": "yes", "plot_title_customization": {"__current_case__": 0, "axis_customization": "default"}, "scaling": {"__current_case__": 0, "plot_scaling": "Automatic"}, "theme": "bw", "transform": "none", "type_conditional": {"__current_case__": 0, "points": {"__current_case__": 0, "pointoptions": "default"}, "type_options": "points"}} ` |
       | out | ` {"additional_output_format": "pdf", "dpi_output_dim": "300.0", "height_output_dim": "7.0", "unit_output_dim": "in", "width_output_dim": "7.0"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/ggplot2_point/ggplot2_point (Test #2)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      Warning message:
      In Sys.setlocale("LC_MESSAGES", "en_US.UTF-8") :
        OS reports request to set locale to "en_US.UTF-8" cannot be honored

      ```
    **Standard Output:**

    * ```console
      

              options(show.error.messages=F, error=function(){cat(geterrmessage(), file=stderr()); q("no",1,F)})

              loc <- Sys.setlocale("LC_MESSAGES", "en_US.UTF-8")
          

      library(ggplot2)


              #Choose between automatically scaled x and y axis or user defined
                  gg_scalex = NULL
                  gg_scaley = NULL
          


                  gg_theme = theme_bw()
          


                  gg_legend = theme(legend.position="right")
          

      input <- read.csv('/corral4/main/objects/b/3/d/dataset_b3dd7953-594b-4b9d-b11c-d75e073cf805.dat', sep='\t', header=TRUE)

      names(input)[8] <- "xcol"
      names(input)[9] <- "ycol"

          gg_facet = NULL
          gg_factor = NULL
          color_scale = NULL

              gg_point = geom_point(size=1, alpha=1, gg_factor)
              gg_line = geom_line(size=1, alpha=1, gg_factor)


          

          gg_axistitle = theme(axis.title = element_text(color = NULL, size = NULL, face = NULL))

          gg_axistext = theme(axis.text = element_text(color = 'red', size = 12.0, face = 'plain'))

          gg_plottitle = theme(plot.title = element_text(color = NULL, size = NULL, face = NULL))

          gg_gridline = NULL

          gg_line = NULL

      #this is the actual ggplot command to make the final plot(s)
      plot_out <- ggplot(input, aes(xcol, ycol)) + gg_point + gg_line + gg_facet +
          gg_theme + gg_scalex + gg_scaley + color_scale + gg_legend + ggtitle('') + xlab('Title of x-axis') + ylab('Title of y-axis')+
          gg_axistitle + gg_axistext + gg_plottitle + gg_gridline


              gg_width <- as.double('7.0')
              gg_height <- as.double('7.0')
              gg_unit <- 'in'
              gg_dpi <- as.double('300.0')
              gg_add_device <- 'pdf'
              output1 <- '/corral4/main/jobs/041/374/41374377/outputs/galaxy_dataset_425bcc65-5cb9-410f-b07b-aac5d91135fd.dat'
              output2 <- '/corral4/main/jobs/041/374/41374377/outputs/galaxy_dataset_25d89259-e26b-4a2d-b3a4-acb5eb50310c.dat'

              ggsave(filename = output1, plot = plot_out, width = gg_width, height = gg_height, units = gg_unit, dpi = gg_dpi, device = "png")
              if(gg_add_device != "none"){
                ggsave(filename = output2, plot = plot_out, width = gg_width, height = gg_height, units = gg_unit, dpi = gg_dpi, device = gg_add_device)
              }
          
              
      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | xplot | ` "8" ` |
       | yplot | ` "9" ` |
       | title | ` "" ` |
       | xlab | ` "Title of x-axis" ` |
       | ylab | ` "Title of y-axis" ` |
       | adv | ` {"axis_text_customization": {"__current_case__": 1, "axis_customization": "defined", "color": "red", "face": "plain", "size": "12.0"}, "axis_title_customization": {"__current_case__": 0, "axis_customization": "default"}, "factor": {"__current_case__": 0, "factoring": "Default"}, "gridlinecust": "default", "legend": "yes", "plot_title_customization": {"__current_case__": 0, "axis_customization": "default"}, "scaling": {"__current_case__": 0, "plot_scaling": "Automatic"}, "theme": "bw", "transform": "none", "type_conditional": {"__current_case__": 0, "points": {"__current_case__": 0, "pointoptions": "default"}, "type_options": "points"}} ` |
       | out | ` {"additional_output_format": "pdf", "dpi_output_dim": "300.0", "height_output_dim": "7.0", "unit_output_dim": "in", "width_output_dim": "7.0"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


</details>
