### ISSUE TITLE
Test _dropletBarcodePlot 1.6.1+galaxy2

### ISSUE THREAD

**Issue by jennaj** [mvdbeek/usegalaxy-tests#31]
Tapas report of tool issue, maybe technical

https://gtnsmrgsbord.slack.com/archives/C0250JZCA6R/p1647284150452049

https://usegalaxy.org/root?tool_id=toolshed.g2.bx.psu.edu/repos/ebi-gxa/droplet_barcode_plot/_dropletBarcodePlot/1.6.1+galaxy2

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/ebi-gxa/droplet_barcode_plot/_dropletBarcodePlot/1.6.1+galaxy2

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="1" data-toggle="tooltip" title="0 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="1" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 100.0%" aria-valuenow="1" aria-valuemin="0" aria-valuemax="1" title="1 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 1 |
| Passed     | 0 |
| Error      | 0 |
| Failure    | 1 |
| Skipped    | 0 |


<details><summary>Failed s</summary>

* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/ebi-gxa/droplet_barcode_plot/_dropletBarcodePlot (Test #1)</summary><div class="padded">

    **Problems**:
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/ebi-gxa/droplet_barcode_plot/_dropletBarcodePlot/1.6.1+galaxy2, exit_code: 127, stderr: /corral4/main/jobs/041/378/41378047/tool_script.sh: line 9: dropletBarcodePlot.R: command not found
      .
      ```
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/ebi-gxa/droplet_barcode_plot/_dropletBarcodePlot/1.6.1+galaxy2, exit_code: 127, stderr: /corral4/main/jobs/041/378/41378047/tool_script.sh: line 9: dropletBarcodePlot.R: command not found
      .
      ```
    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      127
      ```
    **Standard Error:**

    * ```console
      /corral4/main/jobs/041/378/41378047/tool_script.sh: line 9: dropletBarcodePlot.R: command not found

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | input | ` {"__current_case__": 1, "barcode_frequencies": {"values": [{"id": 94442524, "src": "hda"}]}, "type": "false"} ` |
       | label | ` "" ` |
       | density\_bins | ` "50" ` |
       | roryk\_multiplier | ` "1.5" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


</details>

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/ebi-gxa/droplet_barcode_plot/_dropletBarcodePlot/1.6.1+galaxy2

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="1" data-toggle="tooltip" title="0 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="1" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 100.0%" aria-valuenow="1" aria-valuemin="0" aria-valuemax="1" title="1 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 1 |
| Passed     | 0 |
| Error      | 1 |
| Failure    | 0 |
| Skipped    | 0 |


<details><summary>Errored s</summary>

* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/ebi-gxa/droplet_barcode_plot/_dropletBarcodePlot (Test #1)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Job in error state.. tool_id: upload1, exit_code: None, stderr: .
      ```

  </div></details>


</details>

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/ebi-gxa/droplet_barcode_plot/_dropletBarcodePlot/1.6.1+galaxy2

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="1" data-toggle="tooltip" title="0 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="1" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 100.0%" aria-valuenow="1" aria-valuemin="0" aria-valuemax="1" title="1 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 1 |
| Passed     | 0 |
| Error      | 0 |
| Failure    | 1 |
| Skipped    | 0 |


<details><summary>Failed s</summary>

* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/ebi-gxa/droplet_barcode_plot/_dropletBarcodePlot (Test #1)</summary><div class="padded">

    **Problems**:
    * ```
      Output plot_file:  different than expected, difference (using diff):
      ( /tmp/tmp9mwjpuk0barcode_plot.png v. /tmp/tmpgenkx1fabarcode_plot.png )
      Binary data detected, not displaying diff
      ```
    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Output:**

    * ```console
      null device 
                1 

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | input | ` {"__current_case__": 1, "barcode_frequencies": {"values": [{"id": 94524029, "src": "hda"}]}, "type": "false"} ` |
       | label | ` "" ` |
       | density\_bins | ` "50" ` |
       | roryk\_multiplier | ` "1.5" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


</details>

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/ebi-gxa/droplet_barcode_plot/_dropletBarcodePlot/1.6.1+galaxy2

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="1" data-toggle="tooltip" title="0 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="1" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 100.0%" aria-valuenow="1" aria-valuemin="0" aria-valuemax="1" title="1 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 1 |
| Passed     | 0 |
| Error      | 0 |
| Failure    | 1 |
| Skipped    | 0 |


<details><summary>Failed s</summary>

* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/ebi-gxa/droplet_barcode_plot/_dropletBarcodePlot (Test #1)</summary><div class="padded">

    **Problems**:
    * ```
      Output plot_file:  different than expected, difference (using diff):
      ( /tmp/tmpkp8tw_o3barcode_plot.png v. /tmp/tmp03ff_dpibarcode_plot.png )
      Binary data detected, not displaying diff
      ```
    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Output:**

    * ```console
      null device 
                1 

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | input | ` {"__current_case__": 1, "barcode_frequencies": {"values": [{"id": 94720757, "src": "hda"}]}, "type": "false"} ` |
       | label | ` "" ` |
       | density\_bins | ` "50" ` |
       | roryk\_multiplier | ` "1.5" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


</details>

**Comment by jennaj** [comment]
^^ Test case expects a plain text file when the output isn't in plain text?
How did anyone get the test case to pass? Maybe something changed.
Could use an md5 (or similar) instead.
