### ISSUE TITLE
Test circos 0.69.8+galaxy10

### ISSUE THREAD

**Issue by jennaj** [mvdbeek/usegalaxy-tests#32]
Install test

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/iuc/circos/circos/0.69.8+galaxy10

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="3" data-toggle="tooltip" title="0 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="3" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 100.0%" aria-valuenow="3" aria-valuemin="0" aria-valuemax="3" title="3 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 3 |
| Passed     | 0 |
| Error      | 2 |
| Failure    | 1 |
| Skipped    | 0 |


<details><summary>Errored s</summary>

* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/iuc/circos/circos (Test #2)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Value ('1') must fulfill float('200') <= value <= float('inf'), Value ('1') must fulfill float('200') <= value <= float('inf'), Value ('1') must fulfill float('200') <= value <= float('inf'), Value ('1') must fulfill float('200') <= value <= float('inf')
      ```

  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/iuc/circos/circos (Test #3)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Job in error state.. tool_id: upload1, exit_code: None, stderr: .
      ```

  </div></details>


</details>
<details><summary>Failed s</summary>

* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/iuc/circos/circos (Test #1)</summary><div class="padded">

    **Problems**:
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/circos/circos/0.69.8+galaxy10, exit_code: None, stderr: .
      ```
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/circos/circos/0.69.8+galaxy10, exit_code: None, stderr: .
      ```
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/circos/circos/0.69.8+galaxy10, exit_code: None, stderr: .
      ```
    **Command Line:**

    * ```console
      
      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | reference\_genome | ` {"ref": {"__current_case__": 2, "genome_fasta": {"values": [{"id": 94474128, "src": "hda"}]}, "ref_source": "history"}} ` |
       | ideogram | ` {"angle_offset": "-90", "angle_orientation": "clockwise", "bands": {"band_stroke_color": "#000000", "band_stroke_thickness": "0", "band_transparency": "3", "fill_bands": "true", "show_bands": "true"}, "chromosomes_reverse": null, "ideogram_labels": {"parallel": "true", "radius_offset": "0.075", "show_label": "true", "size": "24"}, "limit_chromosomes": null, "pairwise_spacing": [], "radius": "0.9", "spacing": "0.5", "thickness": "30.0", "units": "mb"} ` |
       | plot\_options | ` {"background": {"__current_case__": 1, "background_color": "#ffffff", "background_select": "color"}, "colour_profile": null, "radius": "1500"} ` |
       | sec\_tdd | ` {"data": []} ` |
       | sec\_links | ` {"data": []} ` |
       | scaling | ` {"zooms": []} ` |
       | ticks | ` {"radius": "1.0", "skip_first_label": "false", "skip_last_label": "false", "tick_group": []} ` |
       | limits | ` {"max_ideograms": "200", "max_links": "25000", "max_points_per_track": "25000", "max_ticks": "5000"} ` |
       | outputs | ` {"png": "true", "svg": "true", "tar": "false"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "fasta" ` |



  </div></details>


</details>

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/iuc/circos/circos/0.69.8+galaxy10

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 66.66666666666666%" aria-valuenow="2" aria-valuemin="0" aria-valuemax="3" data-toggle="tooltip" title="2 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="3" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 33.33333333333333%" aria-valuenow="1" aria-valuemin="0" aria-valuemax="3" title="1 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 3 |
| Passed     | 2 |
| Error      | 1 |
| Failure    | 0 |
| Skipped    | 0 |


<details><summary>Errored s</summary>

* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/iuc/circos/circos (Test #2)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Value ('1') must fulfill float('200') <= value <= float('inf'), Value ('1') must fulfill float('200') <= value <= float('inf'), Value ('1') must fulfill float('200') <= value <= float('inf'), Value ('1') must fulfill float('200') <= value <= float('inf')
      ```

  </div></details>


</details>
<details><summary>Passed s</summary>

* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/circos/circos (Test #1)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.

      ```
    **Standard Output:**

    * ```console
      debuggroup summary 0.25s welcome to circos v0.69-8 15 Jun 2019 on Perl 5.026002
      debuggroup summary 0.25s current working directory /corral4/main/jobs/041/422/41422648/working
      debuggroup summary 0.25s command /usr/local/bin/circos -conf circos/conf/circos.conf -noparanoid
      debuggroup summary 0.25s loading configuration from file circos/conf/circos.conf
      debuggroup summary 0.25s found conf file circos/conf/circos.conf
      debuggroup summary 0.48s debug will appear for these features: output,summary
      debuggroup summary 0.48s bitmap output image ./circos.png
      debuggroup summary 0.48s SVG output image ./circos.svg
      debuggroup summary 0.48s parsing karyotype and organizing ideograms
      debuggroup summary 0.49s karyotype has 2 chromosomes of total size 56,082
      debuggroup summary 0.49s applying global and local scaling
      debuggroup summary 0.49s allocating image, colors and brushes
      debuggroup summary 10.99s drawing 2 ideograms of total size 56,082
      debuggroup summary 10.99s drawing highlights and ideograms
      debuggroup output 11.00s generating output
      debuggroup output 11.57s created PNG image ./circos.png (40 kb)
      debuggroup output 11.57s created SVG image ./circos.svg (2 kb)

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | reference\_genome | ` {"ref": {"__current_case__": 2, "genome_fasta": {"values": [{"id": 94521227, "src": "hda"}]}, "ref_source": "history"}} ` |
       | ideogram | ` {"angle_offset": "-90", "angle_orientation": "clockwise", "bands": {"band_stroke_color": "#000000", "band_stroke_thickness": "0", "band_transparency": "3", "fill_bands": "true", "show_bands": "true"}, "chromosomes_reverse": null, "ideogram_labels": {"parallel": "true", "radius_offset": "0.075", "show_label": "true", "size": "24"}, "limit_chromosomes": null, "pairwise_spacing": [], "radius": "0.9", "spacing": "0.5", "thickness": "30.0", "units": "mb"} ` |
       | plot\_options | ` {"background": {"__current_case__": 1, "background_color": "#ffffff", "background_select": "color"}, "colour_profile": null, "radius": "1500"} ` |
       | sec\_tdd | ` {"data": []} ` |
       | sec\_links | ` {"data": []} ` |
       | scaling | ` {"zooms": []} ` |
       | ticks | ` {"radius": "1.0", "skip_first_label": "false", "skip_last_label": "false", "tick_group": []} ` |
       | limits | ` {"max_ideograms": "200", "max_links": "25000", "max_points_per_track": "25000", "max_ticks": "5000"} ` |
       | outputs | ` {"png": "true", "svg": "true", "tar": "false"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "auto" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/circos/circos (Test #3)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.
      Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.
      Use of uninitialized value within %Circos::Error::GROUPERROR in uc at /usr/local/bin/../lib/Circos/Error.pm line 354, <F> line 21.
      Use of uninitialized value within %Circos::Error::GROUPERROR in uc at /usr/local/bin/../lib/Circos/Error.pm line 354, <F> line 21.
      Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781, <F> line 21.
      Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.
      Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.
      Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781, <F> line 1214.
      Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.
      Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.
      Use of uninitialized value within %Circos::Error::GROUPERROR in uc at /usr/local/bin/../lib/Circos/Error.pm line 354.

      ```
    **Standard Output:**

    * ```console
      debuggroup summary 0.41s welcome to circos v0.69-8 15 Jun 2019 on Perl 5.026002
      debuggroup summary 0.42s current working directory /corral4/main/jobs/041/422/41422649/working
      debuggroup summary 0.42s command /usr/local/bin/circos -conf circos/conf/circos.conf -noparanoid
      debuggroup summary 0.42s loading configuration from file circos/conf/circos.conf
      debuggroup summary 0.43s found conf file circos/conf/circos.conf
      debuggroup summary 2.12s debug will appear for these features: output,summary
      debuggroup summary 2.12s bitmap output image ./circos.png
      debuggroup summary 2.12s SVG output image ./circos.svg
      debuggroup summary 2.27s parsing karyotype and organizing ideograms
      debuggroup summary 2.53s karyotype has 2 chromosomes of total size 56,082
      debuggroup summary 2.53s applying global and local scaling
      debuggroup summary 2.54s allocating image, colors and brushes
      debuggroup summary 21.85s drawing 2 ideograms of total size 56,082
      debuggroup summary 21.85s drawing highlights and ideograms
      debuggroup summary 22.00s found conf file /usr/local/bin/../etc/tracks/link.conf
      debuggroup summary 22.00s process track_0 link circos/conf/../data/links-0.txt
      debuggroup summary 22.01s drawing link track_0 z 0
      debuggroup !circoswarning 22.14s  Data point of type [link] [50000-50500] extended past end of ideogram [ctgA 0-50001]. This data point will be [trimmed].
      debuggroup !circoswarning 22.14s  Data point of type [link] [51000-51500] extended past end of ideogram [ctgA 0-50001]. This data point will be [hidden].
      debuggroup summary 22.15s found conf file /usr/local/bin/../etc/tracks/histogram.conf
      debuggroup summary 22.15s found conf file /usr/local/bin/../etc/tracks/scatter.conf
      debuggroup summary 22.15s found conf file /usr/local/bin/../etc/tracks/tile.conf
      debuggroup summary 22.15s processing track_0 histogram circos/conf/../data/data-0.txt
      debuggroup summary 22.54s processing track_1 scatter circos/conf/../data/data-1.txt
      debuggroup summary 23.20s processing track_2 tile circos/conf/../data/data-2.txt
      debuggroup summary 23.29s drawing track_0 histogram z 0 data-0.txt orient out
      debuggroup summary 23.35s found conf file /usr/local/bin/../etc/tracks/axis.conf
      debuggroup summary 25.21s drawing track_1 scatter z 0 data-1.txt orient out
      debuggroup summary 25.27s found conf file /usr/local/bin/../etc/tracks/axis.conf
      debuggroup summary 25.81s drawing track_2 tile z 0 data-2.txt orient out
      debuggroup summary 25.82s found conf file /usr/local/bin/../etc/tracks/axis.conf
      debuggroup !circoswarning 26.32s  Data point of type [tile] [3013-6130] extended past end of ideogram [ctgB 0-6079]. This data point will be [trimmed].
      debuggroup output 26.33s generating output
      debuggroup output 27.27s created PNG image ./circos.png (539 kb)
      debuggroup output 27.27s created SVG image ./circos.svg (414 kb)

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | reference\_genome | ` {"ref": {"__current_case__": 2, "genome_fasta": {"values": [{"id": 94521227, "src": "hda"}]}, "ref_source": "history"}} ` |
       | ideogram | ` {"angle_offset": "-90", "angle_orientation": "clockwise", "bands": {"band_stroke_color": "#000000", "band_stroke_thickness": "0", "band_transparency": "3", "fill_bands": "true", "show_bands": "true"}, "chromosomes_reverse": null, "ideogram_labels": {"parallel": "true", "radius_offset": "0.075", "show_label": "true", "size": "24"}, "limit_chromosomes": null, "pairwise_spacing": [], "radius": "0.9", "spacing": "0.5", "thickness": "30.0", "units": "kb"} ` |
       | plot\_options | ` {"background": {"__current_case__": 1, "background_color": "#ffffff", "background_select": "color"}, "colour_profile": null, "radius": "1500"} ` |
       | sec\_tdd | ` {"data": [{"__index__": 0, "minmax": {"__current_case__": 1, "minmax_select": "no"}, "minsize": "0.0", "orientation": "false", "plot_format": {"__current_case__": 0, "data_source": {"values": [{"id": 94521231, "src": "hda"}]}, "format_specific": {"extend_bins": "false", "fill_color": "#ffdcfc", "fill_color_alpha": "1.0", "fill_under": "true", "stroke_color": "#000000", "stroke_color_alpha": "1.0", "stroke_thickness": "1"}, "plot_format_select": "histogram"}, "r0": "0.8", "r1": "0.9", "sec_axes": {"axes": [], "only_if_data": "always"}, "sec_bkgs": {"backgrounds": [], "only_if_data": "always"}, "sec_rule": {"rules": []}, "zdepth": "0"}, {"__index__": 1, "minmax": {"__current_case__": 1, "minmax_select": "no"}, "minsize": "0.0", "orientation": "false", "plot_format": {"__current_case__": 5, "data_source": {"values": [{"id": 94521231, "src": "hda"}]}, "format_specific": {"fill_color": "#555555", "fill_color_alpha": "1.0", "glyph": "circle", "glyph_size": "8", "stroke_color": "#000000", "stroke_color_alpha": "1.0", "stroke_thickness": "1"}, "plot_format_select": "scatter"}, "r0": "0.7", "r1": "0.8", "sec_axes": {"axes": [], "only_if_data": "always"}, "sec_bkgs": {"backgrounds": [], "only_if_data": "always"}, "sec_rule": {"rules": []}, "zdepth": "0"}, {"__index__": 2, "minmax": {"__current_case__": 1, "minmax_select": "no"}, "minsize": "0.0", "orientation": "false", "plot_format": {"__current_case__": 6, "data_source": {"values": [{"id": 94521232, "src": "hda"}]}, "format_specific": {"fill_color": "#000000", "fill_color_alpha": "1.0", "layers": "15", "margin": "0.002", "overflow": {"__current_case__": 0, "overflow_behavior": "hide"}, "padding": "8.0", "stroke_color": "#000000", "stroke_color_alpha": "1.0", "stroke_thickness": "1", "thickness": "15.0"}, "plot_format_select": "tile"}, "r0": "0.6", "r1": "0.7", "sec_axes": {"axes": [], "only_if_data": "always"}, "sec_bkgs": {"backgrounds": [], "only_if_data": "always"}, "sec_rule": {"rules": []}, "zdepth": "0"}]} ` |
       | sec\_links | ` {"data": [{"__index__": 0, "advanced": {"bezier_radius_purity": "0.75", "crest": "0.5", "perturbation": {"__current_case__": 1, "perturb": "no"}}, "bezier_radius": "0.1", "color": "#000000", "color_alpha": "1.0", "data_source": {"values": [{"id": 94521233, "src": "hda"}]}, "linktype": {"__current_case__": 0, "pattern": "solid", "ribbon": "yes", "twist": ""}, "minsize": "0.0", "radius": "0.59", "sec_link_rule": {"rules": []}, "thickness": "15.0", "zdepth": "0"}]} ` |
       | scaling | ` {"zooms": []} ` |
       | ticks | ` {"radius": "1.0", "skip_first_label": "false", "skip_last_label": "false", "tick_group": [{"__index__": 0, "color": "#000000", "size": "10.0", "spacing": "1.0", "ticks": {"__current_case__": 1, "show_tick_labels": "no"}}, {"__index__": 1, "color": "#000000", "size": "10.0", "spacing": "5.0", "ticks": {"__current_case__": 0, "format": "%.1f", "format_ext": "true", "label_offset": "10.0", "label_size": "20.0", "show_tick_labels": "yes"}}]} ` |
       | limits | ` {"max_ideograms": "200", "max_links": "25000", "max_points_per_track": "25000", "max_ticks": "5000"} ` |
       | outputs | ` {"png": "true", "svg": "true", "tar": "false"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "fasta" ` |



  </div></details>


</details>

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/iuc/circos/circos/0.69.8+galaxy10

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 66.66666666666666%" aria-valuenow="2" aria-valuemin="0" aria-valuemax="3" data-toggle="tooltip" title="2 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="3" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 33.33333333333333%" aria-valuenow="1" aria-valuemin="0" aria-valuemax="3" title="1 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 3 |
| Passed     | 2 |
| Error      | 1 |
| Failure    | 0 |
| Skipped    | 0 |


<details><summary>Errored s</summary>

* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/iuc/circos/circos (Test #2)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Value ('1') must fulfill float('200') <= value <= float('inf'), Value ('1') must fulfill float('200') <= value <= float('inf'), Value ('1') must fulfill float('200') <= value <= float('inf'), Value ('1') must fulfill float('200') <= value <= float('inf')
      ```

  </div></details>


</details>
<details><summary>Passed s</summary>

* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/circos/circos (Test #1)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.

      ```
    **Standard Output:**

    * ```console
      debuggroup summary 0.33s welcome to circos v0.69-8 15 Jun 2019 on Perl 5.026002
      debuggroup summary 0.33s current working directory /corral4/main/jobs/041/424/41424095/working
      debuggroup summary 0.33s command /usr/local/bin/circos -conf circos/conf/circos.conf -noparanoid
      debuggroup summary 0.33s loading configuration from file circos/conf/circos.conf
      debuggroup summary 0.33s found conf file circos/conf/circos.conf
      debuggroup summary 0.68s debug will appear for these features: output,summary
      debuggroup summary 0.68s bitmap output image ./circos.png
      debuggroup summary 0.68s SVG output image ./circos.svg
      debuggroup summary 0.69s parsing karyotype and organizing ideograms
      debuggroup summary 0.74s karyotype has 2 chromosomes of total size 56,082
      debuggroup summary 0.75s applying global and local scaling
      debuggroup summary 0.75s allocating image, colors and brushes
      debuggroup summary 17.19s drawing 2 ideograms of total size 56,082
      debuggroup summary 17.19s drawing highlights and ideograms
      debuggroup output 17.20s generating output
      debuggroup output 17.98s created PNG image ./circos.png (40 kb)
      debuggroup output 17.99s created SVG image ./circos.svg (2 kb)

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | reference\_genome | ` {"ref": {"__current_case__": 2, "genome_fasta": {"values": [{"id": 94523883, "src": "hda"}]}, "ref_source": "history"}} ` |
       | ideogram | ` {"angle_offset": "-90", "angle_orientation": "clockwise", "bands": {"band_stroke_color": "#000000", "band_stroke_thickness": "0", "band_transparency": "3", "fill_bands": "true", "show_bands": "true"}, "chromosomes_reverse": null, "ideogram_labels": {"parallel": "true", "radius_offset": "0.075", "show_label": "true", "size": "24"}, "limit_chromosomes": null, "pairwise_spacing": [], "radius": "0.9", "spacing": "0.5", "thickness": "30.0", "units": "mb"} ` |
       | plot\_options | ` {"background": {"__current_case__": 1, "background_color": "#ffffff", "background_select": "color"}, "colour_profile": null, "radius": "1500"} ` |
       | sec\_tdd | ` {"data": []} ` |
       | sec\_links | ` {"data": []} ` |
       | scaling | ` {"zooms": []} ` |
       | ticks | ` {"radius": "1.0", "skip_first_label": "false", "skip_last_label": "false", "tick_group": []} ` |
       | limits | ` {"max_ideograms": "200", "max_links": "25000", "max_points_per_track": "25000", "max_ticks": "5000"} ` |
       | outputs | ` {"png": "true", "svg": "true", "tar": "false"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "fasta" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/circos/circos (Test #3)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.
      Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.
      Use of uninitialized value within %Circos::Error::GROUPERROR in uc at /usr/local/bin/../lib/Circos/Error.pm line 354, <F> line 21.
      Use of uninitialized value within %Circos::Error::GROUPERROR in uc at /usr/local/bin/../lib/Circos/Error.pm line 354, <F> line 21.
      Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781, <F> line 21.
      Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.
      Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.
      Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781, <F> line 1214.
      Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.
      Use of uninitialized value in subroutine entry at /usr/local/bin/../lib/Circos/Configuration.pm line 781.
      Use of uninitialized value within %Circos::Error::GROUPERROR in uc at /usr/local/bin/../lib/Circos/Error.pm line 354.

      ```
    **Standard Output:**

    * ```console
      debuggroup summary 0.35s welcome to circos v0.69-8 15 Jun 2019 on Perl 5.026002
      debuggroup summary 0.39s current working directory /corral4/main/jobs/041/424/41424096/working
      debuggroup summary 0.39s command /usr/local/bin/circos -conf circos/conf/circos.conf -noparanoid
      debuggroup summary 0.39s loading configuration from file circos/conf/circos.conf
      debuggroup summary 0.39s found conf file circos/conf/circos.conf
      debuggroup summary 0.74s debug will appear for these features: output,summary
      debuggroup summary 0.74s bitmap output image ./circos.png
      debuggroup summary 0.74s SVG output image ./circos.svg
      debuggroup summary 0.74s parsing karyotype and organizing ideograms
      debuggroup summary 0.74s karyotype has 2 chromosomes of total size 56,082
      debuggroup summary 0.75s applying global and local scaling
      debuggroup summary 0.75s allocating image, colors and brushes
      debuggroup summary 14.33s drawing 2 ideograms of total size 56,082
      debuggroup summary 14.33s drawing highlights and ideograms
      debuggroup summary 14.43s found conf file /usr/local/bin/../etc/tracks/link.conf
      debuggroup summary 14.43s process track_0 link circos/conf/../data/links-0.txt
      debuggroup summary 14.44s drawing link track_0 z 0
      debuggroup !circoswarning 14.53s  Data point of type [link] [50000-50500] extended past end of ideogram [ctgA 0-50001]. This data point will be [trimmed].
      debuggroup !circoswarning 14.53s  Data point of type [link] [51000-51500] extended past end of ideogram [ctgA 0-50001]. This data point will be [hidden].
      debuggroup summary 14.53s found conf file /usr/local/bin/../etc/tracks/histogram.conf
      debuggroup summary 14.55s found conf file /usr/local/bin/../etc/tracks/scatter.conf
      debuggroup summary 14.55s found conf file /usr/local/bin/../etc/tracks/tile.conf
      debuggroup summary 14.55s processing track_0 histogram circos/conf/../data/data-0.txt
      debuggroup summary 14.77s processing track_1 scatter circos/conf/../data/data-1.txt
      debuggroup summary 15.16s processing track_2 tile circos/conf/../data/data-2.txt
      debuggroup summary 15.22s drawing track_0 histogram z 0 data-0.txt orient out
      debuggroup summary 15.27s found conf file /usr/local/bin/../etc/tracks/axis.conf
      debuggroup summary 16.61s drawing track_1 scatter z 0 data-1.txt orient out
      debuggroup summary 16.66s found conf file /usr/local/bin/../etc/tracks/axis.conf
      debuggroup summary 17.03s drawing track_2 tile z 0 data-2.txt orient out
      debuggroup summary 17.04s found conf file /usr/local/bin/../etc/tracks/axis.conf
      debuggroup !circoswarning 17.40s  Data point of type [tile] [3013-6130] extended past end of ideogram [ctgB 0-6079]. This data point will be [trimmed].
      debuggroup output 17.40s generating output
      debuggroup output 18.18s created PNG image ./circos.png (539 kb)
      debuggroup output 18.18s created SVG image ./circos.svg (414 kb)

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | reference\_genome | ` {"ref": {"__current_case__": 2, "genome_fasta": {"values": [{"id": 94523883, "src": "hda"}]}, "ref_source": "history"}} ` |
       | ideogram | ` {"angle_offset": "-90", "angle_orientation": "clockwise", "bands": {"band_stroke_color": "#000000", "band_stroke_thickness": "0", "band_transparency": "3", "fill_bands": "true", "show_bands": "true"}, "chromosomes_reverse": null, "ideogram_labels": {"parallel": "true", "radius_offset": "0.075", "show_label": "true", "size": "24"}, "limit_chromosomes": null, "pairwise_spacing": [], "radius": "0.9", "spacing": "0.5", "thickness": "30.0", "units": "kb"} ` |
       | plot\_options | ` {"background": {"__current_case__": 1, "background_color": "#ffffff", "background_select": "color"}, "colour_profile": null, "radius": "1500"} ` |
       | sec\_tdd | ` {"data": [{"__index__": 0, "minmax": {"__current_case__": 1, "minmax_select": "no"}, "minsize": "0.0", "orientation": "false", "plot_format": {"__current_case__": 0, "data_source": {"values": [{"id": 94523887, "src": "hda"}]}, "format_specific": {"extend_bins": "false", "fill_color": "#ffdcfc", "fill_color_alpha": "1.0", "fill_under": "true", "stroke_color": "#000000", "stroke_color_alpha": "1.0", "stroke_thickness": "1"}, "plot_format_select": "histogram"}, "r0": "0.8", "r1": "0.9", "sec_axes": {"axes": [], "only_if_data": "always"}, "sec_bkgs": {"backgrounds": [], "only_if_data": "always"}, "sec_rule": {"rules": []}, "zdepth": "0"}, {"__index__": 1, "minmax": {"__current_case__": 1, "minmax_select": "no"}, "minsize": "0.0", "orientation": "false", "plot_format": {"__current_case__": 5, "data_source": {"values": [{"id": 94523887, "src": "hda"}]}, "format_specific": {"fill_color": "#555555", "fill_color_alpha": "1.0", "glyph": "circle", "glyph_size": "8", "stroke_color": "#000000", "stroke_color_alpha": "1.0", "stroke_thickness": "1"}, "plot_format_select": "scatter"}, "r0": "0.7", "r1": "0.8", "sec_axes": {"axes": [], "only_if_data": "always"}, "sec_bkgs": {"backgrounds": [], "only_if_data": "always"}, "sec_rule": {"rules": []}, "zdepth": "0"}, {"__index__": 2, "minmax": {"__current_case__": 1, "minmax_select": "no"}, "minsize": "0.0", "orientation": "false", "plot_format": {"__current_case__": 6, "data_source": {"values": [{"id": 94523888, "src": "hda"}]}, "format_specific": {"fill_color": "#000000", "fill_color_alpha": "1.0", "layers": "15", "margin": "0.002", "overflow": {"__current_case__": 0, "overflow_behavior": "hide"}, "padding": "8.0", "stroke_color": "#000000", "stroke_color_alpha": "1.0", "stroke_thickness": "1", "thickness": "15.0"}, "plot_format_select": "tile"}, "r0": "0.6", "r1": "0.7", "sec_axes": {"axes": [], "only_if_data": "always"}, "sec_bkgs": {"backgrounds": [], "only_if_data": "always"}, "sec_rule": {"rules": []}, "zdepth": "0"}]} ` |
       | sec\_links | ` {"data": [{"__index__": 0, "advanced": {"bezier_radius_purity": "0.75", "crest": "0.5", "perturbation": {"__current_case__": 1, "perturb": "no"}}, "bezier_radius": "0.1", "color": "#000000", "color_alpha": "1.0", "data_source": {"values": [{"id": 94523889, "src": "hda"}]}, "linktype": {"__current_case__": 0, "pattern": "solid", "ribbon": "yes", "twist": ""}, "minsize": "0.0", "radius": "0.59", "sec_link_rule": {"rules": []}, "thickness": "15.0", "zdepth": "0"}]} ` |
       | scaling | ` {"zooms": []} ` |
       | ticks | ` {"radius": "1.0", "skip_first_label": "false", "skip_last_label": "false", "tick_group": [{"__index__": 0, "color": "#000000", "size": "10.0", "spacing": "1.0", "ticks": {"__current_case__": 1, "show_tick_labels": "no"}}, {"__index__": 1, "color": "#000000", "size": "10.0", "spacing": "5.0", "ticks": {"__current_case__": 0, "format": "%.1f", "format_ext": "true", "label_offset": "10.0", "label_size": "20.0", "show_tick_labels": "yes"}}]} ` |
       | limits | ` {"max_ideograms": "200", "max_links": "25000", "max_points_per_track": "25000", "max_ticks": "5000"} ` |
       | outputs | ` {"png": "true", "svg": "true", "tar": "false"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "fasta" ` |



  </div></details>


</details>

**Comment by jennaj** [comment]
Closing -- it works at usegalaxy.org
