### ISSUE TITLE
Test taxonomy_krona_chart 2.7.1

### ISSUE THREAD

**Issue by jennaj** [mvdbeek/usegalaxy-tests#38]
https://github.com/galaxyproject/usegalaxy-playbook/issues/360

tool_id=toolshed.g2.bx.psu.edu/repos/crs4/taxonomy_krona_chart/taxonomy_krona_chart/2.7.1

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/crs4/taxonomy_krona_chart/taxonomy_krona_chart/2.7.1

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 50.0%" aria-valuenow="1" aria-valuemin="0" aria-valuemax="2" data-toggle="tooltip" title="1 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="2" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 50.0%" aria-valuenow="1" aria-valuemin="0" aria-valuemax="2" title="1 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 2 |
| Passed     | 1 |
| Error      | 0 |
| Failure    | 1 |
| Skipped    | 0 |


<details><summary>Failed s</summary>

* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/crs4/taxonomy_krona_chart/taxonomy_krona_chart (Test #1)</summary><div class="padded">

    **Problems**:
    * ```
      Output output:  different than expected, difference (using diff):
      ( /tmp/tmpe6j_x8ivkrona_test1.html v. /tmp/tmpfpnjpzx8krona_test1.html )
      --- local_file
      +++ history_data
      @@ -6621,77 +6621,18 @@
          </datasets>
       <node name="Root">
        <count><val>100</val></count>
      - <node name="Eukaryota">
      -  <rank><val>superkingdom</val></rank>
      -  <count><val>94</val></count>
      -  <node name="Metazoa">
      -   <rank><val>kingdom</val></rank>
      -   <count><val>94</val></count>
      -   <node name="Chordata">
      -    <rank><val>phylum</val></rank>
      -    <count><val>94</val></count>
      -    <node name="Craniata">
      -     <rank><val>subphylum</val></rank>
      -     <count><val>94</val></count>
      -     <node name="Gnathostomata">
      -      <rank><val>superclass</val></rank>
      -      <count><val>94</val></count>
      -      <node name="Mammalia">
      -       <rank><val>class</val></rank>
      -       <count><val>94</val></count>
      -       <node name="Euarchontoglires">
      ********
      *SNIP *
      ********
      +             <unassigned><val>2</val></unassigned>
      +             <count><val>94</val></count>
      +             <rank><val>genus</val></rank>
      +             <node name="Rattus norvegicus">
      +              <rank><val>species</val></rank>
      +              <members>
      +               <vals><val>IA_1-144417</val><val>IA_1-278966</val><val>IA_1-314709</val><val>IA_1-324951</val><val>IA_1-27817</val><val>IA_1-95255</val><val>IA_1-104173</val><val>IA_1-135979</val><val>IA_1-139090</val><val>IA_1-139090</val><val>IA_1-139090</val><val>IA_1-144996</val><val>IA_1-160446</val><val>IA_1-160446</val><val>IA_1-160446</val><val>IA_1-160446</val><val>IA_1-160446</val><val>IA_1-160446</val><val>IA_1-160446</val><val>IA_1-160446</val><val>IA_1-161439</val><val>IA_1-190855</val><val>IA_1-190855</val><val>IA_1-190855</val><val>IA_1-190855</val><val>IA_1-190855</val><val>IA_1-190855</val><val>IA_1-190855</val><val>IA_1-190855</val><val>IA_1-190855</val><val>IA_1-190855</val><val>IA_1-190855</val><val>IA_1-190855</val><val>IA_1-190855</val><val>IA_1-190855</val><val>IA_1-190855</val><val>IA_1-190855</val><val>IA_1-190855</val><val>IA_1-190855</val><val>IA_1-190855</val><val>IA_1-190855</val><val>IA_1-190855</val><val>IA_1-205154</val><val>IA_1-205154</val><val>IA_1-205154</val><val>IA_1-205154</val><val>IA_1-205154</val><val>IA_1-205154</val><val>IA_1-205154</val><val>IA_1-205154</val><val>IA_1-205154</val><val>IA_1-205154</val><val>IA_1-216231</val><val>IA_1-236286</val><val>IA_1-236286</val><val>IA_1-236286</val><val>IA_1-236286</val><val>IA_1-236286</val><val>IA_1-236286</val><val>IA_1-236286</val><val>IA_1-236286</val><val>IA_1-236286</val><val>IA_1-236286</val><val>IA_1-236286</val><val>IA_1-236286</val><val>IA_1-237681</val><val>IA_1-250166</val><val>IA_1-254274</val><val>IA_1-254274</val><val>IA_1-27817</val><val>IA_1-29000</val><val>IA_1-291427</val><val>IA_1-291427</val><val>IA_1-293054</val><val>IA_1-293054</val><val>IA_1-296315</val><val>IA_1-310974</val><val>IA_1-310974</val><val>IA_1-311282</val><val>IA_1-311282</val><val>IA_1-42600</val><val>IA_1-45102</val><val>IA_1-45102</val><val>IA_1-48105</val><val>IA_1-48105</val><val>IA_1-57254</val><val>IA_1-61975</val><val>IA_1-61975</val><val>IA_1-66943</val><val>IA_1-68288</val><val>IA_1-82334</val><val>IA_1-95526</val></vals>
      +              </members>
      +              <count><val>92</val></count>
      +             </node>
      +            </node>
      +           </node>
      +          </node>
      +         </node>
      +        </node>
      +       </node>
      +      </node>
      +     </node>
      +    </node>
      +   </node>
      +  </node>
      + </node>
       </node>
         </krona>
       </div></body></html>

      ```
    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Output:**

    * ```console
      Importing /corral4/main/objects/c/4/b/dataset_c4b1d78e-94da-4429-a952-9922f83d8535.dat...
      Writing /corral4/main/jobs/043/641/43641244/outputs/galaxy_dataset_a3cf03a9-8224-4d41-80a1-d796a3d47c77.dat...

      Importing /corral4/main/objects/c/4/b/dataset_c4b1d78e-94da-4429-a952-9922f83d8535.dat...
      Writing /corral4/main/jobs/043/641/43641244/outputs/galaxy_dataset_a3cf03a9-8224-4d41-80a1-d796a3d47c77.dat...

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | type\_of\_data | ` {"__current_case__": 0, "input": {"values": [{"id": 98655746, "src": "hda"}]}, "max_rank": "18", "type_of_data_selector": "taxonomy"} ` |
       | root\_name | ` "Root" ` |
       | combine\_inputs | ` "false" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "taxonomy" ` |



  </div></details>


</details>
<details><summary>Passed s</summary>

* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/crs4/taxonomy_krona_chart/taxonomy_krona_chart (Test #2)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Output:**

    * ```console
      Writing /corral4/main/jobs/043/641/43641246/outputs/galaxy_dataset_a226f8e2-f0e0-4f37-a28b-846961ed041e.dat...

      Writing /corral4/main/jobs/043/641/43641246/outputs/galaxy_dataset_a226f8e2-f0e0-4f37-a28b-846961ed041e.dat...

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | type\_of\_data | ` {"__current_case__": 1, "input": {"values": [{"id": 98655747, "src": "hda"}, {"id": 98655748, "src": "hda"}]}, "type_of_data_selector": "text"} ` |
       | root\_name | ` "Root" ` |
       | combine\_inputs | ` "false" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "tabular" ` |



  </div></details>


</details>

**Comment by jennaj** [comment]
https://github.com/galaxyproject/usegalaxy-playbook/issues/360#issuecomment-1149165038
