### ISSUE TITLE
Test taxonomy_krona_chart 2.7.1+galaxy0

### ISSUE THREAD

**Issue by jennaj** [mvdbeek/usegalaxy-tests#39]
https://github.com/galaxyproject/usegalaxy-playbook/issues/360

tool_id=toolshed.g2.bx.psu.edu/repos/crs4/taxonomy_krona_chart/taxonomy_krona_chart/2.7.1+galaxy0

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/crs4/taxonomy_krona_chart/taxonomy_krona_chart/2.7.1+galaxy0

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 100.0%" aria-valuenow="3" aria-valuemin="0" aria-valuemax="3" data-toggle="tooltip" title="3 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="3" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="3" title="0 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 3 |
| Passed     | 3 |
| Error      | 0 |
| Failure    | 0 |
| Skipped    | 0 |


<details><summary>Passed s</summary>

* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/crs4/taxonomy_krona_chart/taxonomy_krona_chart (Test #1)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Output:**

    * ```console
      Importing /corral4/main/objects/e/e/2/dataset_ee295979-d76e-4bb8-9f0b-8c0f5e0f2382.dat...
      Writing /corral4/main/jobs/043/641/43641272/outputs/galaxy_dataset_29defae1-fb3a-4a02-9f46-e66af5e6c15a.dat...

      Importing /corral4/main/objects/e/e/2/dataset_ee295979-d76e-4bb8-9f0b-8c0f5e0f2382.dat...
      Writing /corral4/main/jobs/043/641/43641272/outputs/galaxy_dataset_29defae1-fb3a-4a02-9f46-e66af5e6c15a.dat...

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | type\_of\_data | ` {"__current_case__": 0, "input": {"values": [{"id": 98655773, "src": "hda"}]}, "max_rank": "18", "type_of_data_selector": "taxonomy"} ` |
       | root\_name | ` "Root" ` |
       | combine\_inputs | ` "false" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "taxonomy" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/crs4/taxonomy_krona_chart/taxonomy_krona_chart (Test #2)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Output:**

    * ```console
      Importing /corral4/main/objects/e/e/2/dataset_ee295979-d76e-4bb8-9f0b-8c0f5e0f2382.dat...
      Importing /corral4/main/objects/0/6/c/dataset_06cec197-d889-4324-a166-5666c4c5f818.dat...
      Writing /corral4/main/jobs/043/641/43641275/outputs/galaxy_dataset_fd18a99f-89ae-4985-bf81-89de74aaedfc.dat...

      Importing /corral4/main/objects/e/e/2/dataset_ee295979-d76e-4bb8-9f0b-8c0f5e0f2382.dat...
      Importing /corral4/main/objects/0/6/c/dataset_06cec197-d889-4324-a166-5666c4c5f818.dat...
      Writing /corral4/main/jobs/043/641/43641275/outputs/galaxy_dataset_fd18a99f-89ae-4985-bf81-89de74aaedfc.dat...

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | type\_of\_data | ` {"__current_case__": 0, "input": {"values": [{"id": 98655773, "src": "hda"}, {"id": 98655776, "src": "hda"}]}, "max_rank": "18", "type_of_data_selector": "taxonomy"} ` |
       | root\_name | ` "Root" ` |
       | combine\_inputs | ` "false" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "taxonomy" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/crs4/taxonomy_krona_chart/taxonomy_krona_chart (Test #3)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Output:**

    * ```console
      Writing /corral4/main/jobs/043/641/43641274/outputs/galaxy_dataset_9977f2e1-896f-448d-92eb-8a20b660953c.dat...

      Writing /corral4/main/jobs/043/641/43641274/outputs/galaxy_dataset_9977f2e1-896f-448d-92eb-8a20b660953c.dat...

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | type\_of\_data | ` {"__current_case__": 1, "input": {"values": [{"id": 98655774, "src": "hda"}, {"id": 98655777, "src": "hda"}]}, "type_of_data_selector": "text"} ` |
       | root\_name | ` "Root" ` |
       | combine\_inputs | ` "false" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "tabular" ` |



  </div></details>


</details>
