### ISSUE TITLE
Test roary 3.13.0+galaxy2

### ISSUE THREAD

**Issue by natefoo** [mvdbeek/usegalaxy-tests#4]
For galaxyproject/usegalaxy-tools#445

**Comment by natefoo** [comment]
/run-tool-test toolshed.g2.bx.psu.edu/repos/iuc/roary/roary/3.13.0+galaxy2

**Comment by natefoo** [comment]
/run-tool-test toolshed.g2.bx.psu.edu/repos/iuc/roary/roary/3.13.0+galaxy2

Failed to comment back the failure because there were no tests results because it couldn't find the tool - restarted Main so it should find it now...

**Comment by natefoo** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/iuc/roary/roary/3.13.0+galaxy2

Helps if you use the command correctly.

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 100.0%" aria-valuenow="2" aria-valuemin="0" aria-valuemax="2" data-toggle="tooltip" title="2 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="2" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="2" title="0 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 2 |
| Passed     | 2 |
| Error      | 0 |
| Failure    | 0 |
| Skipped    | 0 |


<details><summary>Passed s</summary>

* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/roary/roary (Test #1)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      Use of uninitialized value in require at /usr/local/lib/site_perl/5.26.2/x86_64-linux-thread-multi/Encode.pm line 61.
      Use of uninitialized value in require at /usr/local/lib/site_perl/5.26.2/x86_64-linux-thread-multi/Encode.pm line 61.
      Use of uninitialized value in require at (eval 709) line 1.
      Illegal division by zero at /usr/local/lib/site_perl/5.26.2/Bio/Roary/External/GeneAlignmentFromNucleotides.pm line 46.

      ```
    **Standard Output:**

    * ```console
      
      Please cite Roary if you use any of the results it produces:
          Andrew J. Page, Carla A. Cummins, Martin Hunt, Vanessa K. Wong, Sandra Reuter, Matthew T. G. Holden, Maria Fookes, Daniel Falush, Jacqueline A. Keane, Julian Parkhill,
      	"Roary: Rapid large-scale prokaryote pan genome analysis", Bioinformatics, 2015 Nov 15;31(22):3691-3693
          doi: http://doi.org/10.1093/bioinformatics/btv421
      	Pubmed: 26198102


      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | gff\_input | ` {"__current_case__": 0, "gff_input_selector": "individual", "gffs": {"values": [{"id": 82061722, "src": "hda"}, {"id": 82061724, "src": "hda"}]}} ` |
       | percent\_ident | ` "95" ` |
       | core\_diff | ` "99.0" ` |
       | outputs | ` None ` |
       | advanced | ` {"maxclust": "50000", "mcl": "1.5", "split_para": "false", "trans_tab": "11"} ` |
       | \_\_job\_resource | ` {"__current_case__": 0, "__job_resource__select": "no"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "gff3" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/roary/roary (Test #2)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      Use of uninitialized value in require at /usr/local/lib/site_perl/5.26.2/x86_64-linux-thread-multi/Encode.pm line 61.
      Use of uninitialized value in require at /usr/local/lib/site_perl/5.26.2/x86_64-linux-thread-multi/Encode.pm line 61.
      Use of uninitialized value in require at (eval 709) line 1.
      Illegal division by zero at /usr/local/lib/site_perl/5.26.2/Bio/Roary/External/GeneAlignmentFromNucleotides.pm line 46.

      ```
    **Standard Output:**

    * ```console
      
      Please cite Roary if you use any of the results it produces:
          Andrew J. Page, Carla A. Cummins, Martin Hunt, Vanessa K. Wong, Sandra Reuter, Matthew T. G. Holden, Maria Fookes, Daniel Falush, Jacqueline A. Keane, Julian Parkhill,
      	"Roary: Rapid large-scale prokaryote pan genome analysis", Bioinformatics, 2015 Nov 15;31(22):3691-3693
          doi: http://doi.org/10.1093/bioinformatics/btv421
      	Pubmed: 26198102


      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | gff\_input | ` {"__current_case__": 0, "gff_input_selector": "individual", "gffs": {"values": [{"id": 82061722, "src": "hda"}, {"id": 82061724, "src": "hda"}]}} ` |
       | percent\_ident | ` "50" ` |
       | core\_diff | ` "50.0" ` |
       | outputs | ` None ` |
       | advanced | ` {"maxclust": "50000", "mcl": "1.5", "split_para": "false", "trans_tab": "11"} ` |
       | \_\_job\_resource | ` {"__current_case__": 0, "__job_resource__select": "no"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "gff3" ` |



  </div></details>


</details>

**Comment by natefoo** [comment]
@mvdbeek might want to escape those # in the expanded "Passed" results. :smile:
