### ISSUE TITLE
Test krona-text 1

### ISSUE THREAD

**Issue by jennaj** [mvdbeek/usegalaxy-tests#40]
https://github.com/galaxyproject/usegalaxy-playbook/issues/360

tool_id=toolshed.g2.bx.psu.edu/repos/saskia-hiltemann/krona_text/krona-text/1

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/saskia-hiltemann/krona_text/krona-text/1

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary


|  State | Count |
| ---------- | ----- |
| Total      | 0 |
| Passed     | 0 |
| Error      | 0 |
| Failure    | 0 |
| Skipped    | 0 |

**Comment by jennaj** [comment]
Ah, no tool test for this one
