### ISSUE TITLE
Test Kraken2Tax 1.2

### ISSUE THREAD

**Issue by jennaj** [mvdbeek/usegalaxy-tests#43]
https://github.com/galaxyproject/usegalaxy-playbook/issues/360

tool_id=toolshed.g2.bx.psu.edu/repos/devteam/kraken2tax/Kraken2Tax/1.2

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/devteam/kraken2tax/Kraken2Tax/1.2

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 100.0%" aria-valuenow="1" aria-valuemin="0" aria-valuemax="1" data-toggle="tooltip" title="1 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="1" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="1" title="0 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 1 |
| Passed     | 1 |
| Error      | 0 |
| Failure    | 0 |
| Skipped    | 0 |


<details><summary>Passed s</summary>

* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/devteam/kraken2tax/Kraken2Tax (Test #1)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | ncbi\_taxonomy | ` "ncbi-2015-10-05" ` |
       | read\_name | ` "2" ` |
       | tax\_id | ` 22bf8e63d7997a13 ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "tabular" ` |



  </div></details>


</details>
