### ISSUE TITLE
test rna_starsolo 2.7.8a

### ISSUE THREAD

**Issue by jennaj** [mvdbeek/usegalaxy-tests#45]
Test for one weird error reported to bugs. 

toolshed.g2.bx.psu.edu/repos/iuc/rna_starsolo/rna_starsolo/2.7.8a

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/iuc/rna_starsolo/rna_starsolo/2.7.8a

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 75.0%" aria-valuenow="6" aria-valuemin="0" aria-valuemax="8" data-toggle="tooltip" title="6 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="8" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 25.0%" aria-valuenow="2" aria-valuemin="0" aria-valuemax="8" title="2 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 8 |
| Passed     | 6 |
| Error      | 2 |
| Failure    | 0 |
| Skipped    | 0 |


<details><summary>Errored s</summary>

* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/iuc/rna_starsolo/rna_starsolo (Test #4)</summary><div class="padded">

    **Execution Problem:**
    * ```
      'id'
      ```

  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/iuc/rna_starsolo/rna_starsolo (Test #8)</summary><div class="padded">

    **Execution Problem:**
    * ```
      'id'
      ```

  </div></details>


</details>
<details><summary>Passed s</summary>

* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/rna_starsolo/rna_starsolo (Test #1)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      [bam_sort_core] merging from 0 files and 9 in-memory blocks...

      ```
    **Standard Output:**

    * ```console
      Jun 24 23:28:30 ..... started STAR run
      Jun 24 23:28:33 ... starting to generate Genome files
      Jun 24 23:28:34 ..... processing annotations GTF
      Jun 24 23:28:52 ... starting to sort Suffix Array. This may take a long time...
      Jun 24 23:28:53 ... sorting Suffix Array chunks and saving them to disk...
      Jun 24 23:29:03 ... loading chunks from disk, packing SA...
      Jun 24 23:29:15 ... finished generating suffix array
      Jun 24 23:29:16 ... generating Suffix Array index
      Jun 24 23:29:16 ... completed Suffix Array index
      Jun 24 23:29:19 ..... inserting junctions into the genome indices
      Jun 24 23:29:20 ... writing Genome to disk ...
      Jun 24 23:29:22 ... writing Suffix Array to disk ...
      Jun 24 23:29:25 ... writing SAindex to disk
      Jun 24 23:29:26 ..... finished successfully
      Jun 24 23:29:32 ..... started STAR run
      Jun 24 23:29:51 ..... loading genome
      Jun 24 23:29:59 ..... started mapping
      Jun 24 23:30:46 ..... finished mapping
      Jun 24 23:30:50 ..... started Solo counting
      Jun 24 23:31:03 ..... finished Solo counting
      Jun 24 23:31:03 ..... finished successfully

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | refGenomeSource | ` {"__current_case__": 1, "geneSource": "history", "genomeFastaFiles": {"values": [{"id": 99483508, "src": "hda"}]}, "genomeSAindexNbases": "4", "sjdbGTFfile": {"values": [{"id": 99483360, "src": "hda"}]}, "sjdbOverhang": "100"} ` |
       | sc | ` {"__current_case__": 0, "input_types": {"__current_case__": 0, "input1": {"values": [{"id": 99483368, "src": "hda"}]}, "input2": {"values": [{"id": 99483377, "src": "hda"}]}, "use": "repeat"}, "params": {"__current_case__": 1, "chemistry": "CR3"}, "soloBarcodeReadLength": "true", "soloCBmatchWLtype": "1MM_multi", "soloCBwhitelist": {"values": [{"id": 99483385, "src": "hda"}]}, "soloUMIdedup": "1MM_All", "solo_type": "CB_UMI_Simple"} ` |
       | solo | ` {"filter": {"__current_case__": 3, "filter_type": "no_filter"}, "soloFeatures": "Gene", "soloOutFormatFeaturesGeneField3": "Gene Expression", "soloStrand": "Forward", "soloUMIfiltering": "-"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/rna_starsolo/rna_starsolo (Test #2)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      [bam_sort_core] merging from 0 files and 9 in-memory blocks...

      ```
    **Standard Output:**

    * ```console
      Jun 24 23:28:34 ..... started STAR run
      Jun 24 23:28:37 ... starting to generate Genome files
      Jun 24 23:28:40 ..... processing annotations GTF
      Jun 24 23:28:56 ... starting to sort Suffix Array. This may take a long time...
      Jun 24 23:28:57 ... sorting Suffix Array chunks and saving them to disk...
      Jun 24 23:29:08 ... loading chunks from disk, packing SA...
      Jun 24 23:29:20 ... finished generating suffix array
      Jun 24 23:29:20 ... generating Suffix Array index
      Jun 24 23:29:20 ... completed Suffix Array index
      Jun 24 23:29:23 ..... inserting junctions into the genome indices
      Jun 24 23:29:24 ... writing Genome to disk ...
      Jun 24 23:29:26 ... writing Suffix Array to disk ...
      Jun 24 23:29:33 ... writing SAindex to disk
      Jun 24 23:29:35 ..... finished successfully
      Jun 24 23:29:38 ..... started STAR run
      Jun 24 23:29:59 ..... loading genome
      Jun 24 23:30:09 ..... started mapping
      Jun 24 23:30:56 ..... finished mapping
      Jun 24 23:31:03 ..... started Solo counting
      Jun 24 23:31:24 ..... finished Solo counting
      Jun 24 23:31:25 ..... finished successfully

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | refGenomeSource | ` {"__current_case__": 1, "geneSource": "history", "genomeFastaFiles": {"values": [{"id": 99483508, "src": "hda"}]}, "genomeSAindexNbases": "4", "sjdbGTFfile": {"values": [{"id": 99483360, "src": "hda"}]}, "sjdbOverhang": "100"} ` |
       | sc | ` {"__current_case__": 0, "input_types": {"__current_case__": 0, "input1": {"values": [{"id": 99483368, "src": "hda"}]}, "input2": {"values": [{"id": 99483377, "src": "hda"}]}, "use": "repeat"}, "params": {"__current_case__": 2, "bccdna_mate": {"__current_case__": 0, "bc_location": "other_mate"}, "chemistry": "custom", "clipAdapterType": "Hamming", "soloAdapterMismatchesNmax": "1", "soloAdapterSequence": "-", "soloCBlen": "16", "soloCBstart": "1", "soloUMIlen": "12", "soloUMIstart": "17"}, "soloBarcodeReadLength": "true", "soloCBmatchWLtype": "1MM_multi", "soloCBwhitelist": {"values": [{"id": 99483385, "src": "hda"}]}, "soloUMIdedup": "1MM_All", "solo_type": "CB_UMI_Simple"} ` |
       | solo | ` {"filter": {"__current_case__": 0, "filter_type": "cellranger2", "max_min_ratio": "10.0", "max_perc": "0.99", "n_expected": "3000"}, "soloFeatures": "Gene", "soloOutFormatFeaturesGeneField3": "Gene Expression", "soloStrand": "Forward", "soloUMIfiltering": "-"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/rna_starsolo/rna_starsolo (Test #3)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      [bam_sort_core] merging from 0 files and 7 in-memory blocks...

      ```
    **Standard Output:**

    * ```console
      Jun 24 23:22:52 ..... started STAR run
      Jun 24 23:22:52 ... starting to generate Genome files
      Jun 24 23:22:52 ..... processing annotations GTF
      Jun 24 23:22:52 ... starting to sort Suffix Array. This may take a long time...
      Jun 24 23:22:52 ... sorting Suffix Array chunks and saving them to disk...
      Jun 24 23:22:52 ... loading chunks from disk, packing SA...
      Jun 24 23:22:52 ... finished generating suffix array
      Jun 24 23:22:52 ... generating Suffix Array index
      Jun 24 23:22:52 ... completed Suffix Array index
      Jun 24 23:22:52 ..... inserting junctions into the genome indices
      Jun 24 23:22:52 ... writing Genome to disk ...
      Jun 24 23:22:52 ... writing Suffix Array to disk ...
      Jun 24 23:22:52 ... writing SAindex to disk
      Jun 24 23:22:52 ..... finished successfully
      Jun 24 23:22:52 ..... started STAR run
      Jun 24 23:22:52 ..... loading genome
      Jun 24 23:22:52 ..... started mapping
      Jun 24 23:23:46 ..... finished mapping
      Jun 24 23:23:46 ..... started Solo counting
      Jun 24 23:23:46 ..... finished Solo counting
      Jun 24 23:23:46 ..... finished successfully

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | refGenomeSource | ` {"__current_case__": 1, "geneSource": "history", "genomeFastaFiles": {"values": [{"id": 99483508, "src": "hda"}]}, "genomeSAindexNbases": "4", "sjdbGTFfile": {"values": [{"id": 99483360, "src": "hda"}]}, "sjdbOverhang": "100"} ` |
       | sc | ` {"__current_case__": 0, "input_types": {"__current_case__": 0, "input1": {"values": [{"id": 99483368, "src": "hda"}, {"id": 99483368, "src": "hda"}, {"id": 99483368, "src": "hda"}]}, "input2": {"values": [{"id": 99483377, "src": "hda"}, {"id": 99483377, "src": "hda"}, {"id": 99483377, "src": "hda"}]}, "use": "repeat"}, "params": {"__current_case__": 1, "chemistry": "CR3"}, "soloBarcodeReadLength": "true", "soloCBmatchWLtype": "1MM_multi", "soloCBwhitelist": {"values": [{"id": 99483385, "src": "hda"}]}, "soloUMIdedup": "1MM_All", "solo_type": "CB_UMI_Simple"} ` |
       | solo | ` {"filter": {"__current_case__": 0, "filter_type": "cellranger2", "max_min_ratio": "10.0", "max_perc": "0.99", "n_expected": "3000"}, "soloFeatures": "Gene", "soloOutFormatFeaturesGeneField3": "Gene Expression", "soloStrand": "Forward", "soloUMIfiltering": "-"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/rna_starsolo/rna_starsolo (Test #5)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      [bam_sort_core] merging from 0 files and 7 in-memory blocks...

      ```
    **Standard Output:**

    * ```console
      Jun 24 23:22:52 ..... started STAR run
      Jun 24 23:22:52 ... starting to generate Genome files
      Jun 24 23:22:52 ..... processing annotations GTF
      Jun 24 23:22:52 ... starting to sort Suffix Array. This may take a long time...
      Jun 24 23:22:52 ... sorting Suffix Array chunks and saving them to disk...
      Jun 24 23:22:52 ... loading chunks from disk, packing SA...
      Jun 24 23:22:52 ... finished generating suffix array
      Jun 24 23:22:52 ... generating Suffix Array index
      Jun 24 23:22:52 ... completed Suffix Array index
      Jun 24 23:22:52 ..... inserting junctions into the genome indices
      Jun 24 23:22:52 ... writing Genome to disk ...
      Jun 24 23:22:52 ... writing Suffix Array to disk ...
      Jun 24 23:22:52 ... writing SAindex to disk
      Jun 24 23:22:52 ..... finished successfully
      Jun 24 23:22:52 ..... started STAR run
      Jun 24 23:22:52 ..... loading genome
      Jun 24 23:22:52 ..... started mapping
      Jun 24 23:23:10 ..... finished mapping
      Jun 24 23:23:10 ..... started Solo counting
      Jun 24 23:23:10 ..... finished Solo counting
      Jun 24 23:23:10 ..... finished successfully

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | refGenomeSource | ` {"__current_case__": 1, "geneSource": "history", "genomeFastaFiles": {"values": [{"id": 99483508, "src": "hda"}]}, "genomeSAindexNbases": "4", "sjdbGTFfile": {"values": [{"id": 99483360, "src": "hda"}]}, "sjdbOverhang": "100"} ` |
       | sc | ` {"__current_case__": 0, "input_types": {"__current_case__": 0, "input1": {"values": [{"id": 99483368, "src": "hda"}]}, "input2": {"values": [{"id": 99483377, "src": "hda"}]}, "use": "repeat"}, "params": {"__current_case__": 1, "chemistry": "CR3"}, "soloBarcodeReadLength": "true", "soloCBmatchWLtype": "1MM_multi_pseudocounts", "soloCBwhitelist": {"values": [{"id": 99483385, "src": "hda"}]}, "soloUMIdedup": "1MM_All", "solo_type": "CB_UMI_Simple"} ` |
       | solo | ` {"filter": {"__current_case__": 2, "filter_type": "topcells", "n_cells": "5"}, "soloFeatures": "GeneFull", "soloOutFormatFeaturesGeneField3": "Dummy Text", "soloStrand": "Forward", "soloUMIfiltering": "MultiGeneUMI"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/rna_starsolo/rna_starsolo (Test #6)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      [bam_sort_core] merging from 0 files and 9 in-memory blocks...

      ```
    **Standard Output:**

    * ```console
      Jun 24 23:28:31 ..... started STAR run
      Jun 24 23:28:35 ... starting to generate Genome files
      Jun 24 23:28:35 ..... processing annotations GTF
      Jun 24 23:28:53 ... starting to sort Suffix Array. This may take a long time...
      Jun 24 23:28:53 ... sorting Suffix Array chunks and saving them to disk...
      Jun 24 23:29:02 ... loading chunks from disk, packing SA...
      Jun 24 23:29:15 ... finished generating suffix array
      Jun 24 23:29:15 ... generating Suffix Array index
      Jun 24 23:29:15 ... completed Suffix Array index
      Jun 24 23:29:18 ..... inserting junctions into the genome indices
      Jun 24 23:29:20 ... writing Genome to disk ...
      Jun 24 23:29:21 ... writing Suffix Array to disk ...
      Jun 24 23:29:24 ... writing SAindex to disk
      Jun 24 23:29:25 ..... finished successfully
      Jun 24 23:29:27 ..... started STAR run
      Jun 24 23:29:50 ..... loading genome
      Jun 24 23:29:59 ..... started mapping
      Jun 24 23:30:46 ..... finished mapping
      Jun 24 23:30:50 ..... started Solo counting
      Jun 24 23:31:10 ..... finished Solo counting
      Jun 24 23:31:11 ..... finished successfully

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | solo | ` {"filter": {"FDR": "0.01", "__current_case__": 1, "candMaxN": "20000", "filter_type": "emptydrops", "indMax": "90000", "indMin": "45000", "maxMinRatio": "10.0", "maxPercentile": "0.99", "nExpectedCells": "5", "simN": "10000", "umiMin": "500", "umiMinFracMedian": "0.01"}, "soloFeatures": "Gene", "soloOutFormatFeaturesGeneField3": "Gene Expression", "soloStrand": "Forward", "soloUMIfiltering": "-"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |
       | refGenomeSource | ` {"__current_case__": 1, "geneSource": "history", "genomeFastaFiles": {"values": [{"id": 99483508, "src": "hda"}]}, "genomeSAindexNbases": "4", "sjdbGTFfile": {"values": [{"id": 99483360, "src": "hda"}]}, "sjdbOverhang": "100"} ` |
       | sc | ` {"__current_case__": 0, "input_types": {"__current_case__": 0, "input1": {"values": [{"id": 99483368, "src": "hda"}]}, "input2": {"values": [{"id": 99483377, "src": "hda"}]}, "use": "repeat"}, "params": {"__current_case__": 1, "chemistry": "CR3"}, "soloBarcodeReadLength": "true", "soloCBmatchWLtype": "1MM_multi", "soloCBwhitelist": {"values": [{"id": 99483385, "src": "hda"}]}, "soloUMIdedup": "1MM_All", "solo_type": "CB_UMI_Simple"} ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/rna_starsolo/rna_starsolo (Test #7)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      [bam_sort_core] merging from 0 files and 7 in-memory blocks...

      ```
    **Standard Output:**

    * ```console
      Jun 24 23:24:50 ..... started STAR run
      Jun 24 23:24:50 ... starting to generate Genome files
      Jun 24 23:24:50 ..... processing annotations GTF
      Jun 24 23:24:50 ... starting to sort Suffix Array. This may take a long time...
      Jun 24 23:24:50 ... sorting Suffix Array chunks and saving them to disk...
      Jun 24 23:24:50 ... loading chunks from disk, packing SA...
      Jun 24 23:24:50 ... finished generating suffix array
      Jun 24 23:24:50 ... generating Suffix Array index
      Jun 24 23:24:50 ... completed Suffix Array index
      Jun 24 23:24:50 ..... inserting junctions into the genome indices
      Jun 24 23:24:50 ... writing Genome to disk ...
      Jun 24 23:24:50 ... writing Suffix Array to disk ...
      Jun 24 23:24:50 ... writing SAindex to disk
      Jun 24 23:24:50 ..... finished successfully
      Jun 24 23:24:50 ..... started STAR run
      Jun 24 23:24:50 ..... loading genome
      Jun 24 23:24:50 ..... started mapping
      Jun 24 23:24:50 ..... finished mapping
      Jun 24 23:24:50 ..... started Solo counting
      Jun 24 23:24:51 ..... finished Solo counting
      Jun 24 23:24:51 ..... finished successfully

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | refGenomeSource | ` {"__current_case__": 1, "geneSource": "history", "genomeFastaFiles": {"values": [{"id": 99483508, "src": "hda"}]}, "genomeSAindexNbases": "4", "sjdbGTFfile": {"values": [{"id": 99483360, "src": "hda"}]}, "sjdbOverhang": "100"} ` |
       | sc | ` {"__current_case__": 1, "cb_whitelists": [{"__index__": 0, "cb_end_anchor": "2", "cb_end_anchor_pos": "-1", "cb_start_anchor": "0", "cb_start_anchor_pos": "0", "whitelist_file": {"values": [{"id": 99483376, "src": "hda"}]}}, {"__index__": 1, "cb_end_anchor": "3", "cb_end_anchor_pos": "8", "cb_start_anchor": "3", "cb_start_anchor_pos": "1", "whitelist_file": {"values": [{"id": 99483386, "src": "hda"}]}}], "clipAdapterType": "CellRanger4", "input_types": {"__current_case__": 0, "input1": {"values": [{"id": 99483362, "src": "hda"}]}, "input2": {"values": [{"id": 99483370, "src": "hda"}]}, "use": "repeat"}, "soloAdapterMismatchesNmax": "1", "soloAdapterSequence": "GAGTGATTGCTTGTGACGCCTT", "soloCBmatchWLtype": "1MM", "soloUMIdedup": "1MM_All", "solo_type": "CB_UMI_Complex", "umi_end_anchor": "3", "umi_end_anchor_pos": "14", "umi_start_anchor": "3", "umi_start_anchor_pos": "9"} ` |
       | solo | ` {"filter": {"__current_case__": 0, "filter_type": "cellranger2", "max_min_ratio": "10.0", "max_perc": "0.99", "n_expected": "3000"}, "soloFeatures": "Gene", "soloOutFormatFeaturesGeneField3": "Gene Expression", "soloStrand": "Forward", "soloUMIfiltering": "-"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


</details>

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/iuc/rna_starsolo/rna_starsolo/2.7.8a

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="8" data-toggle="tooltip" title="0 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="8" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 100.0%" aria-valuenow="8" aria-valuemin="0" aria-valuemax="8" title="8 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 8 |
| Passed     | 0 |
| Error      | 8 |
| Failure    | 0 |
| Skipped    | 0 |


<details><summary>Errored s</summary>

* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/iuc/rna_starsolo/rna_starsolo (Test #1)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Expecting value: line 1 column 1 (char 0)
      ```

  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/iuc/rna_starsolo/rna_starsolo (Test #2)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Expecting value: line 1 column 1 (char 0)
      ```

  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/iuc/rna_starsolo/rna_starsolo (Test #3)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Expecting value: line 1 column 1 (char 0)
      ```

  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/iuc/rna_starsolo/rna_starsolo (Test #4)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Expecting value: line 1 column 1 (char 0)
      ```

  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/iuc/rna_starsolo/rna_starsolo (Test #5)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Expecting value: line 1 column 1 (char 0)
      ```

  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/iuc/rna_starsolo/rna_starsolo (Test #6)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Expecting value: line 1 column 1 (char 0)
      ```

  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/iuc/rna_starsolo/rna_starsolo (Test #7)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Expecting value: line 1 column 1 (char 0)
      ```

  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/iuc/rna_starsolo/rna_starsolo (Test #8)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Expecting value: line 1 column 1 (char 0)
      ```

  </div></details>


</details>
