### ISSUE TITLE
test cshl_fastx_barcode_splitter 1.0.1

### ISSUE THREAD

**Issue by jennaj** [mvdbeek/usegalaxy-tests#50]
Reported error:

> /corral4/main/jobs/044/595/44595944/tool_script.sh: line 22: bzcat: command not found
> Use of uninitialized value $first_char in ord at /cvmfs/main.galaxyproject.org/shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/fastx_barcode_splitter/015dc921d814/fastx

toolshed.g2.bx.psu.edu/repos/devteam/fastx_barcode_splitter/cshl_fastx_barcode_splitter/1.0.1

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/devteam/fastx_barcode_splitter/cshl_fastx_barcode_splitter/1.0.1

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 100.0%" aria-valuenow="3" aria-valuemin="0" aria-valuemax="3" data-toggle="tooltip" title="3 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="3" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="3" title="0 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 3 |
| Passed     | 3 |
| Error      | 0 |
| Failure    | 0 |
| Skipped    | 0 |


<details><summary>Passed s</summary>

* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/devteam/fastx_barcode_splitter/cshl_fastx_barcode_splitter (Test #1)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | refBarcodeLocation | ` {"EOL": "--bol", "__current_case__": 0, "barcodeLocation": "bol"} ` |
       | mismatches | ` "2" ` |
       | partial | ` "0" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "tabular" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/devteam/fastx_barcode_splitter/cshl_fastx_barcode_splitter (Test #2)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | refBarcodeLocation | ` {"EOL": "--bol", "__current_case__": 0, "barcodeLocation": "bol"} ` |
       | mismatches | ` "2" ` |
       | partial | ` "0" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "tabular" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/devteam/fastx_barcode_splitter/cshl_fastx_barcode_splitter (Test #3)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | refBarcodeLocation | ` {"__current_case__": 2, "barcodeLocation": "idxfile", "idxfile": {"values": [{"id": 100403034, "src": "hda"}]}, "idxidstrip": "1"} ` |
       | mismatches | ` "2" ` |
       | partial | ` "0" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "tabular" ` |



  </div></details>


</details>

**Comment by jennaj** [comment]
Ticket: https://github.com/galaxyproject/usegalaxy-tools/issues/533

The tool cannot use bz2 inputs due to a missing dependency at `org`. Works fine at `eu`. The tool tests don't include a bz2 input so was missed.
