### ISSUE TITLE
Test ncbi_makeblastdb 2.10.1+galaxy2 2.10.1+galaxy1 2.10.1+galaxy0

### ISSUE THREAD

**Issue by jennaj** [mvdbeek/usegalaxy-tests#52]
toolshed.g2.bx.psu.edu/repos/devteam/ncbi_blast_plus/ncbi_makeblastdb/2.10.1+galaxy2
toolshed.g2.bx.psu.edu/repos/devteam/ncbi_blast_plus/ncbi_makeblastdb/2.10.1+galaxy1
toolshed.g2.bx.psu.edu/repos/devteam/ncbi_blast_plus/ncbi_makeblastdb/2.10.1+galaxy0

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/devteam/ncbi_blast_plus/ncbi_makeblastdb/2.10.1+galaxy2

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="4" data-toggle="tooltip" title="0 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="4" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 100.0%" aria-valuenow="4" aria-valuemin="0" aria-valuemax="4" title="4 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 4 |
| Passed     | 0 |
| Error      | 4 |
| Failure    | 0 |
| Skipped    | 0 |


<details><summary>Errored s</summary>

* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/devteam/ncbi_blast_plus/ncbi_makeblastdb (Test #1)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Test input file (four_human_proteins.fasta) cannot be found.
      ```

  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/devteam/ncbi_blast_plus/ncbi_makeblastdb (Test #2)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Test input file (four_human_proteins.fasta) cannot be found.
      ```

  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/devteam/ncbi_blast_plus/ncbi_makeblastdb (Test #3)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Test input file (four_human_proteins.fasta) cannot be found.
      ```

  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/devteam/ncbi_blast_plus/ncbi_makeblastdb (Test #4)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Test input file (three_human_mRNA.fasta.gz) cannot be found.
      ```

  </div></details>


</details>

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/devteam/ncbi_blast_plus/ncbi_makeblastdb/2.10.1+galaxy1

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="4" data-toggle="tooltip" title="0 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="4" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 100.0%" aria-valuenow="4" aria-valuemin="0" aria-valuemax="4" title="4 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 4 |
| Passed     | 0 |
| Error      | 4 |
| Failure    | 0 |
| Skipped    | 0 |


<details><summary>Errored s</summary>

* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/devteam/ncbi_blast_plus/ncbi_makeblastdb (Test #1)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Test input file (four_human_proteins.fasta) cannot be found.
      ```

  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/devteam/ncbi_blast_plus/ncbi_makeblastdb (Test #2)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Test input file (four_human_proteins.fasta) cannot be found.
      ```

  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/devteam/ncbi_blast_plus/ncbi_makeblastdb (Test #3)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Test input file (four_human_proteins.fasta) cannot be found.
      ```

  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/devteam/ncbi_blast_plus/ncbi_makeblastdb (Test #4)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Test input file (three_human_mRNA.fasta.gz) cannot be found.
      ```

  </div></details>


</details>

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/devteam/ncbi_blast_plus/ncbi_makeblastdb/2.10.1+galaxy2

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="4" data-toggle="tooltip" title="0 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="4" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 100.0%" aria-valuenow="4" aria-valuemin="0" aria-valuemax="4" title="4 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 4 |
| Passed     | 0 |
| Error      | 4 |
| Failure    | 0 |
| Skipped    | 0 |


<details><summary>Errored s</summary>

* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/devteam/ncbi_blast_plus/ncbi_makeblastdb (Test #1)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Test input file (four_human_proteins.fasta) cannot be found.
      ```

  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/devteam/ncbi_blast_plus/ncbi_makeblastdb (Test #2)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Test input file (four_human_proteins.fasta) cannot be found.
      ```

  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/devteam/ncbi_blast_plus/ncbi_makeblastdb (Test #3)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Test input file (four_human_proteins.fasta) cannot be found.
      ```

  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/devteam/ncbi_blast_plus/ncbi_makeblastdb (Test #4)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Test input file (three_human_mRNA.fasta.gz) cannot be found.
      ```

  </div></details>


</details>

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/devteam/ncbi_blast_plus/ncbi_makeblastdb/2.10.1+galaxy2

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="4" data-toggle="tooltip" title="0 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="4" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 100.0%" aria-valuenow="4" aria-valuemin="0" aria-valuemax="4" title="4 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 4 |
| Passed     | 0 |
| Error      | 4 |
| Failure    | 0 |
| Skipped    | 0 |


<details><summary>Errored s</summary>

* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/devteam/ncbi_blast_plus/ncbi_makeblastdb (Test #1)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Test input file (four_human_proteins.fasta) cannot be found.
      ```

  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/devteam/ncbi_blast_plus/ncbi_makeblastdb (Test #2)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Test input file (four_human_proteins.fasta) cannot be found.
      ```

  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/devteam/ncbi_blast_plus/ncbi_makeblastdb (Test #3)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Test input file (four_human_proteins.fasta) cannot be found.
      ```

  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/devteam/ncbi_blast_plus/ncbi_makeblastdb (Test #4)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Test input file (three_human_mRNA.fasta.gz) cannot be found.
      ```

  </div></details>


</details>

**Comment by jennaj** [comment]
**makeblastdb** (only) is failing with what looks like a config problem.

All these makeblastdb went to roundup: https://usegalaxy.org/u/jen/h/test-makeblastdb
Cross-checked, makeblastdb errors at Linux c408-114.stampede2.tacc.utexas.edu too: https://usegalaxy.org/u/jenhjackson/h/imported-test-makeblastdb

**Comment by natefoo** [comment]
There was no container built for the combination of dependencies, I've created a PR to build one at BioContainers/multi-package-containers#2296

**Comment by natefoo** [comment]
Took a while to get it trickled down to CVMFS but this should work now. I reran one of the failures in your history and it worked.
