### ISSUE TITLE
test fastqc 0.73+galaxy0 && 0.72+galaxy1

### ISSUE THREAD

**Issue by jennaj** [mvdbeek/usegalaxy-tests#55]
re

```
Execution resulted in the following messages:

Fatal error: Exit code 255 (FastQC returned non zero exit code)
Tool generated the following standard error:

FATAL:   could not open image /cvmfs/singularity.galaxyproject.org/all/fastqc:0.11.9--hdfd78af_1: failed to retrieve path for /cvmfs/singularity.galaxyproject.org/all/fastqc:0.11.9--hdfd78af_1: lstat /cvmfs/singularity.galaxyproject.org: transport endpoint is not connected
```

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/devteam/fastqc/fastqc/0.73+galaxy0

**Comment by jennaj** [comment]
Fixed. Not sure why the last test didn't run.

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 75.0%" aria-valuenow="6" aria-valuemin="0" aria-valuemax="8" data-toggle="tooltip" title="6 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="8" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 25.0%" aria-valuenow="2" aria-valuemin="0" aria-valuemax="8" title="2 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 8 |
| Passed     | 6 |
| Error      | 0 |
| Failure    | 2 |
| Skipped    | 0 |


<details><summary>Failed s</summary>

* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/devteam/fastqc/fastqc (Test #5)</summary><div class="padded">

    **Problems**:
    * ```
      'command_line'
      ```

  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/devteam/fastqc/fastqc (Test #7)</summary><div class="padded">

    **Problems**:
    * ```
      'command_line'
      ```

  </div></details>


</details>
<details><summary>Passed s</summary>

* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/devteam/fastqc/fastqc (Test #1)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/corral4/main/jobs/045/783/45783857/_job_tmp -Xmx28g -Xms256m

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | contaminants | ` None ` |
       | adapters | ` None ` |
       | limits | ` None ` |
       | nogroup | ` "false" ` |
       | min\_length | ` "" ` |
       | kmers | ` "7" ` |
       | \_\_job\_resource | ` {"__current_case__": 0, "__job_resource__select": "no"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "fastqsanger" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/devteam/fastqc/fastqc (Test #2)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/corral4/main/jobs/045/783/45783851/_job_tmp -Xmx28g -Xms256m

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | adapters | ` None ` |
       | limits | ` None ` |
       | nogroup | ` "false" ` |
       | min\_length | ` "" ` |
       | kmers | ` "7" ` |
       | \_\_job\_resource | ` {"__current_case__": 0, "__job_resource__select": "no"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "fastqsanger" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/devteam/fastqc/fastqc (Test #3)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/corral4/main/jobs/045/783/45783854/_job_tmp -Xmx28g -Xms256m

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | contaminants | ` None ` |
       | limits | ` None ` |
       | nogroup | ` "false" ` |
       | min\_length | ` "" ` |
       | kmers | ` "7" ` |
       | \_\_job\_resource | ` {"__current_case__": 0, "__job_resource__select": "no"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "fastqsanger" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/devteam/fastqc/fastqc (Test #4)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/corral4/main/jobs/045/783/45783889/_job_tmp -Xmx28g -Xms256m

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | contaminants | ` None ` |
       | adapters | ` None ` |
       | nogroup | ` "false" ` |
       | min\_length | ` "" ` |
       | kmers | ` "7" ` |
       | \_\_job\_resource | ` {"__current_case__": 0, "__job_resource__select": "no"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "fastqsanger" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/devteam/fastqc/fastqc (Test #6)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/corral4/main/jobs/045/783/45783842/_job_tmp -Xmx28g -Xms256m

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | contaminants | ` None ` |
       | adapters | ` None ` |
       | limits | ` None ` |
       | nogroup | ` "false" ` |
       | min\_length | ` "108" ` |
       | kmers | ` "7" ` |
       | \_\_job\_resource | ` {"__current_case__": 0, "__job_resource__select": "no"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "fastqsanger" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/devteam/fastqc/fastqc (Test #8)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/corral4/main/jobs/045/783/45783832/_job_tmp -Xmx28g -Xms256m

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | contaminants | ` None ` |
       | adapters | ` None ` |
       | limits | ` None ` |
       | nogroup | ` "false" ` |
       | min\_length | ` "" ` |
       | kmers | ` "7" ` |
       | \_\_job\_resource | ` {"__current_case__": 0, "__job_resource__select": "no"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "bam" ` |



  </div></details>


</details>
