### ISSUE TITLE
test custom_pro_db 1.22.0

### ISSUE THREAD

**Issue by jennaj** [mvdbeek/usegalaxy-tests#56]
toolshed.g2.bx.psu.edu/repos/galaxyp/custom_pro_db/custom_pro_db/1.22.0

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/galaxyp/custom_pro_db/custom_pro_db/1.22.0

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 33.33333333333333%" aria-valuenow="1" aria-valuemin="0" aria-valuemax="3" data-toggle="tooltip" title="1 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="3" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 66.66666666666666%" aria-valuenow="2" aria-valuemin="0" aria-valuemax="3" title="2 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 3 |
| Passed     | 1 |
| Error      | 0 |
| Failure    | 2 |
| Skipped    | 0 |


<details><summary>Failed s</summary>

* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/galaxyp/custom_pro_db/custom_pro_db (Test #1)</summary><div class="padded">

    **Problems**:
    * ```
      Output output_genomic_mapping_sqlite:  different than expected, difference (using diff):
      ( /tmp/tmpp_bqhaq3hg19_genomic_mapping.sqlite v. /tmp/tmptv7s7k0hhg19_genomic_mapping.sqlite )
      Binary data detected, not displaying diff
      ```
    * ```
      Output output_variant_annotation_sqlite:  different than expected, difference (using diff):
      ( /tmp/tmpc_allrffhg19_variant_annotation.sqlite v. /tmp/tmp68cwiwe5hg19_variant_annotation.sqlite )
      Binary data detected, not displaying diff
      ```
    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Output:**

    * ```console
      Loading customProDB
      Calculate RPKMs and Output proteins pass the cutoff into FASTA file ...  done
      Reading VCF file...  done
      Output variation table and variant protein sequence caused by SNVs...  done
      Output abberant protein FASTA file caused by short INDEL...  done

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | genome\_annotation | ` {"__current_case__": 1, "bamInput": {"values": [{"id": 102810104, "src": "hda"}]}, "cosmic": null, "dbsnpInCoding": null, "exonAnno": {"values": [{"id": 102810090, "src": "hda"}]}, "ids": {"values": [{"id": 102810101, "src": "hda"}]}, "proCodingSeq": {"values": [{"id": 102810098, "src": "hda"}]}, "proteinSeq": {"values": [{"id": 102810094, "src": "hda"}]}, "source": "history", "vcfInput": {"values": [{"id": 102810108, "src": "hda"}]}} ` |
       | rpkmCutoff | ` "1.0" ` |
       | outputIndels | ` "false" ` |
       | outputSQLite | ` "true" ` |
       | outputRData | ` "true" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/hg19.len" ` |
       | dbkey | ` "hg19" ` |
       | \_\_input\_ext | ` "rdata" ` |



  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/galaxyp/custom_pro_db/custom_pro_db (Test #2)</summary><div class="padded">

    **Problems**:
    * ```
      Output output_genomic_mapping_sqlite:  different than expected, difference (using diff):
      ( /tmp/tmpilzha1m3hg19_dbsnp_genomic_mapping.sqlite v. /tmp/tmptiyd2317hg19_dbsnp_genomic_mapping.sqlite )
      Binary data detected, not displaying diff
      ```
    * ```
      Output output_variant_annotation_sqlite:  different than expected, difference (using diff):
      ( /tmp/tmps7iuyw9thg19_dbsnp_variant_annotation.sqlite v. /tmp/tmpid21136hhg19_dbsnp_variant_annotation.sqlite )
      Binary data detected, not displaying diff
      ```
    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Output:**

    * ```console
      Loading customProDB
      Calculate RPKMs and Output proteins pass the cutoff into FASTA file ...  done
      Reading VCF file...  done
      Output variation table and variant protein sequence caused by SNVs...  done
      Output abberant protein FASTA file caused by short INDEL...  done

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | genome\_annotation | ` {"__current_case__": 1, "bamInput": {"values": [{"id": 102810104, "src": "hda"}]}, "cosmic": {"values": [{"id": 102810110, "src": "hda"}]}, "dbsnpInCoding": {"values": [{"id": 102810109, "src": "hda"}]}, "exonAnno": {"values": [{"id": 102810090, "src": "hda"}]}, "ids": {"values": [{"id": 102810101, "src": "hda"}]}, "proCodingSeq": {"values": [{"id": 102810098, "src": "hda"}]}, "proteinSeq": {"values": [{"id": 102810094, "src": "hda"}]}, "source": "history", "vcfInput": {"values": [{"id": 102810108, "src": "hda"}]}} ` |
       | rpkmCutoff | ` "0.0" ` |
       | outputIndels | ` "true" ` |
       | outputSQLite | ` "true" ` |
       | outputRData | ` "false" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/hg19.len" ` |
       | dbkey | ` "hg19" ` |
       | \_\_input\_ext | ` "rdata" ` |



  </div></details>


</details>
<details><summary>Passed s</summary>

* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/galaxyp/custom_pro_db/custom_pro_db (Test #3)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Output:**

    * ```console
      Loading customProDB
      Calculate RPKMs and Output proteins pass the cutoff into FASTA file ...  done
      Reading VCF file...  done
      Output variation table and variant protein sequence caused by SNVs...  done
      Output abberant protein FASTA file caused by short INDEL...  done

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | genome\_annotation | ` {"__current_case__": 1, "bamInput": {"values": [{"id": 102810104, "src": "hda"}]}, "cosmic": null, "dbsnpInCoding": null, "exonAnno": {"values": [{"id": 102810090, "src": "hda"}]}, "ids": {"values": [{"id": 102810101, "src": "hda"}]}, "proCodingSeq": {"values": [{"id": 102810098, "src": "hda"}]}, "proteinSeq": {"values": [{"id": 102810094, "src": "hda"}]}, "source": "history", "vcfInput": {"values": [{"id": 102810108, "src": "hda"}]}} ` |
       | rpkmCutoff | ` "1000.0" ` |
       | outputIndels | ` "true" ` |
       | outputSQLite | ` "false" ` |
       | outputRData | ` "false" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/hg19.len" ` |
       | dbkey | ` "hg19" ` |
       | \_\_input\_ext | ` "rdata" ` |



  </div></details>


</details>

**Comment by jennaj** [comment]
Maybe test case is flawed eg needs a binary diff, not plain text diff.

I ran the tutorial this morning as a broad test of the pipeline, and everything worked fine, including this tool. 

https://usegalaxy.org/u/jen/h/test-customprodb
