### ISSUE TITLE
test augustus 3.4.0+galaxy1

### ISSUE THREAD

**Issue by jennaj** [mvdbeek/usegalaxy-tests#57]
toolshed.g2.bx.psu.edu/repos/bgruening/augustus/augustus/3.4.0+galaxy1

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/bgruening/augustus/augustus/3.4.0+galaxy1

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 100.0%" aria-valuenow="6" aria-valuemin="0" aria-valuemax="6" data-toggle="tooltip" title="6 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="6" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="6" title="0 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 6 |
| Passed     | 6 |
| Error      | 0 |
| Failure    | 0 |
| Skipped    | 0 |


<details><summary>Passed s</summary>

* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/bgruening/augustus/augustus (Test #1)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | noInFrameStop | ` "false" ` |
       | singlestrand | ` "false" ` |
       | utr | ` "true" ` |
       | model | ` {"__current_case__": 1, "augustus_mode": "builtin", "organism": "human"} ` |
       | softmasking | ` "false" ` |
       | strand | ` "both" ` |
       | genemodel | ` "complete" ` |
       | hints | ` {"__current_case__": 1, "usehints": "F"} ` |
       | range | ` {"__current_case__": 1, "userange": "F"} ` |
       | gff | ` "false" ` |
       | outputs | ` ["protein", "codingseq", "cds"] ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/bgruening/augustus/augustus (Test #2)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | noInFrameStop | ` "false" ` |
       | singlestrand | ` "false" ` |
       | utr | ` "true" ` |
       | model | ` {"__current_case__": 1, "augustus_mode": "builtin", "organism": "human"} ` |
       | softmasking | ` "false" ` |
       | strand | ` "both" ` |
       | genemodel | ` "complete" ` |
       | hints | ` {"__current_case__": 1, "usehints": "F"} ` |
       | range | ` {"__current_case__": 1, "userange": "F"} ` |
       | gff | ` "true" ` |
       | outputs | ` ["protein", "codingseq", "cds"] ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/bgruening/augustus/augustus (Test #3)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | noInFrameStop | ` "false" ` |
       | singlestrand | ` "false" ` |
       | utr | ` "false" ` |
       | model | ` {"__current_case__": 1, "augustus_mode": "builtin", "organism": "human"} ` |
       | softmasking | ` "false" ` |
       | strand | ` "both" ` |
       | genemodel | ` "complete" ` |
       | hints | ` {"__current_case__": 1, "usehints": "F"} ` |
       | range | ` {"__current_case__": 1, "userange": "F"} ` |
       | gff | ` "false" ` |
       | outputs | ` ["protein", "codingseq", "introns", "cds", "start", "stop"] ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/bgruening/augustus/augustus (Test #4)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Output:**

    * ```console
      # This output was generated with AUGUSTUS (version 3.4.0).
      # AUGUSTUS is a gene prediction tool written by M. Stanke (mario.stanke@uni-greifswald.de),
      # O. Keller, S. König, L. Gerischer, L. Romoth and Katharina Hoff.
      # Please cite: Mario Stanke, Mark Diekhans, Robert Baertsch, David Haussler (2008),
      # Using native and syntenically mapped cDNA alignments to improve de novo gene finding
      # Bioinformatics 24: 637-644, doi 10.1093/bioinformatics/btn013
      # Sources of extrinsic information: M RM E W 
      # Setting CDSpart local malus: 0.985
      # Setting UTRpart local malus: 0.973
      # reading in the file /corral4/main/objects/c/3/9/dataset_c396dd05-e070-48b5-bdc7-6de32bcb286f.dat ...
      # Have extrinsic information about 1 sequences (in the specified range). 
      # Initializing the parameters using config directory /usr/local/config/ ...
      # fly version. Using default transition matrix.
      # Looks like /corral4/main/objects/c/7/4/dataset_c746e98e-23d0-4bff-b5e5-aad51535048a.dat is in fasta format.
      # We have hints for 1 sequence and for 1 of the sequences in the input set.
      #
      # ----- prediction on sequence number 1 (length = 9950, name = chr2R) -----
      #
      # Delete group HintGroup gi|2701440, 8630-8864, mult= 1, priority= 4 4 features
      # Delete group HintGroup gi|4203815, 8630-9250, mult= 1, priority= 4 6 features
      # Delete group HintGroup gi|4245769, 8630-9250, mult= 1, priority= 4 6 features
      # Delete group HintGroup gi|4245770, 8630-9250, mult= 1, priority= 4 6 features
      # Delete group HintGroup gi|13769068, 8630-9250, mult= 1, priority= 4 6 features
      # Delete group HintGroup gi|14693753, 8630-9250, mult= 1, priority= 4 6 features
      # Delete group HintGroup gi|14695912, 8630-9250, mult= 1, priority= 4 6 features
      # Delete group HintGroup gi|14699170, 8630-9250, mult= 1, priority= 4 6 features
      # Delete group HintGroup gi|14700619, 8630-9250, mult= 1, priority= 4 6 features
      # Delete group HintGroup gi|15539951, 8630-9250, mult= 1, priority= 4 6 features
      # Delete group HintGroup gi|15543927, 8630-9250, mult= 1, priority= 4 6 features
      # Delete group HintGroup gi|38623822, 8630-9250, mult= 1, priority= 4 6 features
      # Delete group HintGroup SRR023546.8642467/1, 8630-8693, mult= 1, priority= 4 2 features
      # Delete group HintGroup gi|2871896, 8811-9250, mult= 1, priority= 4 4 features
      # Delete group HintGroup gi|15543159, 8811-9250, mult= 1, priority= 4 4 features
      # Delete group HintGroup , 8811-8864, mult= 8, priority= 4 1 features
      # Delete group HintGroup , 8811-8864, mult= 8, priority= 4 1 features
      # Delete group HintGroup gi|2700091, 9191-9250, mult= 1, priority= 4 2 features
      # Delete group HintGroup gi|2701304, 9191-9250, mult= 1, priority= 4 2 features
      # Delete group HintGroup gi|2701309, 9191-9250, mult= 1, priority= 4 2 features
      # Delete group HintGroup gi|3101873, 9191-9250, mult= 1, priority= 4 2 features
      # Delete group HintGroup , 9191-9250, mult= 3, priority= 4 1 features
      # Delete group HintGroup , 9191-9250, mult= 3, priority= 4 1 features
      # Deleted 23 groups because some hint was not satisfiable.
      # Predicted genes for sequence number 1 on both strands
      # start gene chr2R.g1
      chr2R	AUGUSTUS	gene	7560	9303	0.84	-	.	chr2R.g1
      chr2R	AUGUSTUS	transcript	7560	9303	0.84	-	.	chr2R.g1.t1
      chr2R	AUGUSTUS	start_codon	9301	9303	.	-	0	transcript_id "chr2R.g1.t1"; gene_id "chr2R.g1";
      # Evidence for and against this transcript:
      # % of transcript supported by hints (any source): 57.1
      # CDS exons: 4/4
      #      W:   4 
      # CDS introns: 0/3
      # 5'UTR exons and introns: 0/0
      # 3'UTR exons and introns: 0/0
      # hint groups fully obeyed: 120
      #      W: 120 
      # incompatible hint groups: 9
      #      W:   9 
      # end gene chr2R.g1
      ###
      # command line:
      # augustus --strand=both --noInFrameStop=false --gff3=off --uniqueGeneId=true --protein=off --codingseq=off --introns=off --stop=off --stop=off --cds=off --singlestrand=false /corral4/main/objects/c/7/4/dataset_c746e98e-23d0-4bff-b5e5-aad51535048a.dat --UTR=off --genemodel=complete --softmasking=0 --hintsfile=/corral4/main/objects/c/3/9/dataset_c396dd05-e070-48b5-bdc7-6de32bcb286f.dat --extrinsicCfgFile=/corral4/main/objects/9/c/b/dataset_9cb5dae6-4781-4c8b-8b91-9709624d8a75.dat --species=fly

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | noInFrameStop | ` "false" ` |
       | singlestrand | ` "false" ` |
       | utr | ` "false" ` |
       | model | ` {"__current_case__": 1, "augustus_mode": "builtin", "organism": "fly"} ` |
       | softmasking | ` "false" ` |
       | strand | ` "both" ` |
       | genemodel | ` "complete" ` |
       | hints | ` {"__current_case__": 0, "extrinsiccfg": {"values": [{"id": 102911770, "src": "hda"}]}, "hintsfile": {"values": [{"id": 102911767, "src": "hda"}]}, "usehints": "T"} ` |
       | range | ` {"__current_case__": 1, "userange": "F"} ` |
       | gff | ` "false" ` |
       | outputs | ` [] ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/bgruening/augustus/augustus (Test #5)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Output:**

    * ```console
      # This output was generated with AUGUSTUS (version 3.4.0).
      # AUGUSTUS is a gene prediction tool written by M. Stanke (mario.stanke@uni-greifswald.de),
      # O. Keller, S. König, L. Gerischer, L. Romoth and Katharina Hoff.
      # Please cite: Mario Stanke, Mark Diekhans, Robert Baertsch, David Haussler (2008),
      # Using native and syntenically mapped cDNA alignments to improve de novo gene finding
      # Bioinformatics 24: 637-644, doi 10.1093/bioinformatics/btn013
      # Sources of extrinsic information: M RM E W 
      # Setting CDSpart local malus: 0.985
      # Setting UTRpart local malus: 0.973
      # reading in the file /corral4/main/objects/c/3/9/dataset_c396dd05-e070-48b5-bdc7-6de32bcb286f.dat ...
      # Have extrinsic information about 1 sequences (in the specified range). 
      # Initializing the parameters using config directory /usr/local/config/ ...
      # fly version. Using default transition matrix.
      # Looks like /corral4/main/objects/c/7/4/dataset_c746e98e-23d0-4bff-b5e5-aad51535048a.dat is in fasta format.
      # We have hints for 1 sequence and for 1 of the sequences in the input set.
      #
      # ----- prediction on sequence number 1 (length = 2001, name = chr2R) -----
      #
      # Delete group HintGroup gi|2701440, 1631-1865, mult= 1, priority= 4 4 features
      # Delete group HintGroup gi|4203815, 1631-1865, mult= 1, priority= 4 4 features
      # Delete group HintGroup gi|4245769, 1631-1865, mult= 1, priority= 4 4 features
      # Delete group HintGroup gi|4245770, 1631-1865, mult= 1, priority= 4 4 features
      # Delete group HintGroup gi|13769068, 1631-1865, mult= 1, priority= 4 4 features
      # Delete group HintGroup gi|14693753, 1631-1865, mult= 1, priority= 4 4 features
      # Delete group HintGroup gi|14695912, 1631-1865, mult= 1, priority= 4 4 features
      # Delete group HintGroup gi|14699170, 1631-1865, mult= 1, priority= 4 4 features
      # Delete group HintGroup gi|14700619, 1631-1865, mult= 1, priority= 4 4 features
      # Delete group HintGroup gi|15539951, 1631-1865, mult= 1, priority= 4 4 features
      # Delete group HintGroup gi|15543927, 1631-1865, mult= 1, priority= 4 4 features
      # Delete group HintGroup gi|38623822, 1631-1865, mult= 1, priority= 4 4 features
      # Delete group HintGroup SRR023546.8642467/1, 1631-1694, mult= 1, priority= 4 2 features
      # Delete group HintGroup gi|2871896, 1812-1865, mult= 1, priority= 4 2 features
      # Delete group HintGroup gi|15543159, 1812-1865, mult= 1, priority= 4 2 features
      # Delete group HintGroup , 1812-1865, mult= 8, priority= 4 1 features
      # Delete group HintGroup , 1812-1865, mult= 8, priority= 4 1 features
      # Deleted 17 groups because some hint was not satisfiable.
      # Predicted genes for sequence number 1 on both strands
      # start gene chr2R.g1
      chr2R	AUGUSTUS	gene	7560	8931	0.84	-	.	chr2R.g1
      chr2R	AUGUSTUS	transcript	7560	8931	0.84	-	.	chr2R.g1.t1
      chr2R	AUGUSTUS	start_codon	8929	8931	.	-	0	transcript_id "chr2R.g1.t1"; gene_id "chr2R.g1";
      # Evidence for and against this transcript:
      # % of transcript supported by hints (any source): 60
      # CDS exons: 3/3
      #      W:   3 
      # CDS introns: 0/2
      # 5'UTR exons and introns: 0/0
      # 3'UTR exons and introns: 0/0
      # hint groups fully obeyed: 96
      #      W:  96 
      # incompatible hint groups: 6
      #      W:   6 
      # end gene chr2R.g1
      ###
      # command line:
      # augustus --strand=both --noInFrameStop=false --gff3=off --uniqueGeneId=true --protein=off --codingseq=off --introns=off --stop=off --stop=off --cds=off --singlestrand=false /corral4/main/objects/c/7/4/dataset_c746e98e-23d0-4bff-b5e5-aad51535048a.dat --UTR=off --genemodel=complete --softmasking=0 --hintsfile=/corral4/main/objects/c/3/9/dataset_c396dd05-e070-48b5-bdc7-6de32bcb286f.dat --extrinsicCfgFile=/corral4/main/objects/9/c/b/dataset_9cb5dae6-4781-4c8b-8b91-9709624d8a75.dat --predictionStart=7000 --predictionEnd=9000 --species=fly

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | noInFrameStop | ` "false" ` |
       | singlestrand | ` "false" ` |
       | utr | ` "false" ` |
       | model | ` {"__current_case__": 1, "augustus_mode": "builtin", "organism": "fly"} ` |
       | softmasking | ` "false" ` |
       | strand | ` "both" ` |
       | genemodel | ` "complete" ` |
       | hints | ` {"__current_case__": 0, "extrinsiccfg": {"values": [{"id": 102911770, "src": "hda"}]}, "hintsfile": {"values": [{"id": 102911767, "src": "hda"}]}, "usehints": "T"} ` |
       | range | ` {"__current_case__": 0, "start": "7000", "stop": "9000", "userange": "T"} ` |
       | gff | ` "false" ` |
       | outputs | ` [] ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/bgruening/augustus/augustus (Test #6)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      #########################################################################
      # WARNING: --softmasking=1 and all sequences are completely in lower case.
      # They will be treated as repeatmasked everywhere and genes could be severely underpredicted.
      # If this is not intended, rerun with --softmasking=0
      #########################################################################

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | noInFrameStop | ` "false" ` |
       | singlestrand | ` "false" ` |
       | utr | ` "true" ` |
       | model | ` {"__current_case__": 1, "augustus_mode": "builtin", "organism": "human"} ` |
       | softmasking | ` "true" ` |
       | strand | ` "both" ` |
       | genemodel | ` "complete" ` |
       | hints | ` {"__current_case__": 1, "usehints": "F"} ` |
       | range | ` {"__current_case__": 1, "userange": "F"} ` |
       | gff | ` "false" ` |
       | outputs | ` ["protein", "codingseq", "cds"] ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


</details>
