### ISSUE TITLE
test crossmap_vcf 0.5.2+galaxy0

### ISSUE THREAD

**Issue by jennaj** [mvdbeek/usegalaxy-tests#58]
toolshed.g2.bx.psu.edu/repos/iuc/crossmap_vcf/crossmap_vcf/0.5.2+galaxy0

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/iuc/crossmap_vcf/crossmap_vcf/0.5.2+galaxy0

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 100.0%" aria-valuenow="1" aria-valuemin="0" aria-valuemax="1" data-toggle="tooltip" title="1 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="1" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="1" title="0 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 1 |
| Passed     | 1 |
| Error      | 0 |
| Failure    | 0 |
| Skipped    | 0 |


<details><summary>Passed s</summary>

* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/crossmap_vcf/crossmap_vcf (Test #1)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      @ 2022-09-20 19:25:44: Read the chain file:  /corral4/main/objects/f/1/1/dataset_f11f3f84-5d92-4a96-91e6-d7040531add9.dat
      @ 2022-09-20 19:25:44: Filter out variants [reference_allele == alternative_allele] ...
      @ 2022-09-20 19:25:44: Creating index for genome.fasta
      @ 2022-09-20 19:25:44: Updating contig field ... 
      @ 2022-09-20 19:25:44: Lifting over ... 
      @ 2022-09-20 19:25:45: Total entries: 3
      @ 2022-09-20 19:25:45: Failed to map: 1

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | seq\_source | ` {"__current_case__": 1, "chain_source": {"__current_case__": 1, "index_source": "history", "input_chain": {"values": [{"id": 102969192, "src": "hda"}]}}, "index_source_s": "history", "input": {"values": [{"id": 102969190, "src": "hda"}]}, "input_fasta": {"values": [{"id": 102969191, "src": "hda"}]}} ` |
       | no\_comp\_alleles | ` "true" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


</details>
