### ISSUE TITLE
test gmx_sim 2022+galaxy0

### ISSUE THREAD

**Issue by jennaj** [mvdbeek/usegalaxy-tests#59]
toolshed.g2.bx.psu.edu/repos/chemteam/gmx_sim/gmx_sim/2022+galaxy0

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/chemteam/gmx_sim/gmx_sim/2022+galaxy0

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/chemteam/gmx_sim/gmx_sim/2022+galaxy0

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 100.0%" aria-valuenow="4" aria-valuemin="0" aria-valuemax="4" data-toggle="tooltip" title="4 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="4" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="4" title="0 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 4 |
| Passed     | 4 |
| Error      | 0 |
| Failure    | 0 |
| Skipped    | 0 |


<details><summary>Passed s</summary>

* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/chemteam/gmx_sim/gmx_sim (Test #1)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | inps | ` {"cpt_in": {"values": [{"id": 103272667, "src": "hda"}]}, "itp_in": null, "ndx_in": null} ` |
       | outps | ` {"cpt_out": "false", "edr_out": "false", "str": "gro", "tpr_out": "true", "traj": "trr", "xvg_out": "false"} ` |
       | sets | ` {"ensembleselect": {"__current_case__": 1, "ensemble": "npt"}, "mdp": {"__current_case__": 0, "mdp_input": {"values": [{"id": 103272668, "src": "hda"}]}, "mdpfile": "custom"}} ` |
       | mxw | ` "0" ` |
       | capture\_log | ` "false" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "auto" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/chemteam/gmx_sim/gmx_sim (Test #2)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | inps | ` {"cpt_in": {"values": [{"id": 103272667, "src": "hda"}]}, "itp_in": null, "ndx_in": null} ` |
       | outps | ` {"cpt_out": "false", "edr_out": "false", "str": "both", "tpr_out": "false", "traj": "trr", "xvg_out": "false"} ` |
       | sets | ` {"ensembleselect": {"__current_case__": 1, "ensemble": "npt"}, "mdp": {"__current_case__": 1, "constraints": "all-bonds", "coulombtype": "PME", "cutoffscheme": "Verlet", "integrator": "md", "md_steps": "500", "mdpfile": "default", "rcoulomb": "1.0", "rlist": "1.0", "rvdw": "1.0", "step_length": "0.002", "systemTcouple": "false", "temperature": "300", "write_freq": "50"}} ` |
       | mxw | ` "0" ` |
       | capture\_log | ` "false" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "gro" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/chemteam/gmx_sim/gmx_sim (Test #3)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | inps | ` {"cpt_in": {"values": [{"id": 103272667, "src": "hda"}]}, "itp_in": null, "ndx_in": {"values": [{"id": 103272669, "src": "hda"}]}} ` |
       | outps | ` {"cpt_out": "false", "edr_out": "false", "str": "both", "tpr_out": "false", "traj": "trr", "xvg_out": "false"} ` |
       | sets | ` {"ensembleselect": {"__current_case__": 1, "ensemble": "npt"}, "mdp": {"__current_case__": 1, "constraints": "all-bonds", "coulombtype": "PME", "cutoffscheme": "Verlet", "integrator": "md", "md_steps": "500", "mdpfile": "default", "rcoulomb": "1.0", "rlist": "1.0", "rvdw": "1.0", "step_length": "0.002", "systemTcouple": "false", "temperature": "300", "write_freq": "50"}} ` |
       | mxw | ` "0" ` |
       | capture\_log | ` "false" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "gro" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/chemteam/gmx_sim/gmx_sim (Test #4)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | inps | ` {"cpt_in": null, "itp_in": {"values": [{"id": 103272665, "src": "hda"}]}, "ndx_in": null} ` |
       | outps | ` {"cpt_out": "true", "edr_out": "false", "str": "pdb", "tpr_out": "false", "traj": "xtc", "xvg_out": "false"} ` |
       | sets | ` {"ensembleselect": {"__current_case__": 0, "ensemble": "nvt", "startvel": "false"}, "mdp": {"__current_case__": 1, "constraints": "all-bonds", "coulombtype": "PME", "cutoffscheme": "Verlet", "integrator": "md", "md_steps": "500", "mdpfile": "default", "rcoulomb": "1.0", "rlist": "1.0", "rvdw": "1.0", "step_length": "0.002", "systemTcouple": "false", "temperature": "300", "write_freq": "50"}} ` |
       | mxw | ` "0" ` |
       | capture\_log | ` "false" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "auto" ` |



  </div></details>


</details>
