### ISSUE TITLE
test meme_meme 5.0.5.0

### ISSUE THREAD

**Issue by jennaj** [mvdbeek/usegalaxy-tests#61]
toolshed.g2.bx.psu.edu/repos/iuc/meme_meme/meme_meme/5.0.5.0

Other tools in this suite are not supported anymore. Might need to be marked deprecated.

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/iuc/meme_meme/meme_meme/5.0.5.0

**Comment by jennaj** [comment]
test jobs not running?

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/iuc/meme_meme/meme_meme/5.0.5.0

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/iuc/meme_meme/meme_meme/5.0.5.0

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 100.0%" aria-valuenow="2" aria-valuemin="0" aria-valuemax="2" data-toggle="tooltip" title="2 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="2" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="2" title="0 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 2 |
| Passed     | 2 |
| Error      | 0 |
| Failure    | 0 |
| Skipped    | 0 |


<details><summary>Passed s</summary>

* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/meme_meme/meme_meme (Test #1)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      Duplicate sequence name. Skipping 'chr21_47517957_47518007_+'.
      Duplicate sequence name. Skipping 'chr21_47517957_47518007_+'.
      Duplicate sequence name. Skipping 'chr21_47575506_47575556_-'.
      [roundup52:882033] PMIX ERROR: NO-PERMISSIONS in file dstore_base.c at line 234

      ```
    **Traceback:**

    * ```console
      
      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | options\_type | ` {"__current_case__": 0, "options_type_selector": "basic"} ` |
       | non\_commercial\_use | ` true ` |
       | \_\_job\_resource | ` {"__current_case__": 0, "__job_resource__select": "no"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/hg19.len" ` |
       | dbkey | ` "hg19" ` |
       | \_\_input\_ext | ` "fasta" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/meme_meme/meme_meme (Test #2)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      Duplicate sequence name. Skipping 'chr21_47517957_47518007_+'.
      Duplicate sequence name. Skipping 'chr21_47517957_47518007_+'.
      Duplicate sequence name. Skipping 'chr21_47575506_47575556_-'.
      [roundup58:05817] PMIX ERROR: NO-PERMISSIONS in file dstore_base.c at line 234

      ```
    **Traceback:**

    * ```console
      
      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | options\_type | ` {"__current_case__": 1, "alphabet_type": {"__current_case__": 1, "alphabet_type_selector": "dna", "pal": false, "prior_type": {"__current_case__": 0, "plib": {"values": [{"id": 113090931, "src": "hda"}]}, "prior_b": "0.01", "prior_type_selector": "dirichlet"}, "revcomp": false, "spmap_type": {"__current_case__": 0, "spfuzz": "0.5", "spmap_type_selector": "uni"}}, "bfile": null, "branching_type": {"__current_case__": 0, "branching_type_selector": "no_x_branch"}, "distance": "0.001", "evt": "inf", "maxiter": "50", "mod_type": {"__current_case__": 1, "mod_type_selector": "zoops", "motif_occurrence_type": {"__current_case__": 0, "motif_occurrence_type_selector": "default"}}, "motif_trim_type": {"__current_case__": 1, "motif_trim_type_selector": "trim", "noendgaps": false, "wg": "11", "ws": "1"}, "motif_width_type": {"__current_case__": 1, "maxw": "50", "minw": "8", "motif_width_type_selector": "range"}, "nmotifs": "1", "options_type_selector": "advanced", "pspfile": null, "sf": "Galaxy FASTA Input", "wnsites": "0.8"} ` |
       | non\_commercial\_use | ` true ` |
       | \_\_job\_resource | ` {"__current_case__": 0, "__job_resource__select": "no"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/hg19.len" ` |
       | dbkey | ` "hg19" ` |
       | \_\_input\_ext | ` "fasta" ` |



  </div></details>


</details>

**Comment by jennaj** [comment]
HooRay
