### ISSUE TITLE
test rseqc_RPKM_saturation 2.6.4.1 >> 5.0.1+galaxy2

### ISSUE THREAD

**Issue by jennaj** [mvdbeek/usegalaxy-tests#63]
toolshed.g2.bx.psu.edu/repos/nilesh/rseqc/rseqc_RPKM_saturation/2.6.4.1

notes:
1. tool requires bed12 (autocoverts any other format, including bed)
2. bed12 is not a datatype the user can select under edit attributes. it can be assigned at upload. 
3. bed -> bed12 with autoconvert loses information in column 11 and 12 (leaves just a single comma?? new?)
4. tool probably fails because cannot interpret splices because no blockSizes or blockStarts

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/nilesh/rseqc/rseqc_RPKM_saturation/2.6.4.1

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 100.0%" aria-valuenow="1" aria-valuemin="0" aria-valuemax="1" data-toggle="tooltip" title="1 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="1" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="1" title="0 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 1 |
| Passed     | 1 |
| Error      | 0 |
| Failure    | 0 |
| Skipped    | 0 |


<details><summary>Passed s</summary>

* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/nilesh/rseqc/rseqc_RPKM_saturation (Test #1)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      [E::idx_find_and_load] Could not retrieve index file for '/corral4/main/objects/f/6/b/dataset_f6b43cc0-f7db-4761-ac60-bed01073591a.dat'
      Load BAM file ...  Done
      shuffling alignments ... Done
      sampling 5% (245) fragments ...
      assign reads to transcripts in /corral4/main/objects/4/c/7/dataset_4c76bdbd-c043-4eca-a675-39486ce4b848.dat ...

      sampling 10% (491) fragments ...
      assign reads to transcripts in /corral4/main/objects/4/c/7/dataset_4c76bdbd-c043-4eca-a675-39486ce4b848.dat ...

      sampling 15% (737) fragments ...
      assign reads to transcripts in /corral4/main/objects/4/c/7/dataset_4c76bdbd-c043-4eca-a675-39486ce4b848.dat ...

      sampling 20% (983) fragments ...
      assign reads to transcripts in /corral4/main/objects/4/c/7/dataset_4c76bdbd-c043-4eca-a675-39486ce4b848.dat ...

      sampling 25% (1229) fragments ...
      assign reads to transcripts in /corral4/main/objects/4/c/7/dataset_4c76bdbd-c043-4eca-a675-39486ce4b848.dat ...

      sampling 30% (1474) fragments ...
      assign reads to transcripts in /corral4/main/objects/4/c/7/dataset_4c76bdbd-c043-4eca-a675-39486ce4b848.dat ...

      sampling 35% (1720) fragments ...
      assign reads to transcripts in /corral4/main/objects/4/c/7/dataset_4c76bdbd-c043-4eca-a675-39486ce4b848.dat ...

      sampling 40% (1966) fragments ...
      assign reads to transcripts in /corral4/main/objects/4/c/7/dataset_4c76bdbd-c043-4eca-a675-39486ce4b848.dat ...

      sampling 45% (2212) fragments ...
      assign reads to transcripts in /corral4/main/objects/4/c/7/dataset_4c76bdbd-c043-4eca-a675-39486ce4b848.dat ...

      sampling 50% (2458) fragments ...
      assign reads to transcripts in /corral4/main/objects/4/c/7/dataset_4c76bdbd-c043-4eca-a675-39486ce4b848.dat ...

      sampling 55% (2703) fragments ...
      assign reads to transcripts in /corral4/main/objects/4/c/7/dataset_4c76bdbd-c043-4eca-a675-39486ce4b848.dat ...

      sampling 60% (2949) fragments ...
      assign reads to transcripts in /corral4/main/objects/4/c/7/dataset_4c76bdbd-c043-4eca-a675-39486ce4b848.dat ...

      sampling 65% (3195) fragments ...
      assign reads to transcripts in /corral4/main/objects/4/c/7/dataset_4c76bdbd-c043-4eca-a675-39486ce4b848.dat ...

      sampling 70% (3441) fragments ...
      assign reads to transcripts in /corral4/main/objects/4/c/7/dataset_4c76bdbd-c043-4eca-a675-39486ce4b848.dat ...

      sampling 75% (3687) fragments ...
      assign reads to transcripts in /corral4/main/objects/4/c/7/dataset_4c76bdbd-c043-4eca-a675-39486ce4b848.dat ...

      sampling 80% (3932) fragments ...
      assign reads to transcripts in /corral4/main/objects/4/c/7/dataset_4c76bdbd-c043-4eca-a675-39486ce4b848.dat ...

      sampling 85% (4178) fragments ...
      assign reads to transcripts in /corral4/main/objects/4/c/7/dataset_4c76bdbd-c043-4eca-a675-39486ce4b848.dat ...

      sampling 90% (4424) fragments ...
      assign reads to transcripts in /corral4/main/objects/4/c/7/dataset_4c76bdbd-c043-4eca-a675-39486ce4b848.dat ...

      sampling 95% (4670) fragments ...
      assign reads to transcripts in /corral4/main/objects/4/c/7/dataset_4c76bdbd-c043-4eca-a675-39486ce4b848.dat ...

      sampling 100% (4916) fragments ...
      assign reads to transcripts in /corral4/main/objects/4/c/7/dataset_4c76bdbd-c043-4eca-a675-39486ce4b848.dat ...


      ```
    **Standard Output:**

    * ```console
      null device 
                1 

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | strand\_type | ` {"__current_case__": 2, "strand_specific": "none"} ` |
       | percentileFloor | ` "5" ` |
       | percentileCeiling | ` "100" ` |
       | percentileStep | ` "5" ` |
       | rpkmCutoff | ` "0.01" ` |
       | mapq | ` "30" ` |
       | rscript\_output | ` "true" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "bam" ` |



  </div></details>


</details>

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/nilesh/rseqc/rseqc_RPKM_saturation/5.0.1+galaxy2

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 100.0%" aria-valuenow="1" aria-valuemin="0" aria-valuemax="1" data-toggle="tooltip" title="1 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="1" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="1" title="0 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 1 |
| Passed     | 1 |
| Error      | 0 |
| Failure    | 0 |
| Skipped    | 0 |


<details><summary>Passed s</summary>

* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/nilesh/rseqc/rseqc_RPKM_saturation (Test #1)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      Load BAM file ...  Done
      shuffling alignments ... Done
      sampling 5% (245) fragments ...
      assign reads to transcripts in /corral4/main/objects/5/7/0/dataset_570ceb72-9370-474c-94a2-41d7461346b7.dat ...

      sampling 10% (491) fragments ...
      assign reads to transcripts in /corral4/main/objects/5/7/0/dataset_570ceb72-9370-474c-94a2-41d7461346b7.dat ...

      sampling 15% (737) fragments ...
      assign reads to transcripts in /corral4/main/objects/5/7/0/dataset_570ceb72-9370-474c-94a2-41d7461346b7.dat ...

      sampling 20% (983) fragments ...
      assign reads to transcripts in /corral4/main/objects/5/7/0/dataset_570ceb72-9370-474c-94a2-41d7461346b7.dat ...

      sampling 25% (1229) fragments ...
      assign reads to transcripts in /corral4/main/objects/5/7/0/dataset_570ceb72-9370-474c-94a2-41d7461346b7.dat ...

      sampling 30% (1474) fragments ...
      assign reads to transcripts in /corral4/main/objects/5/7/0/dataset_570ceb72-9370-474c-94a2-41d7461346b7.dat ...

      sampling 35% (1720) fragments ...
      assign reads to transcripts in /corral4/main/objects/5/7/0/dataset_570ceb72-9370-474c-94a2-41d7461346b7.dat ...

      sampling 40% (1966) fragments ...
      assign reads to transcripts in /corral4/main/objects/5/7/0/dataset_570ceb72-9370-474c-94a2-41d7461346b7.dat ...

      sampling 45% (2212) fragments ...
      assign reads to transcripts in /corral4/main/objects/5/7/0/dataset_570ceb72-9370-474c-94a2-41d7461346b7.dat ...

      sampling 50% (2458) fragments ...
      assign reads to transcripts in /corral4/main/objects/5/7/0/dataset_570ceb72-9370-474c-94a2-41d7461346b7.dat ...

      sampling 55% (2703) fragments ...
      assign reads to transcripts in /corral4/main/objects/5/7/0/dataset_570ceb72-9370-474c-94a2-41d7461346b7.dat ...

      sampling 60% (2949) fragments ...
      assign reads to transcripts in /corral4/main/objects/5/7/0/dataset_570ceb72-9370-474c-94a2-41d7461346b7.dat ...

      sampling 65% (3195) fragments ...
      assign reads to transcripts in /corral4/main/objects/5/7/0/dataset_570ceb72-9370-474c-94a2-41d7461346b7.dat ...

      sampling 70% (3441) fragments ...
      assign reads to transcripts in /corral4/main/objects/5/7/0/dataset_570ceb72-9370-474c-94a2-41d7461346b7.dat ...

      sampling 75% (3687) fragments ...
      assign reads to transcripts in /corral4/main/objects/5/7/0/dataset_570ceb72-9370-474c-94a2-41d7461346b7.dat ...

      sampling 80% (3932) fragments ...
      assign reads to transcripts in /corral4/main/objects/5/7/0/dataset_570ceb72-9370-474c-94a2-41d7461346b7.dat ...

      sampling 85% (4178) fragments ...
      assign reads to transcripts in /corral4/main/objects/5/7/0/dataset_570ceb72-9370-474c-94a2-41d7461346b7.dat ...

      sampling 90% (4424) fragments ...
      assign reads to transcripts in /corral4/main/objects/5/7/0/dataset_570ceb72-9370-474c-94a2-41d7461346b7.dat ...

      sampling 95% (4670) fragments ...
      assign reads to transcripts in /corral4/main/objects/5/7/0/dataset_570ceb72-9370-474c-94a2-41d7461346b7.dat ...

      sampling 100% (4916) fragments ...
      assign reads to transcripts in /corral4/main/objects/5/7/0/dataset_570ceb72-9370-474c-94a2-41d7461346b7.dat ...


      ```
    **Standard Output:**

    * ```console
      null device 
                1 

      ```
    **Traceback:**

    * ```console
      
      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | strand\_type | ` {"__current_case__": 2, "strand_specific": "none"} ` |
       | percentileFloor | ` "5" ` |
       | percentileCeiling | ` "100" ` |
       | percentileStep | ` "5" ` |
       | rpkmCutoff | ` "0.01" ` |
       | mapq | ` "30" ` |
       | rscript\_output | ` true ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


</details>
