### ISSUE TITLE
test mixcr_analyze 3.0.5.0

### ISSUE THREAD

**Issue by jennaj** [mvdbeek/usegalaxy-tests#67]
toolshed.g2.bx.psu.edu/repos/iuc/mixcr_analyze/mixcr_analyze/3.0.5.0

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/iuc/mixcr_analyze/mixcr_analyze/3.0.5.0

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="2" data-toggle="tooltip" title="0 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="2" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 100.0%" aria-valuenow="2" aria-valuemin="0" aria-valuemax="2" title="2 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 2 |
| Passed     | 0 |
| Error      | 0 |
| Failure    | 2 |
| Skipped    | 0 |


<details><summary>Failed s</summary>

* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/iuc/mixcr_analyze/mixcr_analyze (Test #1)</summary><div class="padded">

    **Problems**:
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/mixcr_analyze/mixcr_analyze/3.0.5.0, exit_code: 127, stderr: /corral4/main/jobs/046/733/46733887/tool_script.sh: line 9: mixcr: not found
      .
      ```
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/mixcr_analyze/mixcr_analyze/3.0.5.0, exit_code: 127, stderr: /corral4/main/jobs/046/733/46733887/tool_script.sh: line 9: mixcr: not found
      .
      ```
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/mixcr_analyze/mixcr_analyze/3.0.5.0, exit_code: 127, stderr: /corral4/main/jobs/046/733/46733887/tool_script.sh: line 9: mixcr: not found
      .
      ```
    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      127
      ```
    **Standard Error:**

    * ```console
      /corral4/main/jobs/046/733/46733887/tool_script.sh: line 9: mixcr: not found

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | analyze | ` {"__current_case__": 1, "pipeline": "shotgun"} ` |
       | starting\_material | ` "rna" ` |
       | fastq\_input | ` {"__current_case__": 0, "fastq_input1": {"values": [{"id": 104735550, "src": "hda"}]}, "fastq_input2": {"values": [{"id": 104735553, "src": "hda"}]}, "fastq_input_selector": "paired"} ` |
       | imgt | ` {"__current_case__": 0, "library_selector": "builtin", "species": "9606"} ` |
       | contig\_assembly | ` "true" ` |
       | impute\_germline\_on\_export | ` "true" ` |
       | only\_productive | ` "false" ` |
       | receptor\_type | ` "xcr" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "fastqsanger" ` |



  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/iuc/mixcr_analyze/mixcr_analyze (Test #2)</summary><div class="padded">

    **Problems**:
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/mixcr_analyze/mixcr_analyze/3.0.5.0, exit_code: 127, stderr: /corral4/main/jobs/046/733/46733888/tool_script.sh: line 9: mixcr: not found
      .
      ```
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/mixcr_analyze/mixcr_analyze/3.0.5.0, exit_code: 127, stderr: /corral4/main/jobs/046/733/46733888/tool_script.sh: line 9: mixcr: not found
      .
      ```
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/mixcr_analyze/mixcr_analyze/3.0.5.0, exit_code: 127, stderr: /corral4/main/jobs/046/733/46733888/tool_script.sh: line 9: mixcr: not found
      .
      ```
    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      127
      ```
    **Standard Error:**

    * ```console
      /corral4/main/jobs/046/733/46733888/tool_script.sh: line 9: mixcr: not found

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | analyze | ` {"__current_case__": 0, "adapters": "no-adapters", "pipeline": "amplicon", "primers3end": "j-primers", "primers5end": "v-primers"} ` |
       | starting\_material | ` "rna" ` |
       | fastq\_input | ` {"__current_case__": 0, "fastq_input1": {"values": [{"id": 104735550, "src": "hda"}]}, "fastq_input2": {"values": [{"id": 104735553, "src": "hda"}]}, "fastq_input_selector": "paired"} ` |
       | imgt | ` {"__current_case__": 0, "library_selector": "builtin", "species": "9606"} ` |
       | contig\_assembly | ` "true" ` |
       | impute\_germline\_on\_export | ` "true" ` |
       | only\_productive | ` "false" ` |
       | receptor\_type | ` "xcr" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "fastqsanger" ` |



  </div></details>


</details>

**Comment by jennaj** [comment]
Deprecated by IUC re licence issues

https://github.com/galaxyproject/usegalaxy-tools/issues/569
