### ISSUE TITLE
test annotatemyids 3.14.0+galaxy1

### ISSUE THREAD

**Issue by natefoo** [mvdbeek/usegalaxy-tests#69]

**Comment by natefoo** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/iuc/annotatemyids/annotatemyids/3.14.0+galaxy1

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 100.0%" aria-valuenow="6" aria-valuemin="0" aria-valuemax="6" data-toggle="tooltip" title="6 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="6" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="6" title="0 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 6 |
| Passed     | 6 |
| Error      | 0 |
| Failure    | 0 |
| Skipped    | 0 |


<details><summary>Passed s</summary>

* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/annotatemyids/annotatemyids (Test #1)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      Warning message:
      In Sys.setlocale("LC_MESSAGES", "en_US.UTF-8") :
        OS reports request to set locale to "en_US.UTF-8" cannot be honored
      'select()' returned 1:many mapping between keys and columns

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | file\_has\_header | ` "false" ` |
       | organism | ` "Hs" ` |
       | id\_type | ` "SYMBOL" ` |
       | output\_cols | ` ["ENSEMBL", "ENTREZID", "SYMBOL", "GENENAME"] ` |
       | remove\_dups | ` "false" ` |
       | rscriptOpt | ` "false" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "tabular" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/annotatemyids/annotatemyids (Test #2)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      Warning message:
      In Sys.setlocale("LC_MESSAGES", "en_US.UTF-8") :
        OS reports request to set locale to "en_US.UTF-8" cannot be honored
      'select()' returned 1:1 mapping between keys and columns

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | file\_has\_header | ` "false" ` |
       | organism | ` "Hs" ` |
       | id\_type | ` "ENSEMBL" ` |
       | output\_cols | ` ["ENSEMBL", "ENTREZID", "SYMBOL", "GENENAME"] ` |
       | remove\_dups | ` "false" ` |
       | rscriptOpt | ` "true" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "tabular" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/annotatemyids/annotatemyids (Test #3)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      Warning message:
      In Sys.setlocale("LC_MESSAGES", "en_US.UTF-8") :
        OS reports request to set locale to "en_US.UTF-8" cannot be honored
      'select()' returned 1:many mapping between keys and columns

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | file\_has\_header | ` "false" ` |
       | organism | ` "Hs" ` |
       | id\_type | ` "ENSEMBL" ` |
       | output\_cols | ` ["ENSEMBL", "GO", "ONTOLOGY", "EVIDENCE"] ` |
       | remove\_dups | ` "false" ` |
       | rscriptOpt | ` "false" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "tabular" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/annotatemyids/annotatemyids (Test #4)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      Warning message:
      In Sys.setlocale("LC_MESSAGES", "en_US.UTF-8") :
        OS reports request to set locale to "en_US.UTF-8" cannot be honored
      'select()' returned 1:many mapping between keys and columns

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | file\_has\_header | ` "false" ` |
       | organism | ` "Hs" ` |
       | id\_type | ` "ENSEMBL" ` |
       | output\_cols | ` ["ENSEMBL", "GO", "ONTOLOGY", "EVIDENCE"] ` |
       | remove\_dups | ` "true" ` |
       | rscriptOpt | ` "false" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "tabular" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/annotatemyids/annotatemyids (Test #5)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      Warning message:
      In Sys.setlocale("LC_MESSAGES", "en_US.UTF-8") :
        OS reports request to set locale to "en_US.UTF-8" cannot be honored
      'select()' returned 1:many mapping between keys and columns

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | file\_has\_header | ` "false" ` |
       | organism | ` "At" ` |
       | id\_type | ` "SYMBOL" ` |
       | output\_cols | ` ["GO", "ENTREZID"] ` |
       | remove\_dups | ` "false" ` |
       | rscriptOpt | ` "false" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "tabular" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/annotatemyids/annotatemyids (Test #6)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      Warning message:
      In Sys.setlocale("LC_MESSAGES", "en_US.UTF-8") :
        OS reports request to set locale to "en_US.UTF-8" cannot be honored
      'select()' returned 1:many mapping between keys and columns

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | file\_has\_header | ` "false" ` |
       | organism | ` "Gg" ` |
       | id\_type | ` "SYMBOL" ` |
       | output\_cols | ` ["GO", "ENTREZID"] ` |
       | remove\_dups | ` "false" ` |
       | rscriptOpt | ` "false" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "tabular" ` |



  </div></details>


</details>
