### ISSUE TITLE
Test pangolin 3.1.17+galaxy1

### ISSUE THREAD

**Issue by natefoo** [mvdbeek/usegalaxy-tests#7]
Installed in galaxyproject/usegalaxy-tools#451

**Comment by natefoo** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/iuc/pangolin/pangolin/3.1.17+galaxy1

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 50.0%" aria-valuenow="2" aria-valuemin="0" aria-valuemax="4" data-toggle="tooltip" title="2 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="4" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 50.0%" aria-valuenow="2" aria-valuemin="0" aria-valuemax="4" title="2 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 4 |
| Passed     | 2 |
| Error      | 2 |
| Failure    | 0 |
| Skipped    | 0 |


<details><summary>Errored s</summary>

* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/iuc/pangolin/pangolin (Test #1)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Expecting value: line 1 column 1 (char 0)
      ```

  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/iuc/pangolin/pangolin (Test #2)</summary><div class="padded">

    **Execution Problem:**
    * ```
      Input staging problem: Expecting value: line 1 column 1 (char 0)
      ```

  </div></details>


</details>
<details><summary>Passed s</summary>

* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/pangolin/pangolin (Test #3)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      pangolearn already latest release (2021-12-06)
      constellations updated to v0.1.1
      pango-designation already latest release (v1.2.112)
      Job stats:
      job                     count    min threads    max threads
      --------------------  -------  -------------  -------------
      add_failed_seqs             1              1              1
      align_to_reference          1              1              1
      all                         1              1              1
      generate_report             1              1              1
      get_constellations          1              1              1
      hash_sequence_assign        1              1              1
      pangolearn                  1              1              1
      scorpio                     1              1              1
      total                       8              1              1


      ```
    **Standard Output:**

    * ```console
      loading model 12/16/2021, 21:05:23
      processing block of 1 sequences 12/16/2021, 21:05:25
      complete 12/16/2021, 21:05:25
      [32mOutput file written to: [0m/corral4/main/jobs/039/705/39705554/working/report.csv
      [32mOutput alignment written to: [0m/corral4/main/jobs/039/705/39705554/working/sequences.aln.fasta
      [32mAll dependencies satisfied.[0m
      [32mThe query file is:[0m/corral4/main/objects/5/8/3/dataset_5830703f-01a1-498a-94be-9eb2a4309059.dat
      [32m** Running sequence QC **[0m
      [32mNumber of sequences detected: [0m1
      [32mTotal passing QC: [0m1
      [32m
      Data files found:[0m
      Trained model:	/usr/local/lib/python3.8/site-packages/pangoLEARN/data/decisionTree_v1.joblib
      Header file:	/usr/local/lib/python3.8/site-packages/pangoLEARN/data/decisionTreeHeaders_v1.joblib
      Designated hash:	/usr/local/lib/python3.8/site-packages/pangoLEARN/data/lineages.hash.csv

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | usher | ` "false" ` |
       | alignment | ` "true" ` |
       | max\_ambig | ` "0.5" ` |
       | min\_length | ` "10000" ` |
       | include\_header | ` "false" ` |
       | db | ` {"__current_case__": 0, "source": "download"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/pangolin/pangolin (Test #4)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      pangolearn already latest release (2021-12-06)
      constellations updated to v0.1.1
      pango-designation already latest release (v1.2.112)
      Job stats:
      job                     count    min threads    max threads
      --------------------  -------  -------------  -------------
      add_failed_seqs             1              1              1
      align_to_reference          1              1              1
      all                         1              1              1
      generate_report             1              1              1
      get_constellations          1              1              1
      hash_sequence_assign        1              1              1
      pangolearn                  1              1              1
      scorpio                     1              1              1
      total                       8              1              1


      ```
    **Standard Output:**

    * ```console
      loading model 12/16/2021, 21:04:27
      processing block of 6 sequences 12/16/2021, 21:04:28
      complete 12/16/2021, 21:04:28
      [32mOutput file written to: [0m/corral4/main/jobs/039/705/39705556/working/report.csv
      [32mAll dependencies satisfied.[0m
      [32mThe query file is:[0m/corral4/main/objects/4/d/f/dataset_4df88074-3eb4-49f9-91ee-ca8bdf5cdd5c.dat
      [32m** Running sequence QC **[0m
      [32mNumber of sequences detected: [0m34
      [32mTotal passing QC: [0m34
      [32m
      Data files found:[0m
      Trained model:	/usr/local/lib/python3.8/site-packages/pangoLEARN/data/decisionTree_v1.joblib
      Header file:	/usr/local/lib/python3.8/site-packages/pangoLEARN/data/decisionTreeHeaders_v1.joblib
      Designated hash:	/usr/local/lib/python3.8/site-packages/pangoLEARN/data/lineages.hash.csv

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | usher | ` "false" ` |
       | alignment | ` "false" ` |
       | max\_ambig | ` "0.5" ` |
       | min\_length | ` "10000" ` |
       | include\_header | ` "true" ` |
       | db | ` {"__current_case__": 0, "source": "download"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


</details>

**Comment by natefoo** [comment]
Again all 4 passed when run from the command line. =/
