### ISSUE TITLE
test egsea 1.20.0

### ISSUE THREAD

**Issue by jennaj** [mvdbeek/usegalaxy-tests#76]
toolshed.g2.bx.psu.edu/repos/iuc/egsea/egsea/1.20.0

user reported in bugs -- most outputs selected -- and at least one is missing a dependency (?). Seems new.

> stderr
> Warning message:
> In Sys.setlocale("LC_MESSAGES", "en_US.UTF-8") :
>   OS reports request to set locale to "en_US.UTF-8" cannot be honored
> 
> groupGOTerms: 	GOBPTerm, GOMFTerm, GOCCTerm environments built.
> Error: package or namespace load failed for 'EGSEA':
>  .onLoad failed in loadNamespace() for 'HDF5Array', details:
>   call: H5Fcreate(file)
>   error: HDF5. File accessibility. Unable to open file.

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/iuc/egsea/egsea/1.20.0

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 100.0%" aria-valuenow="7" aria-valuemin="0" aria-valuemax="7" data-toggle="tooltip" title="7 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="7" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="7" title="0 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 7 |
| Passed     | 7 |
| Error      | 0 |
| Failure    | 0 |
| Skipped    | 0 |


<details><summary>Passed s</summary>

* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/egsea/egsea (Test #1)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      Warning message:
      In Sys.setlocale("LC_MESSAGES", "en_US.UTF-8") :
        OS reports request to set locale to "en_US.UTF-8" cannot be honored

      groupGOTerms: 	GOBPTerm, GOMFTerm, GOCCTerm environments built.
      EGSEA analysis has started
      Log fold changes are estimated using limma package ... 
      limma DE analysis is carried out ... 
      EGSEA is running on the provided data and h collection
      ..globaltest*camera*.ora*
      EGSEA analysis took 7.691 seconds.
      EGSEA analysis has completed
      EGSEA HTML report is being generated ...
      Report pages and figures are being generated for the h collection ...
         Heat maps are being generated for top-ranked gene sets 
      based on logFC ... 
         Summary plots are being generated ... 
      EGSEA report generation took 17.538 seconds.
      EGSEA report has been generated.

      ```
    **Standard Output:**

    * ```console
      [1] "Loading MSigDB Gene Sets ... "
      [1] "Loaded gene sets for the collection h ..."
      [1] "Indexed the collection h ..."
      [1] "Created annotation for the collection h ..."
      ##------ Tue Feb 14 18:18:26 2023 ------##
      ##------ Tue Feb 14 18:18:34 2023 ------##
      ##------ Tue Feb 14 18:18:34 2023 ------##
      ##------ Tue Feb 14 18:18:51 2023 ------##

      ```
    **Traceback:**

    * ```console
      
      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | input | ` {"__current_case__": 1, "counts": {"values": [{"id": 108312158, "src": "hda"}]}, "fact": {"__current_case__": 1, "ffile": "no", "rep_factor": [{"__index__": 0, "factorName": "Treatment", "groupNames": "IL13,IL13Ant,IL13,IL13,IL13Ant"}]}, "format": "matrix"} ` |
       | rep\_contrast | ` [{"__index__": 0, "contrast": "IL13Ant-IL13"}] ` |
       | species | ` "human" ` |
       | base\_methods | ` ["camera", "globaltest", "ora"] ` |
       | msigdb | ` {"msigdb_gsets": "h"} ` |
       | keggdb | ` {"kegg_updated": false, "keggdb_gsets": null} ` |
       | gsdb | ` {"gsdb_gsets": null} ` |
       | advanced | ` {"combine_method": "wilkinson", "display_top": "5", "fdr_cutoff": "0.05", "min_size": "2", "rdaOpt": false, "rscriptOpt": false, "sort_method": "med.rank"} ` |
       | non\_commercial\_use | ` true ` |
       | \_\_job\_resource | ` {"__current_case__": 0, "__job_resource__select": "no"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "auto" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/egsea/egsea (Test #2)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      Warning message:
      In Sys.setlocale("LC_MESSAGES", "en_US.UTF-8") :
        OS reports request to set locale to "en_US.UTF-8" cannot be honored

      groupGOTerms: 	GOBPTerm, GOMFTerm, GOCCTerm environments built.
      EGSEA analysis has started
      Log fold changes are estimated using limma package ... 
      limma DE analysis is carried out ... 
      EGSEA is running on the provided data and h collection
      ..globaltest*camera*.ora*
      EGSEA analysis took 11.809 seconds.
      EGSEA analysis has completed
      EGSEA HTML report is being generated ...
      Report pages and figures are being generated for the h collection ...
         Heat maps are being generated for top-ranked gene sets 
      based on logFC ... 
         Summary plots are being generated ... 
      EGSEA report generation took 72.774 seconds.
      EGSEA report has been generated.

      ```
    **Standard Output:**

    * ```console
      [1] "Loading MSigDB Gene Sets ... "
      [1] "Loaded gene sets for the collection h ..."
      [1] "Indexed the collection h ..."
      [1] "Created annotation for the collection h ..."
      ##------ Tue Feb 14 18:24:29 2023 ------##
      ##------ Tue Feb 14 18:24:40 2023 ------##
      ##------ Tue Feb 14 18:24:41 2023 ------##
      ##------ Tue Feb 14 18:25:54 2023 ------##

      ```
    **Traceback:**

    * ```console
      
      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | input | ` {"__current_case__": 1, "counts": {"values": [{"id": 108312158, "src": "hda"}]}, "fact": {"__current_case__": 0, "ffile": "yes", "finfo": {"values": [{"id": 108312163, "src": "hda"}]}}, "format": "matrix"} ` |
       | rep\_contrast | ` [{"__index__": 0, "contrast": "IL13Ant-IL13"}] ` |
       | species | ` "human" ` |
       | base\_methods | ` ["camera", "globaltest", "ora"] ` |
       | msigdb | ` {"msigdb_gsets": "h"} ` |
       | keggdb | ` {"kegg_updated": false, "keggdb_gsets": null} ` |
       | gsdb | ` {"gsdb_gsets": null} ` |
       | advanced | ` {"combine_method": "wilkinson", "display_top": "5", "fdr_cutoff": "0.05", "min_size": "2", "rdaOpt": false, "rscriptOpt": true, "sort_method": "med.rank"} ` |
       | non\_commercial\_use | ` true ` |
       | \_\_job\_resource | ` {"__current_case__": 0, "__job_resource__select": "no"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "tabular" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/egsea/egsea (Test #3)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      Warning message:
      In Sys.setlocale("LC_MESSAGES", "en_US.UTF-8") :
        OS reports request to set locale to "en_US.UTF-8" cannot be honored

      groupGOTerms: 	GOBPTerm, GOMFTerm, GOCCTerm environments built.
      EGSEA analysis has started
      Log fold changes are estimated using limma package ... 
      limma DE analysis is carried out ... 
      EGSEA is running on the provided data and h collection
      ....camera*globaltest*..ora*
      EGSEA analysis took 26.103 seconds.
      EGSEA analysis has completed
      EGSEA HTML report is being generated ...
      Report pages and figures are being generated for the h collection ...
         Heat maps are being generated for top-ranked gene sets 
      based on logFC ... 
         Summary plots are being generated ... 
         Comparison summary plots are being generated  ...
      EGSEA report generation took 224.219 seconds.
      EGSEA report has been generated.

      ```
    **Standard Output:**

    * ```console
      [1] "Loading MSigDB Gene Sets ... "
      [1] "Loaded gene sets for the collection h ..."
      [1] "Indexed the collection h ..."
      [1] "Created annotation for the collection h ..."
      ##------ Tue Feb 14 18:29:46 2023 ------##
      ##------ Tue Feb 14 18:30:13 2023 ------##
      ##------ Tue Feb 14 18:30:13 2023 ------##
      ##------ Tue Feb 14 18:33:57 2023 ------##

      ```
    **Traceback:**

    * ```console
      
      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | input | ` {"__current_case__": 1, "counts": {"values": [{"id": 108312158, "src": "hda"}]}, "fact": {"__current_case__": 0, "ffile": "yes", "finfo": {"values": [{"id": 108312163, "src": "hda"}]}}, "format": "matrix"} ` |
       | rep\_contrast | ` [{"__index__": 0, "contrast": "IL13Ant-IL13"}, {"__index__": 1, "contrast": "IL13-IL13Ant"}] ` |
       | species | ` "human" ` |
       | base\_methods | ` ["camera", "globaltest", "ora"] ` |
       | msigdb | ` {"msigdb_gsets": "h"} ` |
       | keggdb | ` {"kegg_updated": false, "keggdb_gsets": null} ` |
       | gsdb | ` {"gsdb_gsets": null} ` |
       | advanced | ` {"combine_method": "wilkinson", "display_top": "5", "fdr_cutoff": "0.05", "min_size": "2", "rdaOpt": false, "rscriptOpt": false, "sort_method": "med.rank"} ` |
       | non\_commercial\_use | ` true ` |
       | \_\_job\_resource | ` {"__current_case__": 0, "__job_resource__select": "no"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "tabular" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/egsea/egsea (Test #4)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      Warning message:
      In Sys.setlocale("LC_MESSAGES", "en_US.UTF-8") :
        OS reports request to set locale to "en_US.UTF-8" cannot be honored

      groupGOTerms: 	GOBPTerm, GOMFTerm, GOCCTerm environments built.
      EGSEA analysis has started
      Log fold changes are estimated using limma package ... 
      limma DE analysis is carried out ... 
      EGSEA is running on the provided data and h collection
      ..globaltest*camera*.ora*
      EGSEA analysis took 8.328 seconds.
      EGSEA analysis has completed
      EGSEA HTML report is being generated ...
      Report pages and figures are being generated for the h collection ...
         Heat maps are being generated for top-ranked gene sets 
      based on logFC ... 
         Summary plots are being generated ... 
      EGSEA report generation took 16.452 seconds.
      EGSEA report has been generated.

      ```
    **Standard Output:**

    * ```console
      [1] "Loading MSigDB Gene Sets ... "
      [1] "Loaded gene sets for the collection h ..."
      [1] "Indexed the collection h ..."
      [1] "Created annotation for the collection h ..."
      ##------ Tue Feb 14 18:19:15 2023 ------##
      ##------ Tue Feb 14 18:19:23 2023 ------##
      ##------ Tue Feb 14 18:19:23 2023 ------##
      ##------ Tue Feb 14 18:19:40 2023 ------##

      ```
    **Traceback:**

    * ```console
      
      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | input | ` {"__current_case__": 1, "counts": {"values": [{"id": 108312158, "src": "hda"}]}, "fact": {"__current_case__": 0, "ffile": "yes", "finfo": {"values": [{"id": 108312164, "src": "hda"}]}}, "format": "matrix"} ` |
       | rep\_contrast | ` [{"__index__": 0, "contrast": "IL13Ant-IL13"}] ` |
       | species | ` "human" ` |
       | base\_methods | ` ["camera", "globaltest", "ora"] ` |
       | msigdb | ` {"msigdb_gsets": "h"} ` |
       | keggdb | ` {"kegg_updated": false, "keggdb_gsets": null} ` |
       | gsdb | ` {"gsdb_gsets": null} ` |
       | advanced | ` {"combine_method": "wilkinson", "display_top": "5", "fdr_cutoff": "0.05", "min_size": "2", "rdaOpt": false, "rscriptOpt": false, "sort_method": "med.rank"} ` |
       | non\_commercial\_use | ` true ` |
       | \_\_job\_resource | ` {"__current_case__": 0, "__job_resource__select": "no"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "tabular" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/egsea/egsea (Test #5)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      Warning message:
      In Sys.setlocale("LC_MESSAGES", "en_US.UTF-8") :
        OS reports request to set locale to "en_US.UTF-8" cannot be honored

      groupGOTerms: 	GOBPTerm, GOMFTerm, GOCCTerm environments built.
      EGSEA analysis has started
      Log fold changes are estimated using limma package ... 
      limma DE analysis is carried out ... 
      EGSEA is running on the provided data and h collection
      ......gage*.safe*globaltest*...zscore*.camera*.ssgsea*roast*.gsva*..fry*ora*.plage*padog*
      EGSEA analysis took 25.536 seconds.
      EGSEA analysis has completed
      EGSEA HTML report is being generated ...
      Report pages and figures are being generated for the h collection ...
         Heat maps are being generated for top-ranked gene sets 
      based on logFC ... 
         Summary plots are being generated ... 
      EGSEA report generation took 80.473 seconds.
      EGSEA report has been generated.

      ```
    **Standard Output:**

    * ```console
      [1] "Loading MSigDB Gene Sets ... "
      [1] "Loaded gene sets for the collection h ..."
      [1] "Indexed the collection h ..."
      [1] "Created annotation for the collection h ..."
      ##------ Tue Feb 14 18:20:46 2023 ------##
      ##------ Tue Feb 14 18:21:12 2023 ------##
      ##------ Tue Feb 14 18:21:13 2023 ------##
      ##------ Tue Feb 14 18:22:33 2023 ------##

      ```
    **Traceback:**

    * ```console
      
      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | input | ` {"__current_case__": 1, "counts": {"values": [{"id": 108312158, "src": "hda"}]}, "fact": {"__current_case__": 0, "ffile": "yes", "finfo": {"values": [{"id": 108312164, "src": "hda"}]}}, "format": "matrix"} ` |
       | rep\_contrast | ` [{"__index__": 0, "contrast": "IL13Ant-IL13"}] ` |
       | species | ` "human" ` |
       | base\_methods | ` ["camera", "safe", "gage", "zscore", "gsva", "globaltest", "ora", "ssgsea", "padog", "plage", "fry", "roast"] ` |
       | msigdb | ` {"msigdb_gsets": "h"} ` |
       | keggdb | ` {"kegg_updated": false, "keggdb_gsets": null} ` |
       | gsdb | ` {"gsdb_gsets": null} ` |
       | advanced | ` {"combine_method": "wilkinson", "display_top": "5", "fdr_cutoff": "0.05", "min_size": "2", "rdaOpt": false, "rscriptOpt": false, "sort_method": "med.rank"} ` |
       | non\_commercial\_use | ` true ` |
       | \_\_job\_resource | ` {"__current_case__": 0, "__job_resource__select": "no"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "tabular" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/egsea/egsea (Test #6)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      Warning message:
      In Sys.setlocale("LC_MESSAGES", "en_US.UTF-8") :
        OS reports request to set locale to "en_US.UTF-8" cannot be honored

      groupGOTerms: 	GOBPTerm, GOMFTerm, GOCCTerm environments built.
      EGSEA analysis has started
      Log fold changes are estimated using limma package ... 
      limma DE analysis is carried out ... 
      EGSEA is running on the provided data and h collection
      ..globaltest*camera*.ora*
      EGSEA is running on the provided data and kegg collection
      ..globaltest*camera*.ora*
      EGSEA analysis took 13.279 seconds.
      EGSEA analysis has completed
      EGSEA HTML report is being generated ...
      Report pages and figures are being generated for the h collection ...
         Heat maps are being generated for top-ranked gene sets 
      based on logFC ... 
         Summary plots are being generated ... 
      Report pages and figures are being generated for the kegg collection ...
         Pathway maps are being generated for top-ranked 
       pathways based on logFC ... 
         Heat maps are being generated for top-ranked gene sets 
      based on logFC ... 
         Summary plots are being generated ... 
      EGSEA report generation took 125.054 seconds.
      EGSEA report has been generated.

      ```
    **Standard Output:**

    * ```console
      [1] "Loading MSigDB Gene Sets ... "
      [1] "Loaded gene sets for the collection h ..."
      [1] "Indexed the collection h ..."
      [1] "Created annotation for the collection h ..."
      [1] "Building KEGG pathways annotation object ... "
      ##------ Tue Feb 14 18:28:14 2023 ------##
      ##------ Tue Feb 14 18:28:27 2023 ------##
      ##------ Tue Feb 14 18:28:27 2023 ------##
      ##------ Tue Feb 14 18:30:32 2023 ------##

      ```
    **Traceback:**

    * ```console
      
      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | input | ` {"__current_case__": 1, "counts": {"values": [{"id": 108312158, "src": "hda"}]}, "fact": {"__current_case__": 0, "ffile": "yes", "finfo": {"values": [{"id": 108312164, "src": "hda"}]}}, "format": "matrix"} ` |
       | rep\_contrast | ` [{"__index__": 0, "contrast": "IL13Ant-IL13"}] ` |
       | species | ` "human" ` |
       | base\_methods | ` ["camera", "globaltest", "ora"] ` |
       | msigdb | ` {"msigdb_gsets": "h"} ` |
       | keggdb | ` {"kegg_updated": true, "keggdb_gsets": "keggmet"} ` |
       | gsdb | ` {"gsdb_gsets": null} ` |
       | advanced | ` {"combine_method": "wilkinson", "display_top": "5", "fdr_cutoff": "0.05", "min_size": "2", "rdaOpt": false, "rscriptOpt": false, "sort_method": "med.rank"} ` |
       | non\_commercial\_use | ` true ` |
       | \_\_job\_resource | ` {"__current_case__": 0, "__job_resource__select": "no"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "tabular" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/egsea/egsea (Test #7)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      Warning message:
      In Sys.setlocale("LC_MESSAGES", "en_US.UTF-8") :
        OS reports request to set locale to "en_US.UTF-8" cannot be honored

      groupGOTerms: 	GOBPTerm, GOMFTerm, GOCCTerm environments built.
      EGSEA analysis has started
      Log fold changes are estimated using limma package ... 
      limma DE analysis is carried out ... 
      EGSEA is running on the provided data and h collection
      ..globaltest*camera*.ora*
      EGSEA analysis took 9.145 seconds.
      EGSEA analysis has completed
      EGSEA HTML report is being generated ...
      Report pages and figures are being generated for the h collection ...
         Heat maps are being generated for top-ranked gene sets 
      based on logFC ... 
         Summary plots are being generated ... 
      EGSEA report generation took 15.473 seconds.
      EGSEA report has been generated.

      ```
    **Standard Output:**

    * ```console
      [1] "Loading MSigDB Gene Sets ... "
      [1] "Loaded gene sets for the collection h ..."
      [1] "Indexed the collection h ..."
      [1] "Created annotation for the collection h ..."
      ##------ Tue Feb 14 18:22:25 2023 ------##
      ##------ Tue Feb 14 18:22:34 2023 ------##
      ##------ Tue Feb 14 18:22:34 2023 ------##
      ##------ Tue Feb 14 18:22:50 2023 ------##

      ```
    **Traceback:**

    * ```console
      
      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | input | ` {"__current_case__": 0, "format": "files", "rep_factor": [{"__index__": 0, "factorName": "Treatment", "rep_group": [{"__index__": 0, "countsFile": {"values": [{"id": 108312174, "src": "hda"}, {"id": 108312176, "src": "hda"}, {"id": 108312177, "src": "hda"}]}, "groupName": "IL13"}, {"__index__": 1, "countsFile": {"values": [{"id": 108312175, "src": "hda"}, {"id": 108312178, "src": "hda"}]}, "groupName": "IL13Ant"}]}, {"__index__": 1, "factorName": "Batch", "rep_group": [{"__index__": 0, "countsFile": {"values": [{"id": 108312174, "src": "hda"}, {"id": 108312175, "src": "hda"}]}, "groupName": "b1"}, {"__index__": 1, "countsFile": {"values": [{"id": 108312176, "src": "hda"}, {"id": 108312177, "src": "hda"}, {"id": 108312178, "src": "hda"}]}, "groupName": "b2"}]}]} ` |
       | rep\_contrast | ` [{"__index__": 0, "contrast": "IL13Ant-IL13"}] ` |
       | species | ` "human" ` |
       | base\_methods | ` ["camera", "globaltest", "ora"] ` |
       | msigdb | ` {"msigdb_gsets": "h"} ` |
       | keggdb | ` {"kegg_updated": false, "keggdb_gsets": null} ` |
       | gsdb | ` {"gsdb_gsets": null} ` |
       | advanced | ` {"combine_method": "wilkinson", "display_top": "5", "fdr_cutoff": "0.05", "min_size": "2", "rdaOpt": false, "rscriptOpt": false, "sort_method": "med.rank"} ` |
       | non\_commercial\_use | ` true ` |
       | \_\_job\_resource | ` {"__current_case__": 0, "__job_resource__select": "no"} ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "tabular" ` |



  </div></details>


</details>
