### ISSUE TITLE
Test SEACR 1.3+galaxy1 on usegalaxy.org

### ISSUE THREAD

**Issue by natefoo** [mvdbeek/usegalaxy-tests#8]
Installed in galaxyproject/usegalaxy-tools#452

**Comment by natefoo** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/iuc/seacr/seacr/1.3+galaxy1

**Comment by natefoo** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/iuc/seacr/seacr/1.3+galaxy1

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="3" data-toggle="tooltip" title="0 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="3" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 100.0%" aria-valuenow="3" aria-valuemin="0" aria-valuemax="3" title="3 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 3 |
| Passed     | 0 |
| Error      | 0 |
| Failure    | 3 |
| Skipped    | 0 |


<details><summary>Failed s</summary>

* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/iuc/seacr/seacr (Test #1)</summary><div class="padded">

    **Problems**:
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/seacr/seacr/1.3+galaxy1, exit_code: None, stderr: .
      ```
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/seacr/seacr/1.3+galaxy1, exit_code: None, stderr: .
      ```
    **Command Line:**

    * ```console
      
      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | control\_cond | ` {"__current_case__": 1, "control_sel": "t", "t": "0.2"} ` |
       | normalize | ` "true" ` |
       | mode | ` "stringent" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "bed" ` |



  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/iuc/seacr/seacr (Test #2)</summary><div class="padded">

    **Problems**:
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/seacr/seacr/1.3+galaxy1, exit_code: None, stderr: .
      ```
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/seacr/seacr/1.3+galaxy1, exit_code: None, stderr: .
      ```
    **Command Line:**

    * ```console
      
      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | control\_cond | ` {"__current_case__": 1, "control_sel": "t", "t": "0.1"} ` |
       | normalize | ` "false" ` |
       | mode | ` "relaxed" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "auto" ` |



  </div></details>


* <details class="rcorners light-red"><summary class="light-red">&#10060; toolshed.g2.bx.psu.edu/repos/iuc/seacr/seacr (Test #3)</summary><div class="padded">

    **Problems**:
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/seacr/seacr/1.3+galaxy1, exit_code: None, stderr: .
      ```
    * ```
      Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/seacr/seacr/1.3+galaxy1, exit_code: None, stderr: .
      ```
    **Command Line:**

    * ```console
      
      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | control\_cond | ` {"__current_case__": 0, "control_sel": "f", "f": {"values": [{"id": 88935552, "src": "hda"}]}} ` |
       | normalize | ` "true" ` |
       | mode | ` "relaxed" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "bed" ` |



  </div></details>


</details>

**Comment by natefoo** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/iuc/seacr/seacr/1.3+galaxy1

Forgot to restart the first time, forgot I needed to snapshot and restart the second time...

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 100.0%" aria-valuenow="3" aria-valuemin="0" aria-valuemax="3" data-toggle="tooltip" title="3 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="3" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="3" title="0 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 3 |
| Passed     | 3 |
| Error      | 0 |
| Failure    | 0 |
| Skipped    | 0 |


<details><summary>Passed s</summary>

* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/seacr/seacr (Test #1)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Output:**

    * ```console
      Calling enriched regions without control file
      Normalizing control to experimental bedgraph
      Using stringent threshold
      Creating experimental AUC file: Tue Jan  4 12:03:38 CST 2022
      Calculating optimal AUC threshold: Tue Jan  4 12:03:38 CST 2022
      Using user-provided threshold: Tue Jan  4 12:03:38 CST 2022
      Creating thresholded feature file: Tue Jan  4 12:03:47 CST 2022
      Empirical false discovery rate = 0.2
      Merging nearby features and eliminating control-enriched features: Tue Jan  4 12:03:47 CST 2022
      Removing temporary files: Tue Jan  4 12:03:47 CST 2022
      Done: Tue Jan  4 12:03:47 CST 2022

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | control\_cond | ` {"__current_case__": 1, "control_sel": "t", "t": "0.2"} ` |
       | normalize | ` "true" ` |
       | mode | ` "stringent" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "bed" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/seacr/seacr (Test #2)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Output:**

    * ```console
      Calling enriched regions without control file
      Proceeding without normalization of control to experimental bedgraph
      Using relaxed threshold
      Creating experimental AUC file: Tue Jan  4 12:03:38 CST 2022
      Calculating optimal AUC threshold: Tue Jan  4 12:03:38 CST 2022
      Using user-provided threshold: Tue Jan  4 12:03:38 CST 2022
      Creating thresholded feature file: Tue Jan  4 12:03:47 CST 2022
      Empirical false discovery rate = 
      Merging nearby features and eliminating control-enriched features: Tue Jan  4 12:03:47 CST 2022
      Removing temporary files: Tue Jan  4 12:03:47 CST 2022
      Done: Tue Jan  4 12:03:47 CST 2022

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | control\_cond | ` {"__current_case__": 1, "control_sel": "t", "t": "0.1"} ` |
       | normalize | ` "false" ` |
       | mode | ` "relaxed" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "auto" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/seacr/seacr (Test #3)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Output:**

    * ```console
      Calling enriched regions with control file
      Normalizing control to experimental bedgraph
      Using relaxed threshold
      Creating experimental AUC file: Tue Jan  4 12:03:40 CST 2022
      Creating control AUC file: Tue Jan  4 12:03:40 CST 2022
      Calculating optimal AUC threshold: Tue Jan  4 12:03:40 CST 2022
      Calculating threshold using normalized control: Tue Jan  4 12:03:40 CST 2022
      Creating thresholded feature file: Tue Jan  4 12:03:47 CST 2022
      Empirical false discovery rate = 0.181818181818182
      Merging nearby features and eliminating control-enriched features: Tue Jan  4 12:03:47 CST 2022
      Removing temporary files: Tue Jan  4 12:03:47 CST 2022
      Done: Tue Jan  4 12:03:47 CST 2022

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | control\_cond | ` {"__current_case__": 0, "control_sel": "f", "f": {"values": [{"id": 88936436, "src": "hda"}]}} ` |
       | normalize | ` "true" ` |
       | mode | ` "relaxed" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "auto" ` |



  </div></details>


</details>
