### ISSUE TITLE
Test gffread 2.2.1.3+galaxy0

### ISSUE THREAD

**Issue by natefoo** [mvdbeek/usegalaxy-tests#9]
Installed in galaxyproject/usegalaxy-tools#453.

**Comment by natefoo** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/devteam/gffread/gffread/2.2.1.3+galaxy0

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 100.0%" aria-valuenow="10" aria-valuemin="0" aria-valuemax="10" data-toggle="tooltip" title="10 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="10" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="10" title="0 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 10 |
| Passed     | 10 |
| Error      | 0 |
| Failure    | 0 |
| Skipped    | 0 |


<details><summary>Passed s</summary>

* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/devteam/gffread/gffread (Test #1)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | filtering | ` None ` |
       | region | ` {"__current_case__": 0, "region_filter": "none"} ` |
       | maxintron | ` "" ` |
       | chr\_replace | ` None ` |
       | merging | ` {"__current_case__": 0, "merge_sel": "none"} ` |
       | reference\_genome | ` {"__current_case__": 0, "source": "none"} ` |
       | gffs | ` {"__current_case__": 1, "ensembl": "false", "gff_fmt": "gff", "tname": ""} ` |
       | full\_gff\_attribute\_preservation | ` "false" ` |
       | decode\_url | ` "false" ` |
       | expose | ` "false" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/devteam/gffread/gffread (Test #2)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | filtering | ` None ` |
       | region | ` {"__current_case__": 0, "region_filter": "none"} ` |
       | maxintron | ` "" ` |
       | chr\_replace | ` None ` |
       | merging | ` {"__current_case__": 0, "merge_sel": "none"} ` |
       | reference\_genome | ` {"__current_case__": 0, "source": "none"} ` |
       | gffs | ` {"__current_case__": 1, "ensembl": "false", "gff_fmt": "gff", "tname": ""} ` |
       | full\_gff\_attribute\_preservation | ` "false" ` |
       | decode\_url | ` "false" ` |
       | expose | ` "false" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/devteam/gffread/gffread (Test #3)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | filtering | ` None ` |
       | region | ` {"__current_case__": 0, "region_filter": "none"} ` |
       | maxintron | ` "" ` |
       | chr\_replace | ` None ` |
       | merging | ` {"__current_case__": 0, "merge_sel": "none"} ` |
       | reference\_genome | ` {"__current_case__": 0, "source": "none"} ` |
       | gffs | ` {"__current_case__": 1, "ensembl": "false", "gff_fmt": "gff", "tname": ""} ` |
       | full\_gff\_attribute\_preservation | ` "true" ` |
       | decode\_url | ` "false" ` |
       | expose | ` "false" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/devteam/gffread/gffread (Test #4)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | filtering | ` None ` |
       | region | ` {"__current_case__": 0, "region_filter": "none"} ` |
       | maxintron | ` "" ` |
       | chr\_replace | ` None ` |
       | merging | ` {"__current_case__": 0, "merge_sel": "none"} ` |
       | reference\_genome | ` {"__current_case__": 0, "source": "none"} ` |
       | gffs | ` {"__current_case__": 3, "gff_fmt": "bed"} ` |
       | full\_gff\_attribute\_preservation | ` "false" ` |
       | decode\_url | ` "false" ` |
       | expose | ` "false" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/devteam/gffread/gffread (Test #5)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | filtering | ` None ` |
       | region | ` {"__current_case__": 0, "region_filter": "none"} ` |
       | maxintron | ` "" ` |
       | chr\_replace | ` None ` |
       | merging | ` {"__current_case__": 0, "merge_sel": "none"} ` |
       | reference\_genome | ` {"__current_case__": 0, "source": "none"} ` |
       | gffs | ` {"__current_case__": 1, "ensembl": "false", "gff_fmt": "gff", "tname": "track name"} ` |
       | full\_gff\_attribute\_preservation | ` "false" ` |
       | decode\_url | ` "false" ` |
       | expose | ` "false" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/devteam/gffread/gffread (Test #6)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | filtering | ` None ` |
       | region | ` {"__current_case__": 1, "discard_partial": "false", "range": "19:496500..504965", "region_filter": "filter"} ` |
       | maxintron | ` "" ` |
       | chr\_replace | ` None ` |
       | merging | ` {"__current_case__": 0, "merge_sel": "none"} ` |
       | reference\_genome | ` {"__current_case__": 0, "source": "none"} ` |
       | gffs | ` {"__current_case__": 2, "gff_fmt": "gtf", "tname": ""} ` |
       | full\_gff\_attribute\_preservation | ` "false" ` |
       | decode\_url | ` "false" ` |
       | expose | ` "false" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/devteam/gffread/gffread (Test #7)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | filtering | ` None ` |
       | region | ` {"__current_case__": 1, "discard_partial": "true", "range": "19:496500..504965", "region_filter": "filter"} ` |
       | maxintron | ` "" ` |
       | chr\_replace | ` None ` |
       | merging | ` {"__current_case__": 0, "merge_sel": "none"} ` |
       | reference\_genome | ` {"__current_case__": 0, "source": "none"} ` |
       | gffs | ` {"__current_case__": 2, "gff_fmt": "gtf", "tname": ""} ` |
       | full\_gff\_attribute\_preservation | ` "false" ` |
       | decode\_url | ` "false" ` |
       | expose | ` "false" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/devteam/gffread/gffread (Test #8)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | filtering | ` "-C" ` |
       | region | ` {"__current_case__": 1, "discard_partial": "false", "range": "19:496500..504965", "region_filter": "filter"} ` |
       | maxintron | ` "" ` |
       | chr\_replace | ` None ` |
       | merging | ` {"__current_case__": 0, "merge_sel": "none"} ` |
       | reference\_genome | ` {"__current_case__": 0, "source": "none"} ` |
       | gffs | ` {"__current_case__": 2, "gff_fmt": "gtf", "tname": ""} ` |
       | full\_gff\_attribute\_preservation | ` "false" ` |
       | decode\_url | ` "false" ` |
       | expose | ` "false" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/devteam/gffread/gffread (Test #9)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      FASTA index file genomeref.fa.fai created.

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | filtering | ` None ` |
       | region | ` {"__current_case__": 1, "discard_partial": "false", "range": "19:496500..504965", "region_filter": "filter"} ` |
       | maxintron | ` "" ` |
       | chr\_replace | ` None ` |
       | merging | ` {"__current_case__": 0, "merge_sel": "none"} ` |
       | reference\_genome | ` {"__current_case__": 2, "fa_outputs": ["-w exons.fa", "-x cds.fa", "-y pep.fa"], "genome_fasta": {"values": [{"id": 88938569, "src": "hda"}]}, "ref_filtering": null, "source": "history"} ` |
       | gffs | ` {"__current_case__": 2, "gff_fmt": "gtf", "tname": ""} ` |
       | full\_gff\_attribute\_preservation | ` "false" ` |
       | decode\_url | ` "false" ` |
       | expose | ` "false" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/devteam/gffread/gffread (Test #10)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Error:**

    * ```console
      FASTA index file genomeref.fa.fai created.

      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | filtering | ` None ` |
       | region | ` {"__current_case__": 0, "region_filter": "none"} ` |
       | maxintron | ` "" ` |
       | chr\_replace | ` None ` |
       | merging | ` {"__current_case__": 0, "merge_sel": "none"} ` |
       | reference\_genome | ` {"__current_case__": 2, "fa_outputs": ["-y pep.fa", "-S"], "genome_fasta": {"values": [{"id": 88938569, "src": "hda"}]}, "ref_filtering": null, "source": "history"} ` |
       | gffs | ` {"__current_case__": 0, "gff_fmt": "none"} ` |
       | full\_gff\_attribute\_preservation | ` "false" ` |
       | decode\_url | ` "false" ` |
       | expose | ` "false" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "input" ` |



  </div></details>


</details>
