### ISSUE TITLE
test intervene_upset 0.6.5+galaxy2

### ISSUE THREAD

**Issue by jennaj** [mvdbeek/usegalaxy-tests#98]
Crashing due to memory at ORG. Running tool test to see if that works or not.
toolshed.g2.bx.psu.edu/repos/iuc/intervene/intervene_upset/0.6.5+galaxy2

**Comment by jennaj** [comment]
/run-tool-test tool_id=toolshed.g2.bx.psu.edu/repos/iuc/intervene/intervene_upset/0.6.5+galaxy2

**Comment by mvdbeek** [comment]
#  Results (powered by Planemo)

##  Summary

<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 100.0%" aria-valuenow="2" aria-valuemin="0" aria-valuemax="2" data-toggle="tooltip" title="2 Passed">
  </div>
  <div class="progress-bar progress-bar-warning" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="2" data-toggle="tooltip" title="0 Skipped">
  </div>
  <div class="progress-bar progress-bar-danger" style="width: 0.0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="2" title="0 Failed or Errored">
  </div>
</div>

|  State | Count |
| ---------- | ----- |
| Total      | 2 |
| Passed     | 2 |
| Error      | 0 |
| Failure    | 0 |
| Skipped    | 0 |


<details><summary>Passed s</summary>

* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/intervene/intervene_upset (Test #1)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Output:**

    * ```console
      
      Running UpSet module. Please wait...


      You are done! Please check your results @ results. 
      Thank you for using Intervene!


      ```
    **Traceback:**

    * ```console
      
      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | order | ` "freq" ` |
       | ninter | ` "30" ` |
       | showzero | ` false ` |
       | showsize | ` true ` |
       | mbcolor | ` "#ea5d4e" ` |
       | sbcolor | ` "#317eab" ` |
       | mblabel | ` "No. of Intersections" ` |
       | sxlabel | ` "Set size" ` |
       | figtype | ` "pdf" ` |
       | figsize\_width | ` "14" ` |
       | figsize\_height | ` "8" ` |
       | dpi | ` "300" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "txt" ` |



  </div></details>


* <details class="rcorners light-green"><summary class="light-green">&#9989; toolshed.g2.bx.psu.edu/repos/iuc/intervene/intervene_upset (Test #2)</summary><div class="padded">

    **Command Line:**

    * ```console
      
      ```
    **Exit Code:**

    * ```console
      0
      ```
    **Standard Output:**

    * ```console
      
      Running UpSet module. Please wait...


      You are done! Please check your results @ results. 
      Thank you for using Intervene!


      ```
    **Traceback:**

    * ```console
      
      ```
   **Job Parameters:**

   *   | Job parameter | Parameter value |
       | ------------- | --------------- |
       | order | ` "freq" ` |
       | ninter | ` "30" ` |
       | showzero | ` false ` |
       | showsize | ` true ` |
       | mbcolor | ` "#ea5d4e" ` |
       | sbcolor | ` "#317eab" ` |
       | mblabel | ` "No. of Intersections" ` |
       | sxlabel | ` "Set size" ` |
       | figtype | ` "pdf" ` |
       | figsize\_width | ` "14" ` |
       | figsize\_height | ` "8" ` |
       | dpi | ` "300" ` |
       | chromInfo | ` "/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len" ` |
       | dbkey | ` "?" ` |
       | \_\_input\_ext | ` "bed" ` |



  </div></details>


</details>
